### ISSUE TITLE
Can't connect to Ubuntu 16.04: Version mismatch, client refused.

### ISSUE THREAD

**Issue by Dieff** [microsoft/vscode-remote-release#1001]
Vscode is running on:
```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-09T11:32:10.645Z
Electron: 4.2.6
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.0-arch2-1-ARCH
Remote-SSH: 0.44.2
```

The remote server:
```
OS: 16.04.6 LTS (Xenial Xerus)
Kernel: Linux 4.4.0-154-generic x86_64 GNU/Linux
ldd: 2.23
```

Steps to Reproduce:

1. Attempt to connect to the host
2. Wait for the error message to appear:
```
Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)
```

The output of the Remote-SSH extension is:
```
remote-ssh@0.44.2
linux x64
SSH Resolver called for "ssh-remote+do", attempt 1
SSH Resolver called for host: do
Setting up SSH remote "do"
Using commit id "c3fe2d8acde04e579880413ae4622a1f551efdcc" and quality "insider" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
Running script with connection command: "ssh"  -o ClearAllForwardings=true -o ConnectTimeout=15   "do" bash
Install and start server if needed
> Running remote connection script
> Found existing installation at /home/dieff/.vscode-server-oss/bin/c3fe2d8acde04e579880413ae4622a1f551efdcc...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> 2940d58c-4aa8-4c21-9227-bd800dd6c82f==42557==38235==
"install" terminal command done
Received install output: 2940d58c-4aa8-4c21-9227-bd800dd6c82f==42557==38235==
Server is listening on port 42557
Running script with connection command: "ssh" -L 127.0.0.1:42557:127.0.0.1:42557  -o ConnectTimeout=15   "do" bash
Spawning tunnel with: "ssh" -L 127.0.0.1:42557:127.0.0.1:42557  -o ConnectTimeout=15   "do" bash << 'EOSSH'
echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity
EOSSH
> Connected to SSH Host - Please do not close this terminal
Spawned SSH tunnel between local port 42557 and remote port 42557
Waiting for ssh tunnel to be ready
Tunneling remote port 42557 to local port 42557
Resolved "ssh-remote+do" to "127.0.0.1:42557"
```
I have enabled `remote.SSH.ShowLoginTerminal`, but the resulting terminal shows no significant information.

**Comment by Hubro** [comment]
I'm getting the same error when connecting to Debian 9.

Local PC SSH version: `OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019`

Remote system SSH version: `OpenSSH_7.4p1 Debian-10+deb9u5, OpenSSL 1.0.2q  20 Nov 2018`

Does this extension require the local PC and remote to be running the same version of SSH?

**Comment by romanovzky** [comment]
The same as above, this extension does not work with vscode-oss version in Arch repositories. Official binary does.

**Comment by otaj** [comment]
Hi, the same happens here as well.

I just want to point out, this is *not* a WSL issue, but SSH issue. I do understand, that ArchLinux build is officially unsupported, but it would be nice to be able to use this extension anyway

**Comment by Sun1ive** [comment]
+1 running this issue as well
 OS: Arch Linux x86_64

**Comment by BrutalBirdie** [comment]
Same here.
```
4.19.84-1-MANJARO
```

Installed visual-studio-code-bin  1.40.1-1 from AUR and now it's working.
https://aur.archlinux.org/packages/visual-studio-code-bin

**Comment by sizzlorox** [comment]
Can confirm installing via AUR solved this issue for me.
`$ yay -S visual-studio-code-bin`

`
4.19.85-1-MANJARO
`

**Comment by madewild** [comment]
Same for me on Arch

`5.3.11-arch1-1`

**Comment by roblourens** [comment]
It sounds like this has been resolved? Someone please let me know if not. That error can also be seen when the remote doesn't meet the linux prereqs: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by FishHawk** [comment]
Still exist when using vscode-oss

**Comment by roblourens** [comment]
It's not possible to use remote with vscode-oss, since remote relies on non-oss components.

**Comment by Hubro** [comment]
> It's not possible to use remote with vscode-oss, since remote relies on non-oss components.

That's fine, but the current error message is still not acceptable. At the very least there should be a proper error message that explains that the plugin doesn't work on the OSS version.

**Comment by kido5217** [comment]
> It's not possible to use remote with vscode-oss, since remote relies on non-oss components.

Can you please clarify what are those components?

**Comment by roblourens** [comment]
There are some more details here: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy
