### ISSUE TITLE
Cannot connect to WSL 2 Ubuntu

### ISSUE THREAD

**Issue by chro8062** [microsoft/vscode-remote-release#11204]
I have WSL 2 with Ubuntu 22.04.2 LTS installed. I am on a windows 11 laptop. I have many WSL repos that I had been editing with vscode without issues until some recent WSL extension updates. Now I get an error "No WSL Distributions found". But I can access the wsl terminal like normal outside of vscode and have verified that WSL is installed and operating normally. Reverting back to v0.99.0 of the WSL extension resolved my issue.

**Comment by fabricebourel** [comment]
Hello,
ok the solution is to update your WSL2 kernel => wsl --update
Problem fixed in my team.
Cheers.

**Comment by HYR66** [comment]
i can't update wsl on my machine. I fallback version fixed this.
I think it seem the font not match utf-8 problem. wsl log

[2025-09-17 08:10:23.330] NodeExecServer run: C:\Windows\System32\wsl.exe --status 
[2025-09-17 08:10:23.413] WSL feature installed: true (wsl --status), using utf-8 encoding 
[2025-09-17 08:10:23.413] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose 
[2025-09-17 08:10:23.478] No distros found: " \u0000 \u0000N\u0000A\u0000M\u0000E\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000S\u0000T\u0000A\u0000T\u0000E\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000V\u0000E\u0000R\u0000S\u0000I\u0000O\u0000N\u0000\r\u0000\n\u0000*\u0000 \u0000U\u0000b\u0000u\u0000n\u0000t\u0000u\u0000 \u0000 \u0000 \u0000 \u0000R\u0000u\u0000n\u0000n\u0000i\u0000n\u0000g\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u00002\u0000\r\u0000\n\u0000" 
[2025-09-17 08:10:23.478] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose

**Comment by w616780** [comment]
I met the same question as above. When my wsl-remote in vscode is the lastest version:0.104.2, I can't conncet to WSL2 on the my remote server. And I was also told an error “No WSL Distributions found”.  And I entered into my sever via SSH, I found everything about WSL2 is as usual.
I tried to downgrade my wsl-remote extension to **Version 0.99** then the problem was solved. I could connect to WSL2 via wsl-remote extension in vscode.

**Comment by joshden** [comment]
> Hello, ok the solution is to update your WSL2 kernel => wsl --update Problem fixed in my team. Cheers.

Thank you. This worked for me. I did have to reboot Windows after doing `wsl --update` but now I can again use WSL in VS Code.

**Comment by bamurtaugh** [comment]
Thanks all for the discussion. Is anyone still experiencing issues, or has this been resolved with the above seps?

**Comment by fabricebourel** [comment]
> Thanks all for the discussion. Is anyone still experiencing issues, or has this been resolved with the above seps?

Hi Brigit. Updating WSL (with a reboot) solves the "no distro found" message indeed. If one cannot update his WSL, then this is a separate issue IMO. Regards, Fabrice.

**Comment by aeschli** [comment]
The 'no distro found' issue got fixed in vscode-wsl-remote 0.104.3
