### ISSUE TITLE
Devcontainer behind a proxy silently fails installing extensions from devcontainer.json

### ISSUE THREAD

**Issue by DYefimov** [microsoft/vscode-remote-release#11386]
After updating vscode to the latest version (1.107.0), my devcontainer silently fails installing project specific extensions from the devcontainer.json. I'm behind the proxy, but verified it's functioning correctly. The installation process hangs after the successful retrieval of the extension Manifest from the CDN.

Note, that installing extension at the host manually, then "Install in Devcontainer" it via GUI works just fine. Unfortunately, I'm in an early infrastructure phase of one project, and Rebuilding container is a must quite often, so loosing extensions every time is quite frustrating.

- Local OS Version: Debian GNU/Linux 11 (bullseye)
- Docker version: 29.1.3, build f52814d
- Proxy: socks5 (currently at my personal laptop, i.e. same host as vscode, to reduce the complexity of a setup)
- VSCode Version: 1.107.0
- Remote Extension: Dev Containers at localhost (side note: ssh to another host, and devcontainer there behaves just the same way)

I was trying to track down the root cause for a couple of days already, reading devcontainers logs and relevant vscode sources. The next logical step would be to debug vscode, but I'd rather not. Hopefully, there is a solution already.

To ensure a more clean test-bed, all tests were done with:
- rm -rf ~/.vscode ~/.vscode-server ~/.config/Code
- docker system prune -a
- docker volume rm vscode
- sudo apt update && sudo apt upgrade -yq

Steps to reproduce:
1. Wipe out everything vscode related but the vscode package itself. Upgrade system packages.
2. Login via Github, syncing everything, vscode host extensions included.
3. Open the project folder in question
4. Switch to "Log level: trace"
5. Rebuild and reopen in container
6. Observe no extensions from devcontainer.json are installed inside the devcontainer
7. Verify .Manifest was GET 200 succesfully from the CDN
8. Verify /home/ubuntu/.vscode-server/extensions contains only extensions.json (2 bytes long: "[]")
8. code --install-extension inside devcontainer - fails
7. Try installing vscode extension on the host via GUI, and then install it in the devcontainer via GUI - works just fine.

<I'll snip all irrelevant information from settings from the following...>

My settings.json on the host:
```
{
    "http.noProxy": [
        "localhost",
        "127.0.0.1",
        "192.168.0.0/24",
    ],
    "http.proxy": "socks5://localhost:9050",
    "http.proxySupport": "on"
}
```

My devcontainer.json:
```
{
    "name": "ndrdnn_cuda",

    "build": {
        "context": "..",
        "dockerfile": "../dockerfile",
        "target": "devcontainer"
    },

    "features": {
        "ghcr.io/devcontainers/features/docker-outside-of-docker:1": {
            "moby": true,
            "installDockerBuildx": true,
            "installDockerComposeSwitch": true,
            "version": "latest",
            "dockerDashComposeVersion": "v2"
        }
    },

    "customizations": {
        "vscode": {
            "extensions": [
                "ms-vscode.makefile-tools"
            ],
            "settings": {
                "http.proxy": "socks5://192.168.0.131:9050",
                "http.noProxy": [
                    "localhost",
                    "127.0.0.1",
                    "192.168.0.0/24",
                    "host.docker.internal"
                ],
                "http.proxySupport": "on",
                "http.useLocalProxyConfiguration": false
            }
        }
    },

    "remoteUser": "ubuntu",

    "containerEnv": {
        "LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}",
        // note, the following are for testing purposes - the issue persists with all of the following removed
        "http_proxy": "socks5://192.168.0.131:9050",
        "https_proxy": "socks5://192.168.0.131:9050",
        "all_proxy": "socks5://192.168.0.131:9050",
        "no_proxy": "localhost, 127.0.0.1, 192.168.0.0/24, host.docker.internal",
        "HTTP_PROXY": "socks5://192.168.0.131:9050",
        "HTTPS_PROXY": "socks5://192.168.0.131:9050",
        "ALL_PROXY": "socks5://192.168.0.131:9050",
        "NO_PROXY": "localhost, 127.0.0.1, 192.168.0.0/24, host.docker.internal"
    }
}
```

My dockerifle:
```
# syntax=docker/dockerfile:1.19-labs

ARG HUB=registry.hub.docker.com/
ARG OS_VERSION=24.04
ARG CUDA_VERSION=12.6.3
ARG CUDA_FLAVOR=-
# ARG CUDA_FLAVOR=-cudnn-

FROM ${HUB}nvidia/cuda:${CUDA_VERSION}${CUDA_FLAVOR}devel-ubuntu${OS_VERSION} AS dev
# <some apt installs here>

FROM dev AS devcontainer
# <some apt installs here>
# <some env here>
# note, nothing else present, like USER etc.
```

My complete devcontainers log: 
[devcontainers.log](https://github.com/user-attachments/files/24237299/devcontainers.log)

Some analysis for tracking down the issue [log vs source code link]:
```[13:09:45] Installing extensions...``` [extensionManagementCLI.ts](https://github.com/microsoft/vscode/blob/e3523eda7dbe2ca725a5ea1ea6ab96e0858e053a/src/vs/platform/extensionManagement/common/extensionManagementCLI.ts#L78)
```[13:09:46] #1: https://main.vscode-cdn.net/extensions/marketplace.json - end GET 200 {```
```[13:09:46] Completed initializing default profile extensions in extensions installation folder. file:///home/ubuntu/.vscode-server/extensions```
```[13:09:48] #2: https://marketplace.visualstudio.com/_apis/public/gallery/vscode/ms-azuretools/vscode-containers/latest - end GET 200 {```
```[13:09:48] #3: https://marketplace.visualstudio.com/_apis/public/gallery/vscode/ms-vscode/makefile-tools/latest - end GET 200 {``` [extensionManagementCLI.ts](https://github.com/microsoft/vscode/blob/e3523eda7dbe2ca725a5ea1ea6ab96e0858e053a/src/vs/platform/extensionManagement/common/extensionManagementCLI.ts#L198)
```[13:09:49] #6: https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/makefile-tools/0.12.17/1740509451080/Microsoft.VisualStudio.Code.Manifest - end GET 200 {``` [extensionManagementCLI.ts](https://github.com/microsoft/vscode/blob/e3523eda7dbe2ca725a5ea1ea6ab96e0858e053a/src/vs/platform/extensionManagement/common/extensionManagementCLI.ts#L207)
```[13:09:49] #5: https://ms-azuretools.gallerycdn.vsassets.io/extensions/ms-azuretools/vscode-containers/2.3.0/1762798402707/Microsoft.VisualStudio.Code.Manifest - end GET 200 {```

So assuming (according to logs) we successfully fetched the extension package and it's respective manifest from the marketplace/CDN, we at least reached the `GetManifest` call inside `installGalleryExtensions` function in the `src/vs/platform/extensionManagement/common/extensionManagementCLI.ts`.
Looking at the control flow of that function, there are not many branches where we silently bail out - so at least we either have to get an error in logs or some notice regarding extension download.
But we got none.
Aren't we hang on some asynchronous awaitable inside the call stack?

**Comment by DYefimov** [comment]
Just tried: 

1) Dev Containers 0.434.0 in VS Code 1.106.3 (bf9252a2fb45be6893dd8870c0bf37e2e1766d61) - same issue.
2) Dev Containers 0.434.0 in VS Code 1.107.1 (994fd12f8d3a5aa16f17d42c041e5809167e845a) - same issue.

So I'm not sure anymore at which point the issue with the proxy surfaced.

I noticed, that accidentally stripped the head of the 1.107.0 devcontainer log. Here are full ones for the last two attempts:
[devcontainers.1.106.3.log](https://github.com/user-attachments/files/24243018/devcontainers.1.106.3.log)
[devcontainers.1.107.1.log](https://github.com/user-attachments/files/24244383/devcontainers.1.107.1.log)

**Comment by DYefimov** [comment]
Some investigation later, the scenario is:
Due to the connection to the CDN with extensions being throttled (HTTP CONNECT is OK, but download speed is catastrophically throttled), vscode hangs inside the `GetManifest` call, that tries to get the manifest from the CDN.
There is no connection failure, and no "bail out on timeout" functionality inside the `GetManifest`, therefore we silently hang inside the call forever without any explicit error message.

Specifically, remote-ssh respects proxy, and downloads extensions just fine, but devcontainer (both locally and over remote-ssh) seems to ignore proxy settings, no matter how I supply them.

**Comment by nE0sIghT** [comment]
I confirm this issue. Please implement proxy support in the devcontainer

**Comment by nE0sIghT** [comment]
Setting

```

    "containerEnv": {
        "http_proxy": "...",
        "https_proxy": "..."
    },
```

in devcontainer.json works for me. However it would be nice to specify proxy for extensions installation process only

**Comment by DYefimov** [comment]
> in devcontainer.json works for me. However it would be nice to specify proxy for extensions installation process only

That's a global OS (container) scale level hack - not a solution, unfortunately.
Sometimes you can't afford routing all the traffic through proxy - what if you have a devcontainer as a part of your "docker swarm"?
That's just for the sake of example - there are many similar networking setups...

Yeah - that would be nice to fix only the part in question, and avoid re-engineering the networking architecture of your application due to the quirks with your tooling.

**Comment by nE0sIghT** [comment]
I updated vscode recently, cleaned docker cache and now proxy works for me for extension downloads in a devcontainer without extra configuration.

Looks like it was fixed?

**Comment by DYefimov** [comment]
> Looks like it was fixed?

Thanks! That's a miracle. Confirmed.

**Comment by nE0sIghT** [comment]
For some reason this is not works anymore.

**Comment by DYefimov** [comment]
Just rebuilt the container - works just fine with the proxy.
I didn't update to the latest version though.
```
$ sudo apt policy code
code:
  Installed: 1.108.2-1769004815
  Candidate: 1.109.0-1770171879
  Version table:
     1.109.0-1770171879 500
        500 https://packages.microsoft.com/repos/code stable/main amd64 Packages
 *** 1.108.2-1769004815 500
        500 https://packages.microsoft.com/repos/code stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
```
Version: 1.108.2
Commit: c9d77990917f3102ada88be140d28b038d1dd7c7
Date: 2026-01-21T13:52:09.270Z
Electron: 39.2.7
ElectronBuildId: 12953945
Chromium: 142.0.7444.235
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Linux x64 5.10.0-37-amd64
```

Confirmation, download still fails without proxy:
```
$ curl -L -o test.vsx https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-containers/0.434.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 2225k    0 15752    0     0    424      0  1:29:33  0:00:37  1:28:56     0
```

Confirmation, it's ok with proxy:
```
2026-02-09 12:05:42.801 [info] Installing extension 'ms-python.vscode-pylance'...
2026-02-09 12:05:42.814 [info] Installing extension 'ms-azuretools.vscode-containers'...
2026-02-09 12:05:42.820 [info] Getting Manifest... ms-python.vscode-pylance
2026-02-09 12:05:42.820 [info] Getting Manifest... ms-azuretools.vscode-containers
2026-02-09 12:05:43.338 [info] Installing extension: ms-python.vscode-pylance {"isMachineScoped":false,"installPreReleaseVersion":false,"isApplicationScoped":true,"isBuiltin":false,"installGivenVersion":false,"profileLocation":{"$mid":1,"fsPath":"/home/appuser/.vscode-server/extensions/extensions.json","external":"file:///home/appuser/.vscode-server/extensions/extensions.json","path":"/home/appuser/.vscode-server/extensions/extensions.json","scheme":"file"},"productVersion":{"version":"1.108.2","date":"2026-01-21T13:52:09.270Z"}}
2026-02-09 12:05:43.339 [info] Installing extension: ms-azuretools.vscode-containers {"isMachineScoped":false,"installPreReleaseVersion":false,"isApplicationScoped":true,"isBuiltin":false,"installGivenVersion":false,"profileLocation":{"$mid":1,"fsPath":"/home/appuser/.vscode-server/extensions/extensions.json","external":"file:///home/appuser/.vscode-server/extensions/extensions.json","path":"/home/appuser/.vscode-server/extensions/extensions.json","scheme":"file"},"productVersion":{"version":"1.108.2","date":"2026-01-21T13:52:09.270Z"}}
2026-02-09 12:05:50.696 [info] Extension signature verification result for ms-azuretools.vscode-containers: Success. Internal Code: 0. Executed: true. Duration: 5660ms.
2026-02-09 12:05:50.901 [info] Extracted extension to file:///home/appuser/.vscode-server/extensions/ms-azuretools.vscode-containers-2.4.1: ms-azuretools.vscode-containers
2026-02-09 12:05:50.924 [info] Renamed to /home/appuser/.vscode-server/extensions/ms-azuretools.vscode-containers-2.4.1
2026-02-09 12:05:51.105 [info] Extension signature verification result for ms-python.vscode-pylance: Success. Internal Code: 0. Executed: true. Duration: 1170ms.
2026-02-09 12:05:55.491 [info] Extracted extension to file:///home/appuser/.vscode-server/extensions/ms-python.vscode-pylance-2025.10.4: ms-python.vscode-pylance
2026-02-09 12:05:55.914 [info] Renamed to /home/appuser/.vscode-server/extensions/ms-python.vscode-pylance-2025.10.4
2026-02-09 12:05:55.953 [info] Extension installed successfully: ms-azuretools.vscode-containers file:///home/appuser/.vscode-server/extensions/extensions.json
2026-02-09 12:05:55.953 [info] Extension installed successfully: ms-python.vscode-pylance file:///home/appuser/.vscode-server/extensions/extensions.json
2026-02-09 12:05:55.956 [info] Extension 'ms-azuretools.vscode-containers' v2.4.1 was successfully installed.
2026-02-09 12:05:55.956 [info] Extension 'ms-python.vscode-pylance' v2025.10.4 was successfully installed.
```
```
