### ISSUE TITLE
git commands throw permission denied error in remote

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-release#1319]
- I have connected to VM Ubuntu 16 using SSH and opened VS Code window
- From the terminal I ran some git commands like

`git clone git@github.com:microsoft/vscode.git`

and it returns following error

```
Cloning into 'vscode'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Also other git commands like `git pull` does not work.

It works well from the terminal in VM.

**Comment by roblourens** [comment]
Are you trying to use agent forwarding, does your ssh config have `ForwardAgent yes`?

If so can you check `echo $SSH_AUTH_SOCK` from the terminal that works, and from the vscode terminal?

**Comment by sandy081** [comment]
> Are you trying to use agent forwarding, does your ssh config have ForwardAgent yes?

Yes. Enabled.


> echo $SSH_AUTH_SOCK from the terminal that works
/run/user/1001/keyring/ssh

> echo $SSH_AUTH_SOCK from the vscode terminal
Empty

> Or, did you deploy a key to the VM? If so is it in the ssh-agent, or is it in a standard location like ~/.ssh/id_rsa, etc?

I have key under `~/.ssh`

**Comment by roblourens** [comment]
Ok, but are you trying to use the key on the VM or a key in the forwarded agent?

If you are trying to use the forwarded agent then we are failing to set up SSH_AUTH_SOCK somehow, can you share the Remote-SSH log?

**Comment by sandy081** [comment]
Not sure what my remote SSH window is trying to use. I assume it is using the forward agent as when I ask for added ssh identities, it shows an empty list in terminal. Let me know how to confirm that. Here is ssh log

```
[10:29:46.408] remote-ssh-nightly@2019.8.42660
[10:29:46.408] darwin x64
[10:29:46.409] SSH Resolver called for "ssh-remote+ubuntu16", attempt 1
[10:29:46.409] SSH Resolver called for host: ubuntu16
[10:29:46.409] Setting up SSH remote "ubuntu16"
[10:29:46.420] Using commit id "5ab84ce18fe7dee304325952f2849264dd4a48c1" and quality "insider" for server
[10:29:46.423] Testing ssh with ssh -V
[10:29:46.439] ssh exited with code: 0
[10:29:46.439] Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
[10:29:46.440] Running script with connection command: ssh -D 64578 -o ConnectTimeout=15 ubuntu16 bash
[10:29:46.440] Install and start server if needed
[10:29:46.757] > Running remote connection script
[10:29:46.757] Got some output, clearing connection timeout
[10:29:46.759] > Acquiring lock on /home/sandy081/.vscode-server-insiders/bin/5ab84ce18fe7dee304325952f2849264dd4a48c1/vscode-remote-lock.5ab84ce18fe7dee304325952f2849264dd4a48c1
[10:29:46.766] > Found existing installation at /home/sandy081/.vscode-server-insiders/bin/5ab84ce18fe7dee304325952f2849264dd4a48c1...
[10:29:46.777] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
[10:29:46.777] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[10:29:46.787] > Checking server status on port 42689 with wget
[10:29:46.797] > 3dfd1ebf-3476-4c06-8a8a-899ced655c3c: start
> agentPort==42689==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
[10:29:46.797] > webUiAccessToken====
> 3dfd1ebf-3476-4c06-8a8a-899ced655c3c: end
[10:29:46.797] Received install output: 
agentPort==42689==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[10:29:46.798] Remote server is listening on port 42689
[10:29:46.798] Parsed server configuration: {"agentPort":42689,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":""}
[10:29:46.798] Starting forwarding server. localPort 64581 -> socksPort 64578 -> remotePort 42689
[10:29:46.798] Forwarding server listening on 64581
[10:29:46.799] Waiting for ssh tunnel to be ready
[10:29:46.799] Tunneled remote port 42689 to local port 64581
[10:29:46.799] Resolved "ssh-remote+ubuntu16" to "127.0.0.1:64581"
[10:29:46.799] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64"},"measures":{"resolveAttempts":1,"retries":1}}
[10:29:46.800] ------




[10:29:46.800] [Forwarding server 64581] Got connection 0
[10:29:46.805] [Forwarding server 64581] Got connection 1
[10:29:46.806] [Forwarding server 64581] Got connection 2
[10:29:47.015] [Forwarding server 64581] Got connection 3

```

**Comment by roblourens** [comment]
Did you set `remote.SSH.enableAgentForwarding` to false at some point? It should be enabled by default now but the log shows it disabled.

**Comment by roblourens** [comment]
Oh crap, this is due to the bug where the default value of a setting is not returned when accessed in a remote resolver. There is an issue for it but I can't find it... FYI @alexandrudima

**Comment by roblourens** [comment]
I fixed it, hopefully it works in the new update.

**Comment by sandy081** [comment]
Is the fix available in latest version of the extension?

**Comment by roblourens** [comment]
Yes

**Comment by sandy081** [comment]
I am still having the same issue

![image](https://user-images.githubusercontent.com/10746682/64232454-4534b380-cef2-11e9-88d6-cd3031b55a1d.png)


```
[06:58:12.631] remote-ssh-nightly@2019.9.3780
[06:58:12.631] darwin x64
[06:58:12.632] SSH Resolver called for "ssh-remote+ubuntu16", attempt 1
[06:58:12.632] SSH Resolver called for host: ubuntu16
[06:58:12.632] Setting up SSH remote "ubuntu16"
[06:58:12.643] Using commit id "3db7e09f3b61f915d03bbfa58e258d6eee843f35" and quality "insider" for server
[06:58:12.645] Testing ssh with ssh -V
[06:58:12.662] ssh exited with code: 0
[06:58:12.662] Got stderr from ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
[06:58:12.662] Running script with connection command: ssh -D 61814 -o ConnectTimeout=15 ubuntu16 bash
[06:58:12.663] Install and start server if needed
[06:58:13.020] > Running remote connection script
[06:58:13.020] Got some output, clearing connection timeout
[06:58:13.022] > Acquiring lock on /home/sandy081/.vscode-server-insiders/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/vscode-remote-lock.3db7e09f3b61f915d03bbfa58e258d6eee843f35
[06:58:13.030] > Found existing installation at /home/sandy081/.vscode-server-insiders/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35...
[06:58:13.042] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[06:58:13.054] > Checking server status on port 36877 with wget
[06:58:13.063] > d94f8fe3-cfb3-44cc-a81b-f98447118c5c: start
> sshAuthSock====
> agentPort==36877==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
[06:58:13.064] > d94f8fe3-cfb3-44cc-a81b-f98447118c5c: end
[06:58:13.064] Received install output: 
sshAuthSock====
agentPort==36877==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[06:58:13.064] Remote server is listening on port 36877
[06:58:13.064] Parsed server configuration: {"agentPort":36877,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":""}
[06:58:13.065] Starting forwarding server. localPort 61817 -> socksPort 61814 -> remotePort 36877
[06:58:13.065] Forwarding server listening on 61817
[06:58:13.066] Waiting for ssh tunnel to be ready
[06:58:13.066] Tunneled remote port 36877 to local port 61817
[06:58:13.066] Resolved "ssh-remote+ubuntu16" to "127.0.0.1:61817"
[06:58:13.067] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64"},"measures":{"resolveAttempts":1,"retries":1}}
[06:58:13.067] ------




[06:58:13.067] [Forwarding server 61817] Got connection 0
[06:58:13.071] [Forwarding server 61817] Got connection 1
[06:58:13.071] [Forwarding server 61817] Got connection 2

```

**Comment by roblourens** [comment]
Progress though.

`> sshAuthSock====`

now ssh is not forwarding the agent as if ForwardAgent is not being applied. Can you share your ssh config?

Another option is that the local end can't access the agent. For example if SSH_AUTH_SOCK is not defined in vscode's environment.

**Comment by chengxuhub** [comment]
> Oh crap, this is due to the bug where the default value of a setting is not returned when accessed in a remote resolver. There is an issue for it but I can't find it... FYI @alexandrudima

omg! When I upgrade to the latest version - 1.38.0,  this issue make me cant't using remote development.

**Comment by sandy081** [comment]
Fixed after setting `ForwardAgent Yes` in config.
