### ISSUE TITLE
SSH agent forwarding broken

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-remote-release#1396]
This worked before and seems broken now.

I have `ForwardAgent yes` and also `"remote.SSH.enableAgentForwarding": true`.

On the host:
```sh
$ ssh-add -l
Error connecting to agent: No such file or directory
$ echo $SSH_AUTH_SOCK
/tmp/ssh-OnHTgMlg8x/agent.8183
$ ls -al /tmp/ssh-OnHTgMlg8x/agent.8183
ls: cannot access '/tmp/ssh-OnHTgMlg8x/agent.8183': No such file or directory
$ echo $SSH_AUTH_SOCK_LOCATION

```

I restarted VS Code, opened new shells, but it doesn't help. `ssh-add -l` on the client system shows the correct key.

Remote - SSH: 0.46.0
VS Code: 1.38.0
Client OS: Windows 10

**Comment by roblourens** [comment]
Sorry for missing this issue. Still works for me. If this is still a problem could you share the log from the Remote-SSH output channel?

**Comment by letmaik** [comment]
```
[10:11:25.282] remote-ssh@0.46.1
[10:11:25.282] win32 x64
[10:11:25.282] SSH Resolver called for "ssh-remote+myvm", attempt 1
[10:11:25.282] SSH Resolver called for host: myvm
[10:11:25.282] Setting up SSH remote "myvm"
[10:11:25.298] Using commit id "b37e54c98e1a74ba89e03073e5a3761284e3ffb0" and quality "stable" for server
[10:11:25.300] Testing ssh with ssh -V
[10:11:25.417] ssh exited with code: 0
[10:11:25.417] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[10:11:25.418] Running script with connection command: ssh -D 50881 myvm bash
[10:11:25.420] Install and start server if needed
[10:11:25.479] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[10:11:25.480] Got some output, clearing connection timeout
[10:11:25.495] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[10:11:26.086] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
[10:11:26.640] > Running remote connection script
> 
[10:11:26.649] > Acquiring lock on /home/user/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3
> 761284e3ffb0/vscode-remote-lock.b37e54c98e1a74ba89e03073e5a3761284e3ffb0        
> Found existing installation at /home/user/.vscode-server/bin/b37e54c98e1a74b
> a89e03073e5a3761284e3ffb0...
> 
[10:11:26.658] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[10:11:26.668] > Checking server status on port 45487 with wget
> 
[10:11:26.677] > 11db48a9-2746-4fae-9ef9-417340591494: start  
> sshAuthSock==/tmp/ssh-q8CnSrE0Xv/agent.5500==
> agentPort==45487==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> 11db48a9-2746-4fae-9ef9-417340591494: end    
> 
[10:11:26.677] Received install output:   
sshAuthSock==/tmp/ssh-q8CnSrE0Xv/agent.5500==
agentPort==45487==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[10:11:26.678] Remote server is listening on port 45487
[10:11:26.678] Parsed server configuration: {"agentPort":45487,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":""}
[10:11:26.681] Starting forwarding server. localPort 50884 -> socksPort 50881 -> remotePort 45487
[10:11:26.682] Forwarding server listening on 50884
[10:11:26.682] Waiting for ssh tunnel to be ready
[10:11:26.684] [Forwarding server 50884] Got connection 0
[10:11:26.685] Tunneled remote port 45487 to local port 50884
[10:11:26.685] Resolved "ssh-remote+myvm" to "127.0.0.1:50884"
[10:11:26.686] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64"},"measures":{"resolveAttempts":1,"retries":1}}
[10:11:26.686] ------




[10:11:26.702] [Forwarding server 50884] Got connection 1
[10:11:26.703] [Forwarding server 50884] Got connection 2
[10:11:27.148] [Forwarding server 50884] Got connection 3
[10:11:27.151] [Forwarding server 50884] Got connection 4
[10:11:27.152] [Forwarding server 50884] Got connection 5
[10:11:27.154] [Forwarding server 50884] Got connection 6
[10:11:32.864] [Forwarding server 50884] Got connection 7
[10:11:32.866] [Forwarding server 50884] Got connection 8
[10:11:32.867] [Forwarding server 50884] Got connection 9
```

Shell output is still like in my original post.

**Comment by roblourens** [comment]
Looks like the extension is just failing to parse `sshAuthSock==/tmp/ssh-q8CnSrE0Xv/agent.5500==`, not sure why, but can you try with the nightly build of the extension? I fixed an issue related to parsing the server output on windows, although the log makes it look like you haven't actually hit that...

**Comment by letmaik** [comment]
It works in Insiders. However, when I now switch back to stable, then remote ssh is broken completely, so Insiders must have done something to the server.

Log from stable:
```
[07:16:43.951] remote-ssh@0.46.1
[07:16:43.951] win32 x64
[07:16:43.951] SSH Resolver called for "ssh-remote+myvm", attempt 1
[07:16:43.951] SSH Resolver called for host: myvm
[07:16:43.951] Setting up SSH remote "myvm"
[07:16:43.965] Using commit id "b37e54c98e1a74ba89e03073e5a3761284e3ffb0" and quality "stable" for server
[07:16:43.967] Testing ssh with ssh -V
[07:16:44.020] ssh exited with code: 0
[07:16:44.020] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[07:16:44.020] Running script with connection command: ssh -D 60466 myvm bash
[07:16:44.034] Install and start server if needed
[07:16:44.089] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[07:16:44.089] Got some output, clearing connection timeout
[07:16:44.099] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[07:16:44.370] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
[07:16:44.797] > Running remote connection script
> 
[07:16:44.805] > Acquiring lock on /home/user/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3
> 761284e3ffb0/vscode-remote-lock.b37e54c98e1a74ba89e03073e5a3761284e3ffb0        
> Found existing installation at /home/user/.vscode-server/bin/b37e54c98e1a74b
> a89e03073e5a3761284e3ffb0...
> 
[07:16:44.814] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[07:16:44.823] > Checking server status on port 45487 with wget
> 8b1d1443-0e32-4273-8c27-c1658d472ea5: start   
> sshAuthSock==/tmp/ssh-k1VSnUk3Gr/agent.9697== 
> agentPort==45487==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> 8b1d1443-0e32-4273-8c27-c1658d472ea5: end     
> 
[07:16:44.823] Received install output:    
sshAuthSock==/tmp/ssh-k1VSnUk3Gr/agent.9697== 
agentPort==45487==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[07:16:44.824] Failed to parse remote port from server output:    
sshAuthSock==/tmp/ssh-k1VSnUk3Gr/agent.9697== 
agentPort==45487==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[07:16:44.824] 
[07:16:44.824] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[07:16:44.824] ------




[07:16:53.075] ConfigFileWatcher: start watching file:///c%3A/Users/user/.ssh/config
[07:16:53.075] ConfigFileWatcher: adding save listener
[07:16:53.075] ConfigFileWatcher: adding close listener
```

Log from Insiders:
```
[07:22:14.598] remote-ssh@0.46.1
[07:22:14.598] win32 x64
[07:22:14.600] SSH Resolver called for "ssh-remote+myvm", attempt 1
[07:22:14.600] SSH Resolver called for host: myvm
[07:22:14.600] Setting up SSH remote "myvm"
[07:22:14.619] Using commit id "9f6a745027fc7b2a12495970f64625e24f410224" and quality "insider" for server
[07:22:14.621] Testing ssh with ssh -V
[07:22:14.704] ssh exited with code: 0
[07:22:14.704] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[07:22:14.705] Running script with connection command: ssh -D 60565 myvm bash
[07:22:14.707] Install and start server if needed
[07:22:14.787] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[07:22:14.787] Got some output, clearing connection timeout
[07:22:14.820] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[07:22:15.093] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
[07:22:15.522] > Running remote connection script
> 
[07:22:15.531] > Acquiring lock on /home/user/.vscode-server-insiders/bin/9f6a745027fc7b2a124
> 95970f64625e24f410224/vscode-remote-lock.9f6a745027fc7b2a12495970f64625e24f41022
> 4
> Found existing installation at /home/user/.vscode-server-insiders/bin/9f6a74
> 5027fc7b2a12495970f64625e24f410224...
> 
[07:22:15.536] > SSH_CONNECTION=167.220.197.34 45794 10.1.0.5 22
> LANG=C.UTF-8
> SSH_AUTH_SOCK=/tmp/ssh-3kpDaUQx3o/agent.11036
> XDG_SESSION_ID=38614
> USER=user
> PWD=/home/user
> HOME=/home/user
> SSH_CLIENT=167.220.197.34 45794 22
> MAIL=/var/mail/user
> SHELL=/bin/bash
> SHLVL=2
> VSCODE_AGENT_FOLDER=/home/user/.vscode-server-insiders
> LOGNAME=user
> XDG_RUNTIME_DIR=/run/user/1010
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
> r/local/games
[07:22:15.537] > 
> _=/usr/bin/printenv
[07:22:15.541] > 
> Starting server...
[07:22:15.544] > 
> 
[07:22:15.545] > Waiting for server log...
[07:22:15.553] > 
> 
[07:22:16.043] > 
> *
[07:22:16.044] > 
> * Reminder: You may only use this software with Visual Studio family products,  
[07:22:16.045] > 
> 
[07:22:16.045] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[07:22:16.046] > 
> *
[07:22:16.047] > 
> 
[07:22:16.052] > 
> 9cd86eb8-be12-42d4-a2d0-56caa2120103: start
[07:22:16.053] > 
> sshAuthSock==/tmp/ssh-3kpDaUQx3o/agent.11036==
[07:22:16.053] > 
> agentPort==36823==
[07:22:16.055] > 
> 
[07:22:16.055] > webViewServerPort====
[07:22:16.057] > 
> osReleaseId==ubuntu==
[07:22:16.057] > 
> arch==x86_64==
[07:22:16.057] > 
> webUiAccessToken====
[07:22:16.060] > 
> 9cd86eb8-be12-42d4-a2d0-56caa2120103: end
[07:22:16.060] Received install output: 
sshAuthSock==/tmp/ssh-3kpDaUQx3o/agent.11036==
agentPort==36823==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[07:22:16.061] Remote server is listening on port 36823
[07:22:16.061] Parsed server configuration: {"agentPort":36823,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-3kpDaUQx3o/agent.11036"}
[07:22:16.064] Starting forwarding server. localPort 60568 -> socksPort 60565 -> remotePort 36823
[07:22:16.066] Forwarding server listening on 60568
[07:22:16.067] Waiting for ssh tunnel to be ready
[07:22:16.069] [Forwarding server 60568] Got connection 0
[07:22:16.070] Tunneled remote port 36823 to local port 60568
[07:22:16.071] Resolved "ssh-remote+myvm" to "127.0.0.1:60568"
[07:22:16.071] Remote extension host environment: {"SSH_AUTH_SOCK":"/tmp/ssh-3kpDaUQx3o/agent.11036","SSH_AUTH_SOCK_LOCATION":"/tmp/vscode-ssh-auth-sock-location-141316150"}
[07:22:16.071] Writing new SSH_AUTH_SOCK to /tmp/vscode-ssh-auth-sock-location-141316150
[07:22:16.075] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64"},"measures":{"resolveAttempts":1,"retries":1}}
[07:22:16.075] ------




[07:22:16.078] > 
> 
[07:22:16.184] [Forwarding server 60568] Got connection 1
[07:22:16.186] [Forwarding server 60568] Got connection 2
[07:22:16.787] Finished writing SSH_AUTH_SOCK_LOCATION
```

**Comment by roblourens** [comment]
It looks like it is having sort of the same issue, just worse. I think this is an issue with parsing the output that I already fixed. I meant the nightly version of the extension, not vscode insiders: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by letmaik** [comment]
No luck, using VS Code Insiders and SSH nightly:

```sh
$ ssh-add -l
Error connecting to agent: No such file or directory
$ echo $SSH_AUTH_SOCK
/tmp/vscode-ssh-auth-sock-213622416
$ ls -al /tmp/vscode-ssh-auth-sock-213622416
ls: cannot access '/tmp/vscode-ssh-auth-sock-213622416': No such file or directory
$ls -al /tmp/ssh-HJjaOpSks2/agent.167984
srwxrwxr-x 1 user user 0 Sep 24 16:50 /tmp/ssh-HJjaOpSks2/agent.167984
```
Note the last line! Compare with log:

```
[16:50:38.161] remote-ssh-nightly@2019.9.34020
[16:50:38.161] win32 x64
[16:50:38.161] SSH Resolver called for "ssh-remote+myvm", attempt 1
[16:50:38.161] SSH Resolver called for host: myvm
[16:50:38.161] Setting up SSH remote "myvm"
[16:50:38.204] Using commit id "9f6a745027fc7b2a12495970f64625e24f410224" and quality "insider" for server
[16:50:38.206] Testing ssh with ssh -V
[16:50:38.257] ssh exited with code: 0
[16:50:38.258] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[16:50:38.258] Running script with connection command: ssh -T -D 63857 myvm bash
[16:50:38.260] Install and start server if needed
[16:50:38.317] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[16:50:38.317] Got some output, clearing connection timeout
[16:50:38.328] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:50:38.626] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
[16:50:39.080] > 64c987d9f680: running
> 
[16:50:39.098] > Acquiring lock on /home/user/.vscode-server-insiders/bin/9f6a745027fc7b2a124
> 95970f64625e24f410224/vscode-remote-lock.9f6a745027fc7b2a12495970f64625e24f41022
> 4
> 
[16:50:39.107] > Found existing installation at /home/user/.vscode-server-insiders/bin/9f6a74
> 5027fc7b2a12495970f64625e24f410224...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> 
[16:50:39.116] > Checking server status on port 36823 with wget
> 
[16:50:39.117] > 64c987d9f680: start
> sshAuthSock==/tmp/ssh-HJjaOpSks2/agent.167984==
> agentPort==36823==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> 64c987d9f680: end
[16:50:39.117] Received install output: 
sshAuthSock==/tmp/ssh-HJjaOpSks2/agent.167984==
agentPort==36823==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[16:50:39.118] Remote server is listening on port 36823
[16:50:39.118] Parsed server configuration: {"agentPort":36823,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-HJjaOpSks2/agent.167984"}
[16:50:39.122] Starting forwarding server. localPort 63860 -> socksPort 63857 -> remotePort 36823
[16:50:39.124] Forwarding server listening on 63860
[16:50:39.125] Waiting for ssh tunnel to be ready
[16:50:39.127] Tunneled remote port 36823 to local port 63860
[16:50:39.127] Resolved "ssh-remote+myvm" to "127.0.0.1:63860"
[16:50:39.128] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-HJjaOpSks2/agent.167984" "/tmp/vscode-ssh-auth-sock-213622416"
[16:50:39.128] Using cwd: vscode-remote://ssh-remote%2Bmyvm/
[16:50:39.128] Remote extension host environment: {"SSH_AUTH_SOCK":"/tmp/vscode-ssh-auth-sock-213622416"}
[16:50:39.129] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0"},"measures":{"resolveAttempts":1,"retries":1}}
[16:50:39.129] ------




[16:50:39.130] > 
> 
[16:50:39.130] [Forwarding server 63860] Got connection 0
[16:50:39.142] [Forwarding server 63860] Got connection 1
[16:50:39.143] [Forwarding server 63860] Got connection 2
[16:50:39.440] [Forwarding server 63860] Got connection 3
[16:50:39.915] "Update SSH_AUTH_SOCK" terminal command done
```

For some reason the symlink didn't get created. When I run `ln -f -s "/tmp/ssh-HJjaOpSks2/agent.167984" "/tmp/vscode-ssh-auth-sock-213622416"` manually, then `ssh-add -l` works as expected.

**Comment by roblourens** [comment]
Interesting. If `ln` had produced any output, it would have been logged. And if you reload the window a couple times, it's the same result every time?

**Comment by paidhi** [comment]
Could this issue be reopened?

I can confirm that the problem still exists. Even with a current version of Visual Studio Code Insiders and "SSH - Remote (Nightly)".

Tested with the following:

Visual Studio Code 
```
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299
```
Tested stable and nightly version of the SSH extension (Remote - SSH 0.47.2, Remote - SSH (Nightly) 2019.10.42662).


Visual Studio Code Insiders
```
Version: 1.41.0-insider (user setup)
Commit: fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347
Date: 2019-11-08T05:28:30.394Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299
```
SSH extension: Remote - SSH (Nightly)  2019.10.42662

I have also noticed a lot of files not being cleaned up in /tmp:
```
> ls -l /tmp/vscode*
srwxrwxr-x 1 banfim banfim  0 Nov  8 15:00 /tmp/vscode-ipc-17f87a77-5090-4f69-8d4a-c58b7674f3a5.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 15:03 /tmp/vscode-ipc-2151acc5-bd3b-4c5c-b975-32aa79397732.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 14:29 /tmp/vscode-ipc-48989a25-552c-430a-b6fd-acb3e2600c14.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 14:26 /tmp/vscode-ipc-4d09b169-845d-4cef-9c36-6f6e4d23c665.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 14:30 /tmp/vscode-ipc-52307b96-e477-4609-9aef-b89b609b1d58.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 15:05 /tmp/vscode-ipc-b8a557b6-59f5-4ec6-b324-a85dd98b45c1.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 15:02 /tmp/vscode-ipc-c8ad7e45-823e-4bd7-8c86-4023b66a72ac.sock
srwxrwxr-x 1 banfim banfim  0 Nov  8 15:06 /tmp/vscode-ipc-f94314f5-5dc9-4e0a-87c1-aa869bdd2008.sock
lrwxrwxrwx 1 banfim banfim 30 Nov  8 15:00 /tmp/vscode-ssh-auth-sock-117798753 -> /tmp/ssh-urY3VOj9dO/agent.8194
lrwxrwxrwx 1 banfim banfim 30 Nov  8 15:02 /tmp/vscode-ssh-auth-sock-317316993 -> /tmp/ssh-hRvRP24gJr/agent.8758
lrwxrwxrwx 1 banfim banfim 30 Nov  8 14:26 /tmp/vscode-ssh-auth-sock-331258891 -> /tmp/ssh-6kxhpJXqf0/agent.5652
lrwxrwxrwx 1 banfim banfim 30 Nov  8 14:29 /tmp/vscode-ssh-auth-sock-370874681 -> /tmp/ssh-t9C3Coz9K2/agent.6577
lrwxrwxrwx 1 banfim banfim 30 Nov  8 14:30 /tmp/vscode-ssh-auth-sock-391070964 -> /tmp/ssh-LBe0ep1fIQ/agent.7322
lrwxrwxrwx 1 banfim banfim 31 Nov  8 15:05 /tmp/vscode-ssh-auth-sock-616537288 -> /tmp/ssh-USh9HwlXKy/agent.10282
lrwxrwxrwx 1 banfim banfim 30 Nov  8 15:03 /tmp/vscode-ssh-auth-sock-706678449 -> /tmp/ssh-70DQJP6KOv/agent.9383
lrwxrwxrwx 1 banfim banfim 31 Nov  8 15:06 /tmp/vscode-ssh-auth-sock-94290854 -> /tmp/ssh-vZs51Afy2v/agent.11056

```

**Comment by roblourens** [comment]
@paidhi please open a new issue since this one is stale and include the log from the Remote - SSH output channel
