### ISSUE TITLE
VSC remote leaves behind old server versions and extensions data at each VSC update

### ISSUE THREAD

**Issue by lupalby** [microsoft/vscode-remote-release#2852]
- VSCode Version: 1.44.2
- Local OS Version: Windows 10 Enterprise 1909
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Use VS Code remote in WSL for some time
2. Update to a new version of VS Code
3. The remote server will be downloaded again in WSL and extensions like C++ will create a new intellisense database, etc
4. The more updates of VS Code, the more copies accumulate

Duplication can easily be seen in `.vscode-server/bin`, `.vscode-server/data/User/workspaceStorage`, and `.cache/vscode-cpptools/ipch`. I now can see 8 different versions and my `.vscode-server` is well over 1GB now because of this and `.cache/vscode-cpptools` is over 3GB.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Sorry if this is a duplicate or it's missing some information. I tried to search in the issues but I couldn't find anything related. I'll be happy to provide any more information needed.

Thanks for the great work, I love this feature, I do most of my development with this!

**Comment by lupalby** [comment]
Based on [this comment](https://github.com/microsoft/vscode-remote-release/issues/969#issuecomment-511148723) from @roblourens only the latest 5 copies of the remote server should be saved, but I see 8 now in just a few months that I've been using it

**Comment by roblourens** [comment]
That's right, but you see more than 5 copies under `bin/`?

**Comment by lupalby** [comment]
Today VSC updated to 1.45.0 so when I connected to WSL it downloaded a new version of the remote server. I now see 9 folders under `bin/`.
Which log are you interested in? This is the content of `remoteagent.log`:
```
[2020-05-09 16:32:43.128] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2020-05-09 16:32:43.128] [remoteagent] [info] Extension host agent started.
[2020-05-09 16:32:43.219] [remoteagent] [info] [::ffff:127.0.0.1][930da044][ManagementConnection] New connection established.
[2020-05-09 16:32:43.221] [remoteagent] [info] [::ffff:127.0.0.1][5191065c][ExtensionHostConnection] New connection established.
[2020-05-09 16:32:43.713] [remoteagent] [info] Deleted from disk ms-vscode.cpptools /home/my-user/.vscode-server/extensions/ms-vscode.cpptools-0.27.1
[2020-05-09 16:32:44.336] [remoteagent] [info] [::ffff:127.0.0.1][5191065c][ExtensionHostConnection] <80> Launched Extension Host Process.
[2020-05-09 16:32:45.238] [remoteagent] [info] Installing extension: ms-vsliveshare.vsliveshare
[2020-05-09 16:32:45.239] [remoteagent] [info] Installing extension: visualstudioexptteam.vscodeintellicode
[2020-05-09 16:32:52.968] [remoteagent] [info] Downloaded extension: ms-vsliveshare.vsliveshare /tmp/c655573d-182d-4c2b-9355-2a8cda74b0fb
[2020-05-09 16:32:53.491] [remoteagent] [info] Downloaded extension: visualstudioexptteam.vscodeintellicode /tmp/a92d6ff6-f086-4085-b131-81e169dbda79
[2020-05-09 16:32:54.227] [remoteagent] [info] Extracted extension to /home/my-user/.vscode-server/extensions/.visualstudioexptteam.vscodeintellicode-1.2.7: visualstudioexptteam.vscodeintellicode
[2020-05-09 16:32:54.268] [remoteagent] [info] Renamed to /home/my-user/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.2.7
[2020-05-09 16:32:54.280] [remoteagent] [info] Installation completed. visualstudioexptteam.vscodeintellicode
[2020-05-09 16:32:54.298] [remoteagent] [info] Extensions installed successfully: visualstudioexptteam.vscodeintellicode
[2020-05-09 16:32:54.624] [remoteagent] [info] Extracted extension to /home/my-user/.vscode-server/extensions/.ms-vsliveshare.vsliveshare-1.0.2106: ms-vsliveshare.vsliveshare
[2020-05-09 16:32:54.659] [remoteagent] [info] Renamed to /home/my-user/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.2106
[2020-05-09 16:32:54.669] [remoteagent] [info] Installation completed. ms-vsliveshare.vsliveshare
[2020-05-09 16:32:54.683] [remoteagent] [info] Extensions installed successfully: ms-vsliveshare.vsliveshare
```

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by lupalby** [comment]
I am not using remote SSH, but remote WSL. These are all the options I have:
![image](https://user-images.githubusercontent.com/34496994/81489454-617bb380-922a-11ea-86bd-575e9b2d5896.png)
The log I posted above is from "Log (Remote Server)"

**Comment by lupalby** [comment]
If I launch the command `Remote-WSL: show log` I get this:
```
[2020-05-12 04:21:31.747] Resolving wsl+ubuntu, resolveAttempt: 1
[2020-05-12 04:21:31.946] Starting VS Code Server inside WSL (Ubuntu)
[2020-05-12 04:21:31.946] Extension version: 0.44.2, Windows build: 18363. Multi distro support: available. WSL path support: enabled
[2020-05-12 04:21:32.264] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-05-12 04:21:33.149] Probing result: found
[2020-05-12 04:21:33.149] Server install found in WSL
[2020-05-12 04:21:33.150] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" d69a79b73808559a91206d73d7717ff5f798f23c stable .vscode-server 0  --disable-telemetry' in c:\Users\WinUser\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.2}
[2020-05-12 04:21:33.762] Setting up server environment: Looking for /home/my-user/.vscode-server/server-env-setup. Not found.
[2020-05-12 04:21:33.762] WSL version: 4.4.0-18362-Microsoft Ubuntu
[2020-05-12 04:21:33.762] Starting server: /home/my-user/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/server.sh  --port=0 --use-host-proxy --fileWatcherPolling=0 --disable-telemetry
[2020-05-12 04:21:36.770] 
[2020-05-12 04:21:36.770] 
[2020-05-12 04:21:36.770] *
[2020-05-12 04:21:36.770] * Visual Studio Code Server
[2020-05-12 04:21:36.770] *
[2020-05-12 04:21:36.770] * Reminder: You may only use this software with Visual Studio family products,
[2020-05-12 04:21:36.770] * as described in the license https://aka.ms/vscode-remote/license
[2020-05-12 04:21:36.770] *
[2020-05-12 04:21:36.770] 
[2020-05-12 04:21:36.770] 
[2020-05-12 04:21:37.070] IP Address: 172.17.25.113
[2020-05-12 04:21:37.070] IP Address: 192.168.1.133
[2020-05-12 04:21:37.070] Extension host agent listening on 63648
[2020-05-12 04:21:37.070] 
[2020-05-12 04:21:37.070] 
[2020-05-12 04:21:37.070] [21:21:36] Extension host agent started.
[2020-05-12 04:21:37.071] WSL resolver response: 127.0.0.1:63648
[2020-05-12 04:21:37.071] To debug connection issues, open a local browser on http://127.0.0.1:63648/version
```

**Comment by roblourens** [comment]
Sorry, I misread the issue and didn't realize you were using WSL and not SSH.

**Comment by lupalby** [comment]
No worries, let me know if you need any more information from my end.

**Comment by EFCHolla** [comment]
Hi, @roblourens I'm using Remote-SSH to connect to my server running Ubuntu 18.04 from my Windows 10 workstation, after about a month there has already been 3 copy of vscode-server version with some kind of IDs I know no meaning of in ~/.vscode-server/bin and other places, I'm wondering if there is any command or script I can use to clean up old version binaries and extensions since it is gobbling up my SSD space real fast.
My remote machine is my sole training resource for my ML projects, much appreciated if you can give me some help or hints!

**Comment by lupalby** [comment]
@aeschli do you have any update on this? Since new versions of VSC keep coming out, my folders keep growing, I am now at 11.
Let me know if I can help in any way.
Thanks!

**Comment by lupalby** [comment]
Why was this closed? It has been confirmed to be not performing as it is supposed to do, therefore making it a bug. I provided all the information I was asked and made myself available for any further assistance.
If I made any mistake in reporting the problem, or went against any guideline, I apologize for that, please give me a chance to fix that by giving me a feedback.

**Comment by aeschli** [comment]
I pushed a fix. Please try VSCode - Remote V0.44.3.

**Comment by lupalby** [comment]
Thanks for the info, just got the updated extension today. Is it supposed to check and clean up at every start of VSC, or only when VSC updates? I tried to open and close the app several times, leaving plenty time for all the extensions to load, but I still see 11 folders under `.vscode-server\bin`
I am running Remote - WSL 0.44.3 on VSC 1.46.0

**Comment by aeschli** [comment]
Thanks a lot for having an eye on this.
The removing of the old version happens when a new version of the server is downloaded and installed. 1.46.1 is coming soon, so if you can check again after it is installed that would be great.

**Comment by lupalby** [comment]
Just received the 1.46.1 update and I can confirm that now there is only one copy of the server left. Thanks for the fix!

**Comment by aeschli** [comment]
Thanks @lupalby for verifying this!
