### ISSUE TITLE
Could not fetch remote environment / Connection error: Unauthorized client refused

### ISSUE THREAD

**Issue by stygarfield** [microsoft/vscode-remote-release#4087]
Apologies if this is an easy fix, or a silly question. I'm pretty new, and don't understand much.

I used to be able to us vscode to remote to some Raspberry Pis (running Rasbian) - but recently it has stopped working. I can SSH to them just fine - and if I delete the .vscode-remote-insiders directory, vscode will re-install it. Afterwards, it gives me two error messages

'Could not fetch remote environment'
and
'Failed to connect to the remote extension host server (Error: Connection errorL Unauthorized client refused.)'

I checked the log, and this is the output

```
[21:58:01.997] Log Level: 2
[21:58:01.999] remote-ssh-nightly@2020.11.38340
[21:58:02.000] win32 x64
[21:58:02.001] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223139322e3136382e302e323134222c2275736572223a227069227d", attempt 1
[21:58:02.001] "remote.SSH.useLocalServer": false
[21:58:02.002] "remote.SSH.showLoginTerminal": false
[21:58:02.002] "remote.SSH.remotePlatform": {"192.168.0.254":"linux","192.168.0.214":"linux","192.168.0.253":"linux","192.168.0.125":"linux"}
[21:58:02.002] "remote.SSH.sshPath": undefined
[21:58:02.002] "remote.SSH.sshConfigurationFile": undefined
[21:58:02.002] "remote.SSH.useFlock": true
[21:58:02.002] "remote.SSH.lockfilesInTmp": false
[21:58:02.002] "remote.SSH.localServerDownload": auto
[21:58:02.003] "remote.SSH.remoteServerListenOnSocket": false
[21:58:02.003] "remote.SSH.showLoginTerminal": false
[21:58:02.003] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[21:58:02.003] SSH Resolver called for host: pi@192.168.0.214
[21:58:02.003] Setting up SSH remote "192.168.0.214"
[21:58:02.025] Using commit id "0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d" and quality "insider" for server
[21:58:02.028] Install and start server if needed
[21:58:02.047] Checking ssh with "ssh -V"
[21:58:02.089] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[21:58:02.093] Running script with connection command: ssh -T -D 60572 pi@192.168.0.214 bash
[21:58:02.096] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:58:02.788] > 65a98d5548c0: running
> ]0;C:\WINDOWS\System32\cmd.exe
[21:58:02.789] Got some output, clearing connection timeout
[21:58:02.913] > Acquiring lock on /home/pi/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8a
> c1a84949a83f35d/vscode-remote-lock.pi.0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d  
[21:58:02.949] > Found existing installation at /home/pi/.vscode-server-insiders/bin/0a80aacc7be1
> ab03ec0f94b8ac1a84949a83f35d...
[21:58:02.964] > Checking /home/pi/.vscode-server-insiders/.0a80aacc7be1ab03ec0f94b8ac1a84949a83f
> 35d.log and /home/pi/.vscode-server-insiders/.0a80aacc7be1ab03ec0f94b8ac1a84949a
> 83f35d.pid for a running server
> Looking for server with pid: 9617
[21:58:02.987] > Found running server...
[21:58:02.997] > 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[21:58:03.027] > Checking server status on port 37743 with wget
[21:58:03.045] > 65a98d5548c0: start     
> sshAuthSock====
> webUiAccessToken====    
> listeningOn==37743==    
> osReleaseId==raspbian== 
> arch==armv7l==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 65a98d5548c0: end
[21:58:03.045] Received install output:      
sshAuthSock====
webUiAccessToken====    
listeningOn==37743==    
osReleaseId==raspbian== 
arch==armv7l==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[21:58:03.046] Remote server is listening on 37743
[21:58:03.046] Parsed server configuration: {"remoteListeningOn":{"port":37743},"osReleaseId":"raspbian","arch":"armv7l","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000","platform":"linux"}
[21:58:03.047] Starting forwarding server. localPort 60575 -> socksPort 60572 -> remotePort 37743
[21:58:03.048] Forwarding server listening on 60575
[21:58:03.048] Waiting for ssh tunnel to be ready
[21:58:03.049] Tunneled 37743 to local port 60575
[21:58:03.050] Resolved "ssh-remote+7b22686f73744e616d65223a223139322e3136382e302e323134222c2275736572223a227069227d" to "127.0.0.1:60575"
[21:58:03.051] [Forwarding server 60575] Got connection 0
[21:58:03.063] ------




[21:58:03.117] > 
[21:58:03.125] [Forwarding server 60575] Got connection 1
[21:58:03.126] [Forwarding server 60575] Got connection 2
[21:58:04.598] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[21:58:04.604] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

I don't know what changed to break it - but I can not connect to any of my raspberry pis anymore.

**Comment by mfocko** [comment]
same here, no problem with the git though... log ends iwth `Got connection 2`

**Comment by markrosoftuk** [comment]
Same here using insiders and exploration. Works ok on stable release though.

**Comment by lukstep** [comment]
Same here.  Remote - SSH logs ends with `Got connection 2` and popped up an error:
`Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)`

**Comment by khadija-cloud** [comment]
Same here

**Comment by arsdragonfly** [comment]
same here

**Comment by stygarfield** [comment]
I only seem to get the git.exe error when I'm trying to connect after the vscode remote server is installed - otherwise it fails at 'Got connection 2' as others have noted above.

Anyone have any ideas?

**Comment by lukstep** [comment]
I've switched from VSC insiders to stable version and it work.

**Comment by Hotbrains** [comment]
Same here!

**Comment by YaarPodshipnik** [comment]
Same here

**Comment by kianryan** [comment]
Adding another vote.
rm -rf .vscode-server-insiders/
does not resolve the problem here.

**Comment by roblourens** [comment]
Is everyone using Insiders? Does it work in stable VS Code?

Also can you check for errors in the devtools console (Help > Toggle Developer Tools)

**Comment by roblourens** [comment]
Maybe this corresponds to the Electron update? And https://github.com/microsoft/vscode-remote-release/issues/2998#issuecomment-735738520 sounds relevant, this should be reverted soon @deepak1556

**Comment by stygarfield** [comment]
I'm using insiders, when I toggle developer tools, these are the errors that are showing

![errors](https://user-images.githubusercontent.com/17439958/100698548-97f75800-334d-11eb-9745-bca801fd75a3.png)
![errors2](https://user-images.githubusercontent.com/17439958/100698638-c9702380-334d-11eb-9d13-e771b16b2d53.png)
![errors3](https://user-images.githubusercontent.com/17439958/100698680-e3aa0180-334d-11eb-869f-95bbf6b06ee3.png)

**Comment by deepak1556** [comment]
@roblourens I am not sure what the issue is from the logs, can you help with narrowing down the root cause.

**Comment by khadija-cloud** [comment]
Finally, Issue fixed by vscode update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deepak1556** [comment]
@khadija-cloud which version fixed the issue ?

**Comment by khadija-cloud** [comment]
For me the last version and update remote ssh extansion

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YaarPodshipnik** [comment]
I've updated the vscode to config listed below, but I'm still seeing the problem:
```
Version: 1.52.0-insider (user setup)
Commit: ac165d7f....
Electron: 11.0.2
Chrome: 87.9.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.17763
```
Remote Development pack I have installed is 0.20.0, Remote - SSH is 0.56.0. I do not have an option to install another version or to upgrade those extenstions.

**Comment by gajama** [comment]
For past few days I have what seems to be the same issue connecting from my Mac to a CentOS server. I can connect from my Mac to other computers via SSH and from my Linux box to the CentOS server but on Mac (recently updated to BigSur) I get the same error messages as above. Running insiders latest and Remote - SSH nightly. Works fine using stable.

This does look like https://github.com/microsoft/vscode-remote-release/issues/2998 as glibc only goes up to version 3.4.19 on the server.

**Comment by markrosoftuk** [comment]
Works on insiders latest release (just now!). Not working in exploration yet, hoping for an update for that too as it is so much faster to use on M1 mac than insiders or stable.

**Comment by YaarPodshipnik** [comment]
Commit bf213952, from 2020-12-01T09:19:32.000Z did fix this for me as well! Seems this rolled back Electron, Chrome, Node.js and V8 versions

**Comment by gajama** [comment]
Yes, latest update fixed it for me as well.

**Comment by stygarfield** [comment]
Same here! It is working again! It must have been whatever update happened in the last 12 or so hours.

Thank you so much @roblourens and @deepak1556 !!

**Comment by lukstep** [comment]
Same here, version bellow working already.
 
Version: 1.52.0-insider (user setup)
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:19:32.000Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by deepak1556** [comment]
Since this issue will come back once push the electron update next month, to debug further, I would like to know the linux distro everyone here tried to connect to. Can you share the logs from the failure ?

We did update the build image to Ubuntu bionic for x64 target which definitely bumps the glibc requirement for some our native modules.

**Comment by deepak1556** [comment]
Actually what I want to know specifically is the linux distro and version, so you can just paste that info instead of the entire log.

**Comment by emmertex** [comment]
As requested details of server I cannot connect to
`Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Linux ursa-minor 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:08:09 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by markrosoftuk** [comment]
CentOS 7.9 here.

**Comment by Chenghao-Wu** [comment]
Mac OS big sur with M1 cpu can not connect (exploration version) the remote server with error information: 
1. Could not fetch remote environment
2. Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)

Version: 1.52.0-exploration
Commit: 85eed6d6df7551ab9de7427fb291e1fca645d020
Date: 2020-12-01T22:59:49.347Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0

**Comment by stygarfield** [comment]
Running Linux PiGarage 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 according to `uname -a`

**Comment by sonneveld** [comment]
I can confirm I saw this issue with Centos 7 (but my current vscode insiders version seems to have righted itself.) from a Windows Server 2016 machine.

Log (.ac165d7f974d70212be80cb15eaecfc1fd20b21a.log) : [vscode-remote-log.txt](https://github.com/microsoft/vscode-remote-release/files/5633464/vscode-remote-log.txt)

**Comment by deepak1556** [comment]
I have updated the build pipeline used for Electron 11 to have older gcc toolchain (specifically gcc-5) should maintain support to distros as current insiders does. However I would like to confirm this with some early testers using any of the following builds, so that we don't break anything next week when Electron 11 gets pushed to insiders.

[Tar archive](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/code-exploration-x64-1607056310.tar.gz)
[Snap package](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/code-exploration-x64-1607056737.snap)
[Deb package](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/code-exploration_1.52.0-1607056005_amd64.deb)
[Rpm package](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/code-exploration-1.52.0-1607056089.el7.x86_64.rpm)

Thanks for testing!

**Comment by darrenkenny** [comment]
@deepak1556 - I tried to run the Tar build above on OL7, it ran, but I couldn't load the Remote SSH extension to try connect to anything. 

The extension was installed, but no matter what I could not get it to prompt me after selecting to connect to a remote host, or even editing the remote-ssh  configuration menu option - neither worked.

I tried to enable debug logging, but it didn't seem to output anything in any of the log locations, but maybe I'm doing that wrong, will try again later. 

But as I mentioned too on the other issue (#4103 ), I usually use a MacOS client to a remote host which is where it's broken for me.

**Comment by gajama** [comment]
NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by Chenghao-Wu** [comment]
I tested the builds you provide on MacOS arm64 and trying to connect a cent os remote server. It has the same problem. 
1. Could not fetch remote environment
2. Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)
I would guess the remote server or local server can not download the exploration vscode codes?

Thanks for your help and time.

**Comment by deepak1556** [comment]
what is the value of `strings <path-to>/libstdc++.so | grep GLIBCXX_3.4.2` on your cent os ?

Can you also find `spdlog.node` under `~/.vscode-server-exploration` and try the following `strings <path-to>/spdlog.node | grep GLIBCXX`

**Comment by Chenghao-Wu** [comment]
- First I tried: strings /usr/lib/libstdc++.so.6 | grep GLIBCXX
`GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
GA+GLIBCXX_ASSERTIONS
GA+GLIBCXX_ASSERTIONS`

2. second I tried to find the spdlog.node: 
bruce@x1075 .vscode-exploration % ls
argv.json	extensions
It seems there is no this file.

3. I dont have spdlog.node, so I did not continue.

Thank you for your time!

**Comment by deepak1556** [comment]
> First I tried: strings /usr/lib/libstdc++.so.6 | grep GLIBCXX

Thats a good enough matrix for our modules to run.

Can you paste the full log of the failing remote connection.

**Comment by Chenghao-Wu** [comment]
The following messages are what I got from vscode exploration version

[18:46:39.888] Log Level: 2
[18:46:39.889] remote-ssh@0.58.0
[18:46:39.889] darwin arm64
[18:46:39.890] SSH Resolver called for "ssh-remote+sniffa", attempt 1
[18:46:39.890] "remote.SSH.useLocalServer": true
[18:46:39.890] "remote.SSH.sshPath": undefined
[18:46:39.890] "remote.SSH.sshConfigurationFile": undefined
[18:46:39.890] "remote.SSH.useFlock": true
[18:46:39.890] "remote.SSH.lockfilesInTmp": false
[18:46:39.890] "remote.SSH.localServerDownload": always
[18:46:39.890] "remote.SSH.remoteServerListenOnSocket": false
[18:46:39.890] "remote.SSH.showLoginTerminal": true
[18:46:39.890] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[18:46:39.890] SSH Resolver called for host: sniffa
[18:46:39.890] Setting up SSH remote "sniffa"
[18:46:39.891] Acquiring local install lock: /var/folders/km/jr_xw52j5499c41bk_m3y6fm0000gn/T/vscode-remote-ssh-sniffa-install.lock
[18:46:39.950] Looking for existing server data file at /Users/bruce/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-sniffa-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json
[18:46:39.951] Using commit id "25a4ee40993f43df9229edc552bd3018c086569d" and quality "exploration" for server
[18:46:39.952] Install and start server if needed
[18:46:39.953] Checking ssh with "ssh -V"
[18:46:40.008] > OpenSSH_8.1p1, LibreSSL 2.7.3

[18:46:40.009] askpass server listening on /var/folders/km/jr_xw52j5499c41bk_m3y6fm0000gn/T/vscode-ssh-askpass-06f1a3f1c63ac238f19d30b8c070541034dd03e2.sock
[18:46:40.009] Spawning local server with {"ipcHandlePath":"/var/folders/km/jr_xw52j5499c41bk_m3y6fm0000gn/T/vscode-ssh-askpass-3d9cf0d447584f3e62d7aaa97dca82c1e124ff55.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49552","-o","ConnectTimeout=60","sniffa"],"dataFilePath":"/Users/bruce/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-sniffa-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json"}
[18:46:40.009] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bruce/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Exploration.app/Contents/Frameworks/Code - Exploration Helper (Renderer).app/Contents/MacOS/Code - Exploration Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/bruce/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/km/jr_xw52j5499c41bk_m3y6fm0000gn/T/vscode-ssh-askpass-06f1a3f1c63ac238f19d30b8c070541034dd03e2.sock"}
[18:46:40.052] Spawned 27734
[18:46:40.161] > local-server> Spawned ssh: 27735
[18:46:40.163] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[18:46:40.238] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:zIgQ9+MuFAIT5IA02RkQfvU6Ra2mgcvvGGVtDsZ45uo
[18:46:40.414] Got askpass request: {"request":"zwu@www.theo.chemie.tu-darmstadt.de's password:"}
[18:46:40.414] Showing password prompt
[18:46:40.415] Listening for interwindow password on /var/folders/km/jr_xw52j5499c41bk_m3y6fm0000gn/T/vscode-ssh-askpass-18bb31a3bac4e625a253c51ebef5919aaf1eb12f.sock
[18:46:40.415] Writing password prompt to globalState
[18:46:48.494] Got password response
[18:46:48.495] Interactor gave response: *********
[18:46:48.495] Cleaning up other-window auth server
[18:46:48.542] stderr> Authenticated to www.theo.chemie.tu-darmstadt.de ("id address deleted by me").
[18:46:48.582] > Last failed login: Fri Dec  4 11:08:55 CET 2020 from x1075.vpn.hrz.tu-darmstadt.de on ssh:notty
> There was 1 failed login attempt since the last successful login.
[18:46:48.705] > ready: 07a66b412e32
[18:46:48.722] > Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
[18:46:48.723] Platform: linux
[18:46:48.765] > 07a66b412e32: running
[18:46:48.794] > Acquiring lock on /home/zwu/.vscode-server-exploration/bin/25a4ee40993f43df9229edc552bd3018c086569d/vscode-remote-lock.zwu.25a4ee40993f43df9229edc552bd3018c086569d
[18:46:48.797] > Found existing installation at /home/zwu/.vscode-server-exploration/bin/25a4ee40993f43df9229edc552bd3018c086569d...
> Checking /home/zwu/.vscode-server-exploration/.25a4ee40993f43df9229edc552bd3018c086569d.log and /home/zwu/.vscode-server-exploration/.25a4ee40993f43df9229edc552bd3018c086569d.pid for a running server
[18:46:48.798] > Looking for server with pid: 80381
[18:46:48.868] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[18:46:48.875] > Checking server status on port 39331 with wget
[18:46:48.879] > 07a66b412e32: start
> sshAuthSock====
> webUiAccessToken====
[18:46:48.880] > listeningOn==39331==
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/1025==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 07a66b412e32: end
[18:46:48.880] Received install output: 
sshAuthSock====
webUiAccessToken====listeningOn==39331==
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/1025==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[18:46:48.880] Remote server is listening on 39331
[18:46:48.881] Parsed server configuration: {"remoteListeningOn":{"port":39331},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1025","platform":"linux"}
[18:46:48.881] Persisting server connection details to /Users/bruce/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-sniffa-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json
[18:46:48.883] Starting forwarding server. localPort 49555 -> socksPort 49552 -> remotePort 39331
[18:46:48.883] Forwarding server listening on 49555
[18:46:48.884] Waiting for ssh tunnel to be ready
[18:46:48.884] [Forwarding server 49555] Got connection 0
[18:46:48.885] Tunneled 39331 to local port 49555
[18:46:48.885] Resolved "ssh-remote+sniffa" to "127.0.0.1:49555"
[18:46:48.896] ------




[18:46:48.923] [Forwarding server 49555] Got connection 1
[18:46:48.923] [Forwarding server 49555] Got connection 2

**Comment by roblourens** [comment]
I don't see anything suspicious in that log

**Comment by roblourens** [comment]
@Chenghao-Wu I guess you are not having the glibc issue that others are having. Could you open a new issue, and try this

- F1 > "Set Log Level" > Trace
- Try to connect again
- Include in the issue any output you see in the devtools console (Help > Toggle developer tools)

**Comment by Chenghao-Wu** [comment]
Thank you a lot for helping me have a check.
I have opened a new issue and copy paste all log info following the way you provided.
Hope it may help!
Thanks again.

**Comment by deepak1556** [comment]
This should be fixed in latest exploration as well as insiders. Closing.
