### ISSUE TITLE
After updating to VS Code Insiders 1.53, Remote SSH stopped working

### ISSUE THREAD

**Issue by Menelion** [microsoft/vscode-remote-release#4292]
- VSCode Version:1.53.0-Insider, Commit: e17aea136d32fdb06d9b32184b04ccd36bb51e9c
- OS Version: Windows 10, Version 1909 (OS Build 18363.815) X64

Steps to Reproduce:

1. Update to VS Code 1.53.0.
2. Install Remote Extension Pack.
3. Try connecting to a Mac OS powered device via Remote SSH.
Expected Result: Everything should work as before.
Actual Result:

```shell
[16:09:48.678] Log Level: 2
[16:09:48.684] remote-ssh@0.62.0
[16:09:48.684] win32 x64
[16:09:48.685] SSH Resolver called for "ssh-remote+mac", attempt 1
[16:09:48.685] "remote.SSH.useLocalServer": false
[16:09:48.686] "remote.SSH.showLoginTerminal": false
[16:09:48.686] "remote.SSH.remotePlatform": {"mac":"macOS"}
[16:09:48.686] "remote.SSH.sshPath": undefined
[16:09:48.686] "remote.SSH.sshConfigurationFile": undefined
[16:09:48.686] "remote.SSH.useFlock": true
[16:09:48.686] "remote.SSH.lockfilesInTmp": false
[16:09:48.686] "remote.SSH.localServerDownload": auto
[16:09:48.686] "remote.SSH.remoteServerListenOnSocket": false
[16:09:48.687] "remote.SSH.showLoginTerminal": false
[16:09:48.687] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[16:09:48.687] SSH Resolver called for host: mac
[16:09:48.687] Setting up SSH remote "mac"
[16:09:48.703] Using commit id "e17aea136d32fdb06d9b32184b04ccd36bb51e9c" and quality "insider" for server
[16:09:48.706] Install and start server if needed
[16:09:48.711] Checking ssh with "ssh -V"
[16:09:48.800] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:09:48.803] Running script with connection command: ssh -T -D 53659 mac bash
[16:09:48.806] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:09:49.018] > 
[16:09:49.019] Got some output, clearing connection timeout
[16:09:49.698] > 8f7372bddf85: running
> 
[16:09:49.725] > Acquiring lock on /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d3
> 2fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c
> \ln /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c.target /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d
> 32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fd
> b06d9b32184b04ccd36bb51e9c
> ln: /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c: File exists
> Installation already in progress...
> 8f7372bddf85: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 8f7372bddf85: end
> 
[16:09:49.726] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:09:49.726] Server installation process already in progress - waiting and retrying
[16:09:50.007] "install" terminal command done
[16:09:50.008] Install terminal quit with output: 
[16:09:50.732] Running script with connection command: ssh -T -D 53659 mac bash
[16:09:50.733] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:09:50.892] > 
[16:09:50.892] Got some output, clearing connection timeout
[16:09:51.545] > 8f7372bddf85: running
> 
[16:09:51.572] > Acquiring lock on /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d3
> 2fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c
> \ln /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c.target /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d
> 32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fd
> b06d9b32184b04ccd36bb51e9c
> ln: /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c: File exists
> Installation already in progress...
> 8f7372bddf85: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 8f7372bddf85: end
> 
[16:09:51.572] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:09:51.573] Server installation process already in progress - waiting and retrying
[16:09:51.817] "install" terminal command done
[16:09:51.817] Install terminal quit with output: 
<...>
```

Does this issue occur when all extensions are disabled?: N/A, Remote SSH is required

**Comment by mgr-inz-rafal** [comment]
Same here. Any help appreciated.

**Comment by Menelion** [comment]
For everyone who wants to downgrade, here's the link to a working build (adjust according to your OS):

https://vscode-update.azurewebsites.net/1.52.0-insider/win32-x64/insider

For more info see #46089.

**Comment by neoswallow** [comment]
I wonder if there is a link to download a specific previous build.

**Comment by roblourens** [comment]
I don't fully understand what the log is showing but I pushed a fix to the nightly version of the SSH extension which should work around it. Please try that. But I don't think that mac ARM is supported yet for remote?

**Comment by roblourens** [comment]
I guess 1.53 insiders should support M1, please discuss this in https://github.com/microsoft/vscode-remote-release/issues/4069 @neoswallow

**Comment by neoswallow** [comment]
At least SSH portion of remote has been working on 1.53.0-insiders M1 builds (host mac is an Intel mac) until it broke with yesterday's build.
Since my issue is with connecting to an Intel mac, #4096 isn't the issue I'm having.
I just installed Remote-SSH (Nightly) and it still doesn't connect.
Below is the log:
```
[12:28:12.891] Log Level: 2
[12:28:12.892] remote-ssh-nightly@2021.1.8132
[12:28:12.892] darwin arm64
[12:28:12.893] SSH Resolver called for "ssh-remote+ethan-mbp-port-forward", attempt 1
[12:28:12.893] "remote.SSH.useLocalServer": true
[12:28:12.893] "remote.SSH.sshPath": undefined
[12:28:12.893] "remote.SSH.sshConfigurationFile": undefined
[12:28:12.893] "remote.SSH.useFlock": true
[12:28:12.893] "remote.SSH.lockfilesInTmp": false
[12:28:12.893] "remote.SSH.localServerDownload": auto
[12:28:12.894] "remote.SSH.remoteServerListenOnSocket": false
[12:28:12.894] "remote.SSH.showLoginTerminal": false
[12:28:12.894] SSH Resolver called for host: ethan-mbp-port-forward
[12:28:12.894] Setting up SSH remote "ethan-mbp-port-forward"
[12:28:12.895] Acquiring local install lock: /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/vscode-remote-ssh-ethan-mbp-port-forward-install.lock
[12:28:12.950] Looking for existing server data file at /Users/swallow/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-ethan-mbp-port-forward-e17aea136d32fdb06d9b32184b04ccd36bb51e9c-2021.1.8132/data.json
[12:28:12.951] Using commit id "e17aea136d32fdb06d9b32184b04ccd36bb51e9c" and quality "insider" for server
[12:28:12.953] Install and start server if needed
[12:28:12.955] Checking ssh with "ssh -V"
[12:28:13.008] > OpenSSH_8.1p1, LibreSSL 2.7.3

[12:28:13.018] askpass server listening on /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/vscode-ssh-askpass-38878a6cdaca47d75842ceb2b9d3ab9acf2abd0b.sock
[12:28:13.018] Spawning local server with {"ipcHandlePath":"/var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/vscode-ssh-askpass-8a0b09d02e8343ec89a4185b96d4bc075852f3ab.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51256","-o","ConnectTimeout=15","ethan-mbp-port-forward"],"dataFilePath":"/Users/swallow/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-ethan-mbp-port-forward-e17aea136d32fdb06d9b32184b04ccd36bb51e9c-2021.1.8132/data.json"}
[12:28:13.018] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/vscode-ssh-askpass-38878a6cdaca47d75842ceb2b9d3ab9acf2abd0b.sock"}
[12:28:13.069] Spawned 30601
[12:28:13.190] > local-server> Spawned ssh: 30602
[12:28:13.192] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[12:28:13.207] > ready: d13beb8916bc
[12:28:13.211] > Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
[12:28:13.211] Platform: macOS
[12:28:13.227] > d13beb8916bc: running
[12:28:13.254] > Acquiring lock on /Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.ethan.e17aea136d32fdb06d9b32184b04ccd36bb51e9c
[12:28:13.260] > \ln /Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.ethan.e17aea136d32fdb06d9b32184b04ccd36bb51e9c.target /Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.ethan.e17aea136d32fdb06d9b32184b04ccd36bb51e9c
[12:28:13.271] > Installing to /Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c...
[12:28:13.276] > d13beb8916bc%%1%%
[12:28:13.302] > Downloading with wget
[12:28:13.689] > wget download failed
> https://update.code.visualstudio.com/commit:e17aea136d32fdb06d9b32184b04ccd36bb51e9c/server-darwin/insider: 2021-01-13 12:28:13 ERROR 404: Not Found.
> printenv:
[12:28:13.699] >     SHELL=/bin/zsh
>     TMPDIR=/var/folders/gl/r78wb5m525jb_7_21m86w3rc0000gn/T/
>     SSH_CLIENT=fe80::472:d4ed:6720:7ad%en7 51254 22
>     USER=ethan
>     VSCODE_AGENT_FOLDER=/Users/ethan/.vscode-server-insiders
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/aria2/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
>     PWD=/Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c
>     LANG=en_US.UTF-8
>     SHLVL=2
>     HOME=/Users/ethan
>     LOGNAME=ethan
>     SSH_CONNECTION=fe80::472:d4ed:6720:7ad%en7 51254 fe80::855:33ce:ab56:3af6%en7 22
>     _=/usr/bin/printenv
>     OLDPWD=/Users/ethan
> Trigger local server download
[12:28:13.699] > d13beb8916bc:trigger_server_download
> platform==macOS==
> vscodeArch==x64==
> destFolder==/Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c==
> d13beb8916bc:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /Users/ethan/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184b04ccd36bb51e9c/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[12:28:13.700] Got malformed request to download on client, invalid platform: macOS
[12:28:13.700] Terminating local server
[12:28:13.709] Resolver error: Error: Client-side server download failed
	at Function.Create (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:64360)
	at /Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:135309
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.t.tryInstallWithLocalServer (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:403248)
	at async /Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:309144
	at async Object.t.withShowDetailsEvent (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:404324)
	at async /Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:402044
	at async S (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:398812)
	at async Object.t.resolveWithLocalServer (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:401671)
	at async Object.t.resolve (/Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:1:312911)
	at async /Users/swallow/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.8132/out/extension.js:127:110333
[12:28:13.710] Local server exit: 15
[12:28:13.714] ------
```
Notably
[12:33:39.268] > wget download failed
> https://update.code.visualstudio.com/commit:e17aea136d32fdb06d9b32184b04ccd36bb51e9c/server-darwin/insider: 2021-01-13 12:33:39 ERROR 404: Not Found.

and
[12:33:39.272] Got malformed request to download on client, invalid platform: macOS

resulting
[12:33:39.279] Resolver error: Error: Client-side server download failed

**Comment by Menelion** [comment]
Sorry for a newbie question, but how to install a nightly version of the extension? My Mac is Intel and it's on Catalina.

**Comment by roblourens** [comment]
Oh, I see the problem now. Looks like the vscode client build that you have was incomplete, and the mac server and mac intel client bits are missing. So I couldn't repro it from my mac intel client because it's one build behind, but arm mac and windows clients will have this issue. Trying to get a new build out, and the ssh nightly change is not relevant after all.

Here are links to the previous builds for you

- https://az764295.vo.msecnd.net/insider/6dc779565e1e4a26104002fde340b68c157c3bc5/VSCode-darwin-arm64.zip
- https://az764295.vo.msecnd.net/insider/6dc779565e1e4a26104002fde340b68c157c3bc5/VSCode-win32-x64-1.53.0-insider.zip

**Comment by roblourens** [comment]
Ok we have published a build which is complete, so this should work normally now on the latest insiders. Sorry for the trouble. We have checks to prevent publishing incomplete builds but they were lost in some build changes.

**Comment by neoswallow** [comment]
> Sorry for a newbie question, but how to install a nightly version of the extension? My Mac is Intel and it's on Catalina.

You can search for remote-ssh in extensions tab and it will show nightly version alongside regular version.

Name: Remote - SSH (Nightly)
Id: ms-vscode-remote.remote-ssh-nightly
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 2021.1.18424
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly

**Comment by roblourens** [comment]
Closing this since we should be back to normal

**Comment by sxtiann** [comment]
still have this issue

**Comment by neoswallow** [comment]
> still have this issue

I'm not having the issue currently.
But I did reset `.vscode-server-insiders` folder (on SSH server) at one point and some other file inside of it at another time.
Both cases resulted in loosing all opened files.
After this was fixed, I did have one other occasion that I had to delete a file inside `.vscode-server-insiders/bin` which also resulted in loosing all opened files.
I think its name had "lock" in it unlike rest of the files there.
If you're still having problem, maybe try that.
