### ISSUE TITLE
Clone Repo in Container Volumne: URL not recognized

### ISSUE THREAD

**Issue by MBAatEJOT** [microsoft/vscode-remote-release#4799]
We don't use GitHub to manage our projects we use Azure DevOps

Since today when I try to "Clone a repository in a cointainer volume" I get the error:
`The repository URL 'https://MyOrg@dev.azure.com/MyProject/MyProject/_git/MyProject' was not recognized`

This is a major break down.

Please fix immediately.

**Comment by chrmarti** [comment]
As a temporary workaround, you can install the previous stable version (0.163.2): Go to the extensions viewlet, click on the gear icon and pick 'Install Another Version...'.
![image](https://user-images.githubusercontent.com/9205389/113260121-2f55c300-92ce-11eb-8e29-14a7278a5ea9.png)

**Comment by brianmoore180** [comment]
I'm also experiencing this issue. Please fix ASAP!

**Comment by dmasur** [comment]
Same here. Workaround from @chrmarti helped

**Comment by egamma** [comment]
@chrmarti overlooked some ADO URL semantics, fix ready for review.

**Comment by egamma** [comment]
Fix released and will be available in version > 0.166.0.

**Comment by chrmarti** [comment]
Fix is available in Remote-Containers 0.166.1.

**Comment by TylerLeonhardt** [comment]
@MBAatEJOT @brianmoore180 @dmasur can you verify that this is fixed, please?

**Comment by brianmoore180** [comment]
This appears to be fixed. Thank you!

**Comment by MBAatEJOT** [comment]
@TylerLeonhardt I can verify the fix as well 👍

**Comment by dmasur** [comment]
For me the problem still exists on 0.166.1
![image](https://user-images.githubusercontent.com/83548/113993436-c41f6a00-9854-11eb-9570-79ab8109f099.png)

**Comment by egamma** [comment]
The filing URL is `git@gitlab.de:workshops/thymeleaf-mvc.git`

**Comment by arwyn** [comment]
@egamma I am experiencing same issue @dmasur  is having.
On 0.163.2 and prior cloning our internal git server URL would bring up volume selection and when 'Unique volume' is selected, it would clone the repository without errors to /workspaces/<project> where <project> was the last section or the URL.

On 0.166.1 the same URL results in an alert dialog as seen in the screen-shot above. After 3~5 seconds the volume selection appeared. When I selected 'Unique volume' it proceeded to clone and open, but the repository was cloned in /workspaces/repository. This break a fair number of internal build scripts that expect the directory location to be fixed. At no point was I given the option to select or choose the project name.

On a related note, opening a previously cloned repository seems re-clone in a new volume. I guess you are using the project name in the volume name hash. The result is suddenly all my WIP and local branches disappear on upgrade. No alert or notification of the change was provided leading to a short WTF moment.

Reverting to or a setting to provide 0.163.2 behaviour would be very much appreciated. We are stuck on 0.163.2 for the time being.

**Comment by gparmeggiani** [comment]
Hi
just stepping in to say that the alert saying that the repository name is not recognized is unnecessary in my opinion: just ask for the name.
However, I still think it can be derived from the URL. Why not taking the word after the last `/` and before `.git` in the URL?

**Comment by egamma** [comment]
@arwyn can you please share internal git server URL.

>but the repository was cloned in /workspaces/repository. This break a fair number of internal build scripts that expect the directory location to be fixed. 

Sorry about that, when the URL is not recognised, then 'repository' is now used as the default project name and clone location. 

Rather than using 'repository' as the default we could prompt for the clone location/project name and use the last segment of the URL as the default. Using the last segment as default will not work when a git clone URL is referring to a commit, branch, or tag (e.g. `https://github.com/owner/repo/tree/branchOwner/branchName` `https://github.com/owner/repo/commit/ID`).

**Comment by egamma** [comment]
@gparmeggiani agreed I was just typing the same https://github.com/microsoft/vscode-remote-release/issues/4799#issuecomment-819612161

**Comment by arwyn** [comment]
@egamma 
> can you please share internal git server URL.
Something along the lines of `ssh://gerrit.company-domain.local/team-name/name/of/repo`. '/' are used as grouping separators and '-' are used for spaces. So an example repo name would be `automation/docker/jenkins-server`. As you can see, using the last part of the URL was not perfect for us either, but it was acceptable.

Using the last part before an optional .git as the default, with the option to edit on first clone would be an improvement over 0.163.2 since we could avoid conflicts (we have at least 3 repos ending in 'tools'). Clicking an additional 'ok' would not be a burden providing you don't have to enter the entire name every time.

**Comment by MBAatEJOT** [comment]
> @gparmeggiani agreed I was just typing the same [#4799 (comment)](https://github.com/microsoft/vscode-remote-release/issues/4799#issuecomment-819612161)
> 
> > However, I still think it can be derived from the URL. Why not taking the word after the last / and before .git in the URL?
> 
> This is a good heuristic 👍

But please be aware that not all providers use `.git` for the repo url.

**Comment by gparmeggiani** [comment]
I'm now wondering why the parsing of the URL is necessary. Why not letting `git clone` decide in which folder clone the repository?

**Comment by egamma** [comment]
>I'm now wondering why the parsing of the URL is necessary. Why not letting git clone decide (or suggest) in which folder clone the repository?

We support that more than repository can be cloned into the same volume for that we need to extract the repository name so that the clone happens in different folders inside the volume, e.g. volume/repoName1, volume/repoName2

**Comment by arwyn** [comment]
> My current thinking is to involve the user when the git URL is not recognized and suggest the last segment of the URL as the repository name.

👍 

Can you automatically reuse the old volume on restart without any additional prompts like it works now? That would cover all my use-cases.

**Comment by egamma** [comment]
>Can you automatically reuse the old volume on restart without any additional prompts like it works now? That would cover all my use-cases.

@arwyn You can stop restart a container that has the volume mounted from the Remote Explorer. What scenario do you have in mind, can you elaborate pls.

**Comment by egamma** [comment]
Implemented the above proposal which actually should bring back the behaviour that existed with unknown repository Urls in version 0.163.

**Comment by arwyn** [comment]
@egamma Thank you for quick handling of the issue.

>  What scenario do you have in mind, can you elaborate pls.

Nothing special. When windows restarts and vscode opens a previously worked on repository, I expect the previous volume to be used (and any local branches / commits / wip are preserved.
The same would go for if I rebuilt the container due to Dockerfile changes.

Worked flawlessly for 0.163.2. Stopped working at same time, so I suspect it is to do with the repo name change. I will test again when your changes are rolled out and add a new issue and link here if there is any problem.

**Comment by egamma** [comment]
@arwyn I've attached a vsix with the latest version. I would appreciate if you can verify the issue and the restart behaviour you mention.

To install the extension from the vsix follow these steps:
- download [remote-containers-0.167.0.txt](https://github.com/microsoft/vscode-remote-release/files/6323792/remote-containers-0.167.0.txt)
- rename the file suffix from .txt to .vsix
- use the 'Install from VSIX...' command in the Extensions view to install the extension as shown in the screenshot
- in the extensions viewlet verify that you have version 0.167.0 installed, see the second screenshot

![image](https://user-images.githubusercontent.com/172399/115000813-68339180-9ea3-11eb-8d61-b570b518e0c7.png)

![image](https://user-images.githubusercontent.com/172399/115001236-c6f90b00-9ea3-11eb-9922-e7d72fc7c8d0.png)

**Comment by gparmeggiani** [comment]
I get this error while installing the vsix

![image](https://user-images.githubusercontent.com/7251603/115002315-e2b0e100-9ea4-11eb-9e13-e15ee6f5e749.png)

**Comment by chrmarti** [comment]
I have release 0.168.0 with the latest changes. You currently need VS Code Insiders to get that version: https://code.visualstudio.com/insiders/

**Comment by egamma** [comment]
@gparmeggiani sorry, I've overlooked that you need to run on insiders to install the VSIX (the engine version of the extension requires a newer version than the stable version of VS Code). 

Thanks to @chrmarti for publishing the latest version you can now just install from the Marketplace when running on the insiders version.

**Comment by arwyn** [comment]
@egamma Sorry for delay in response, I was afk for a few days.

I have tested with 0.169 (insider latest) and I can confirm that all issues I was having have been resolved. Thank you again for the quick response and handling of the issues.

**Comment by egamma** [comment]
@arwyn thank you for the verification!
