### ISSUE TITLE
Endlessly installing extensions on WSL2 (Ubuntu-20.04)

### ISSUE THREAD

**Issue by SturmB** [microsoft/vscode-remote-release#5129]
- VSCode Version:
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: Ubuntu 20.04.2 LTS on Windows 10 x86_64
- Remote Extension/Connection Type: WSL2
- Logs: (Need help on how to get the relevant logs for this issue.)

This problem is very similar to https://github.com/microsoft/vscode-remote-release/issues/3152. However, I do not know how to increase the log level to diagnose it further by myself.

Steps to Reproduce:

1. Install a new copy of the above version (latest as of this writing) of VS Code from a clean state on Windows 10.
2. Launch it from WSL  with `code .`.
3. Install an extension or two (almost doesn't matter which ones). Notice that there isn't an option to "Install on WSL:Ubuntu-20.04" anymore.
4. While in the Extensions Sidebar, notice that the extensions are only installed locally, not in WSL.
5. Click the little cloud icon next to the section titled "WSL: Ubuntu-20.04 - Installed" and choose one or more locally-installed extensions to install to WSL.
6. Watch as the toast appears and states "Installing Extensions...", yet never actually does so and endlessly animates.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by bamurtaugh** [comment]
Can you please turn on trace level logging (Developer: Set Log Level... -> Trace), and then share your logs from:

- View -> Open View… -> Log (Remote Server)
- Log (Window)

Thank you!

**Comment by SturmB** [comment]
Thank you, @bamurtaugh. I've attached the two logs for you here. I'm pretty sure I've masked all sensitive info in them:
[SturmB-remoteExtension.log](https://github.com/microsoft/vscode-remote-release/files/6616002/SturmB-remoteExtension.log)
[SturmB-renderer.log](https://github.com/microsoft/vscode-remote-release/files/6616003/SturmB-renderer.log)

Also, I've now discovered that the problem is not just limited to extensions. When I open a workspace that is _most definitely_ source-controlled with git, VS Code complains in the Source Control panel, "The folder currently open doesn't have a git repository. […]" So, even though the status bar shows that VS Code is connected to WSL, it seems like the connection isn't complete, perhaps? I don't know.

**Comment by bamurtaugh** [comment]
cc @sandy081 for any thoughts

**Comment by sandy081** [comment]
Seems to me connection issue with VS Code remote server installed in WSL.

@aeschli FYI

**Comment by SturmB** [comment]
> Seems to me connection issue with VS Code remote server installed in WSL.

I would agree. But what can be done to fix the issue or even 'reset' that connection completely?

**Comment by aeschli** [comment]
The renderer log shows that the remote extension host constantly reconnects (about 10 times in 4 minutes)
e.g.
```
[2021-06-08 07:12:14.886] [renderer1] [info] [remote-connection][ExtensionHost][2ad61…]
[reconnect] starting reconnecting loop. You can get more information with the trace log level. needs to be recopnnected over 10 times in the 5 minutes
```

**Comment by alexdima** [comment]
@SturmB I have tried installing many extensions, but I could not reproduce. I have added more logging yesterday when the renderer process - WSL server process connection gets interrupted. This logging is present in our latest [Insiders version](https://code.visualstudio.com/insiders/).

From my looking at the log, it looks like the renderer reconnects to the extension host process running inside WSL every 20 seconds. This indicates that the extension host process running inside WSL is not healthy or unresponsive. This aligns with noticing that git is not working and that is because git executes together with the other extensions in the extension host process.

So could you please try using [our latest insiders](https://code.visualstudio.com/insiders/) and if you are able to reproduce the issue, I would appreciate if you could attach the following log files:
* `F1 > Developer: Show Window Log`
* the WSL server log present under WSL at `~/.vscode-remote/data/<timestamp>/remoteagent.log`
* the remote extension host log present under WSL at  `~/.vscode-remote/data/<timestamp>/exthost<N>/exthost.log`

Thank you!

**Comment by SturmB** [comment]
Thanks for looking into this, @alexdima.

Here's the updated 'about' info:

```
Version: 1.58.0-insider (user setup)
Commit: 012b14606f75ec4fed90d7ab4154f63dffab9503
Date: 2021-06-11T05:14:11.473Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

And here is one of the three files you have requested:
- [sturmb-renderer-2021-06-11.log](https://github.com/microsoft/vscode-remote-release/files/6640057/sturmb-renderer-2021-06-11.log)

I could not find the other two as there does not appear to be a `.vscode-remote/` directory anywhere; not within WSL and not within Windows.

As a consolation prize, here is a `remote-agent.log` file that I found within `~/.vscode-server-insiders/data/logs/20210611T130930/`:
- [remoteagent.log](https://github.com/microsoft/vscode-remote-release/files/6640082/remoteagent.log)

**Comment by alexdima** [comment]
You are right, the Insiders version uses `~/.vscode-server-insiders/...` and `~/.vscode-remote/...` is only used when running from source, appologies for mixing them up. 

Thank you for the new logs, these confirm my suspicion that the remote extension host is really unhealthy. Given you are not seeing any `exthost` log, it looks to me like the extension host process fails to spawn. Before spawning the extension host, we are running some process to read the user environment and we block on that completing. 

That code can be skipped by passing `--force-disable-user-env`, but I am not sure how this argument can be passed to the vscode server via WSL.

@aeschli IMHO `resolveShellEnv` is never returning and that blocks the launching of the WSL remote extension host. Have you seen this before? Do you have any insights here?

**Comment by alexdima** [comment]
I am now convinced that `resolveShellEnv` is hanging, as the `remoteagent.log` should contain `<PID> Launched Extension Host Process` and that one is logged immediately after the shell environment is resolved.

**Comment by TylerLeonhardt** [comment]
@SturmB  I think we really need to see the trace logs to understand this but to get those is a little tricky because we need the log level to set to trace when we start VS Code. Thankfully we have a way to do that.

Run this command:
![image](https://user-images.githubusercontent.com/2644648/121743849-d917b400-cab6-11eb-846c-ba8b59adea15.png)

That opens a JSON file for which you need to add this to it:
```json
"log-level": "trace"
```

Then do your repro again and open the Main Output pane
![image](https://user-images.githubusercontent.com/2644648/121744111-43c8ef80-cab7-11eb-8a73-7e1424cc6a6d.png)

And share what's inside.

**Comment by SturmB** [comment]
@alexdima If you're referring to which shell should be the default for the built-in terminal, then I'm not entirely sure. I have a vague recollection (my memory is awful!) that I went through and changed some terminal-related settings in the JSON file a while back when I upgraded to WSL2, killed my old WSL1 instance, etc.

However, this should be a moot point now as I have since completely uninstalled VS Code and manually deleted as many of its hidden folders as I could find (following [some SO instructions I found](https://stackoverflow.com/questions/47689536/uninstall-visual-studio-code-in-windows)). The `settings.json` file now is minimal and doesn't include anything about the integrated terminal.

I currently do all of my CLI work in Windows Terminal.

---

I see your recent posts just as I was typing this. Btw, my main (non-insiders) copy of VS Code just updated itself to 1.57.0, but the problem still persists, natch.

I've enabled trace logging. Here are both the main and window logs, just in case you could use both:
- [sturmb-2021-06-11a-main.log](https://github.com/microsoft/vscode-remote-release/files/6640828/sturmb-2021-06-11a-main.log)
- [sturmb-2021-06-11a-renderer.log](https://github.com/microsoft/vscode-remote-release/files/6640829/sturmb-2021-06-11a-renderer.log)

**Comment by alexdima** [comment]
@TylerLeonhardt I think you are investigating in the wrong direction. On WSL, the main process runs on Windows. The server process runs inside WSL. I believe `resolveShellEnv` does not return when it is executed on the server process. The relevant log should be at `remoteagent.log` located in `~/.vscode-server<-insiders>/data/<timestamp>/remoteagent.log`

**Comment by SturmB** [comment]
Here's the `remoteagent.log` file. I'm heading out for the weekend. Thanks again!

- [sturmb-2021-06-11a-remoteExtension.log](https://github.com/microsoft/vscode-remote-release/files/6641490/sturmb-2021-06-11a-remoteExtension.log)

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by alexdima** [comment]
Thank you @SturmB , I've looked at the log. Unfortunately the trace log level reaches the server too late, after the problematic `resolveShellEnv` call, so we don't get to see the trace calls from within that method.

@aeschli Do you have some hints on how to start the server with the trace log level?

**Comment by alexdima** [comment]
I have pushed a change on my side to proceed launching the extension host even without the shell environment if `resolveShellEnv` does not return within 10 seconds. When this will happen the following will be printed to the log as an error: `Could not resolve shell environment within 10 seconds. Proceeding without shell environment...`.

@SturmB This doesn't fix the root cause, which is still unknown, but it should unblock you, starting with tomorrow's insiders build.

**Comment by alexdima** [comment]
@SturmB I've just noticed [this other thread](https://github.com/microsoft/vscode-remote-release/issues/5010#issuecomment-836377459). Do you happen to have any content under WSL in the `.zshrc` / `.bashrc` files that live in the `$HOME` directory of WSL ?

**Comment by aeschli** [comment]
Please set `"remote.WSL.debug": true` and make sure you have the version 0.58.1 of Remote-WSL )ms-vscode-remote.remote-wsl@0.58.1)
This will turn on log=trace also for the server.

**Comment by SturmB** [comment]
I'm not entirely sure what you mean by having any content in them. Yes, I do absolutely have startup dotfiles like that, customized from a base installation of Antigen with Powerlevel10k:

- https://pastebin.com/u/SturmB/1/reXkJ9Ve

And I did notice a call to an invalid directory on the last line of `.zshrc.local`, but I commented it out and restarted WSL, but the issue persists.

**Comment by SturmB** [comment]
@alexdima Okay, so I've just updated to today's release of the insiders build. Indeed, I am now seeing the Source Control panel populated with my git info and I am able to install a local extension to 'remote' WSL.

When I started the program up, it opened a WSL terminal and spewed [a bunch of logging info](https://github.com/microsoft/vscode-remote-release/files/6657904/sturmb-2021-06-15-terminal.log). Also, here are two more logs after the upgrade. I can definitely see the 'Could not resolve shell environment…' message:

- [sturmb-2021-06-15-remoteExtension.log](https://github.com/microsoft/vscode-remote-release/files/6657911/sturmb-2021-06-15-remoteExtension.log)
- [sturmb-2021-06-15-remoteExtHost.log](https://github.com/microsoft/vscode-remote-release/files/6657912/sturmb-2021-06-15-remoteExtHost.log)

**Comment by alexdima** [comment]
@bpasero @joaomoreno Here is the relevant trace information:

```
[2021-06-15 14:29:19.018] [remoteagent] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-06-15 14:29:19.018] [remoteagent] [trace] getUnixShellEnvironment#runAsNode undefined
[2021-06-15 14:29:19.018] [remoteagent] [trace] getUnixShellEnvironment#noAttach undefined
[2021-06-15 14:29:19.020] [remoteagent] [trace] getUnixShellEnvironment#env {"USER":"sturm","VSCODE_WSL_EXT_LOCATION":"/mnt/c/Users/christopher.mcgee/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.58.1","SHLVL":"0","HOME":"/home/sturm","OLDPWD":"/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code Insiders","WSL_DISTRO_NAME":"Ubuntu-20.04","LOGNAME":"sturm","VSCODE_WSL_DEBUG_INFO":"true","WSL_INTEROP":"/run/WSL/8800_interop","NAME":"Apache","_":"/usr/bin/sh","TERM":"xterm-256color","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Amazon Corretto/jdk15.0.2_7/bin:/mnt/c/Python39/Scripts/:/mnt/c/Python39/:/mnt/c/Program Files/Amazon Corretto/jdk11.0.7_10/bin:/mnt/c/Program Files/Amazon Corretto/jdk1.8.0_252/bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Python27/:/mnt/c/Python27/Scripts:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files/Java/jdk-11.0.3/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Users/christopher.mcgee/AppData/Local/Microsoft/WindowsApps:/mnt/c/php:/mnt/c/ProgramData/ComposerSetup/bin:/mnt/c/PSTools:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/Program Files (x86)/WinMerge:/mnt/c/Program Files (x86)/Yarn/bin/:/mnt/c/Program Files/7-Zip:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/PuTTY/:/mnt/c/Program Files/Amazon Corretto/jdk15.0.2_7/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/christopher.mcgee/scoop/shims:/mnt/c/Users/christopher.mcgee/AppData/Roaming/Composer/vendor/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Yarn/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/nvs/default:/mnt/c/Users/christopher.mcgee/AppData/Local/nvs/:/mnt/c/Users/christopher.mcgee/dev/Tools/apache-maven-3.8.1/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code Insiders/bin","VSCODE_AGENT_FOLDER":"/home/sturm/.vscode-server-insiders","LANG":"C.UTF-8","SHELL":"/bin/zsh","VSCODE_SERVER_TAR":"/mnt/c/Users/CHRIST~1.MCG/AppData/Local/Temp/vscode-remote-wsl/b79d23d3568db6c926c5ac428457c31f4dfc1c00/vscode-server-insider-linux-x64.tar.gz","PWD":"/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code Insiders","HOSTTYPE":"x86_64","WSLENV":"VSCODE_WSL_EXT_LOCATION/up:VSCODE_SERVER_TAR/up","VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH":"/home/sturm/.vscode-server-insiders/bin/b79d23d3568db6c926c5ac428457c31f4dfc1c00/remote/node_modules","VSCODE_CWD":"/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code Insiders","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1"}
[2021-06-15 14:29:19.020] [remoteagent] [trace] getUnixShellEnvironment#shell /bin/zsh
[2021-06-15 14:29:19.020] [remoteagent] [trace] getUnixShellEnvironment#spawn ["-ilc"] '/home/sturm/.vscode-server-insiders/bin/b79d23d3568db6c926c5ac428457c31f4dfc1c00/node' -p '"cd829ac0eb6c" + JSON.stringify(process.env) + "cd829ac0eb6c"'
[2021-06-15 14:29:19.040] [remoteagent] [trace] Started scanning system extensions
[2021-06-15 14:29:19.040] [remoteagent] [trace] Started scanning user extensions
[2021-06-15 14:29:19.041] [remoteagent] [trace] Started scanning system extensions
[2021-06-15 14:29:19.041] [remoteagent] [trace] Started scanning user extensions
[2021-06-15 14:29:19.041] [remoteagent] [trace] Started scanning user extensions
[2021-06-15 14:29:29.017] [remoteagent] [error] [resolve shell env] Could not resolve shell environment within 10 seconds. Proceeding without shell environment...
```

Given the changes in https://github.com/microsoft/vscode/commit/eaf29b7e243ca5d68c8cb472f82de6be7e777390 which moves the 10s timeout inside `resolveShellEnv`, I'm not sure if you need more information to track down what the problem is. One small debt there might be that it would be good to kill the spawned process when giving up.

**Comment by bpasero** [comment]
Pushed https://github.com/microsoft/vscode/commit/f4fe15ac917b82b91e866e67d6f706b9bd39128f to kill the child process when the 10s pass, @joaomoreno please review.

@SturmB when in WSL you run `/bin/zsh -ilc "<path to node.js> -p 'JSON.stringify(process.env)'" does that ever return?

**Comment by SturmB** [comment]
@bpasero It returns in about one second:
```lang.bash
$ /bin/zsh -ilc "/home/sturm/.nvs/default/bin/node -p 'JSON.stringify(process.env)'"
{"HOSTTYPE":"x86_64","LANG":"C.UTF-8","PATH":"/home/sturm/.nvs/default/bin:/home/sturm/.local/bin:/home/sturm/bin:/home/sturm/.composer/vendor/bin:/home/sturm/.gem/ruby/3.0.0/bin:/home/sturm/.nvs/default/bin:/home/sturm/.local/bin:/home/sturm/bin:/home/sturm/.composer/vendor/bin:/home/sturm/.gem/ruby/3.0.0/bin:/home/sturm/.rvm/gems/ruby-3.0.0/bin:/home/sturm/.rvm/gems/ruby-3.0.0@global/bin:/usr/share/rvm/rubies/ruby-3.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Amazon Corretto/jdk15.0.2_7/bin:/mnt/c/Python39/Scripts/:/mnt/c/Python39/:/mnt/c/Program Files/Amazon Corretto/jdk11.0.7_10/bin:/mnt/c/Program Files/Amazon Corretto/jdk1.8.0_252/bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Python27/:/mnt/c/Python27/Scripts:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files/Java/jdk-11.0.3/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Users/christopher.mcgee/AppData/Local/Microsoft/WindowsApps:/mnt/c/php:/mnt/c/ProgramData/ComposerSetup/bin:/mnt/c/PSTools:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/Program Files (x86)/WinMerge:/mnt/c/Program Files (x86)/Yarn/bin/:/mnt/c/Program Files/7-Zip:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/PuTTY/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/christopher.mcgee/scoop/shims:/mnt/c/Users/christopher.mcgee/AppData/Roaming/Composer/vendor/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Yarn/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/nvs/default:/mnt/c/Users/christopher.mcgee/AppData/Local/nvs/:/mnt/c/Users/christopher.mcgee/dev/Tools/apache-maven-3.8.1/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/christopher.mcgee/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/usr/share/rvm/bin:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fancy-ctrl-z:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gnu-utils:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/kubectl:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rake:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/systemd:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/zsh_reload:/home/sturm/.antigen/bundles/zsh-users/zsh-autosuggestions:/home/sturm/.antigen/bundles/popstas/zsh-command-time:/home/sturm/.antigen/bundles/unixorn/autoupdate-antigen.zshplugin:/home/sturm/.antigen/bundles/urbainvaes/fzf-marks:/home/sturm/.antigen/bundles/ytet5uy4/fzf-widgets:/home/sturm/.antigen/bundles/zdharma/fast-syntax-highlighting-v1.2:/home/sturm/.antigen/bundles/joel-porquet/zsh-dircolors-solarized:/home/sturm/.antigen/bundles/romkatv/powerlevel10k:/home/sturm/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/sturm/.antigen/bundles/zsh-users/zsh-completions:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo:/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/snap/bin","TERM":"xterm-256color","WSLENV":"WT_SESSION::WT_PROFILE_ID","WT_SESSION":"730337f7-806c-4dbe-890e-28becd4d10b2","WT_PROFILE_ID":"{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}","WSL_INTEROP":"/run/WSL/32423_interop","NAME":"Apache","HOME":"/home/sturm","USER":"sturm","LOGNAME":"sturm","SHELL":"/bin/zsh","WSL_DISTRO_NAME":"Ubuntu-20.04","SHLVL":"2","PWD":"/home/sturm/devops","OLDPWD":"/home/sturm/devops","rvm_path":"/usr/share/rvm","rvm_prefix":"/usr/share","rvm_bin_path":"/usr/share/rvm/bin","rvm_version":"1.29.12 (manual)","GEM_HOME":"/home/sturm/.rvm/gems/ruby-3.0.0","GEM_PATH":"/home/sturm/.rvm/gems/ruby-3.0.0:/home/sturm/.rvm/gems/ruby-3.0.0@global","MY_RUBY_HOME":"/usr/share/rvm/rubies/ruby-3.0.0","IRBRC":"/usr/share/rvm/rubies/ruby-3.0.0/.irbrc","RUBY_VERSION":"ruby-3.0.0","EDITOR":"vim","PAGER":"less","LESS":"-R","LSCOLORS":"Gxfxcxdxbxegedabagacad","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","ZSH_TMUX_TERM":"screen-256color","ZSH_TMUX_CONFIG":"/home/sturm/.tmux.conf","_ZSH_TMUX_FIXED_CONFIG":"/home/sturm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux/tmux.extra.conf","FZF_WIDGET_ROOT":"/home/sturm/.antigen/bundles/ytet5uy4/fzf-widgets","FZF_WIDGET_TMUX":"0","FZF_WIDGET_CACHE":"/home/sturm/.cache/fzf-widgets","P9K_SSH":"0","FZF_TMUX":"0","FZF_DEFAULT_OPTS":"--height 100% --reverse","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","MOTD_SHOWN":"update-motd","SSH_AUTH_SOCK":"/tmp/ssh-dSMews0bMGkF/agent.32629","SSH_AGENT_PID":"32630","DO_API_TOKEN":"8f90a71407fcc93d39a8ad8254943a6adb82e6d6f14dd4e8e26b0a65f11aa767","NVS_HOME":"/home/sturm/.nvs","NVS_ROOT":"/home/sturm/.nvs","NVS_OS":"linux","NVS_USE_XZ":"1","P9K_TTY":"old","_P9K_TTY":"/dev/pts/6","ZSH_COMMAND_TIME":"","rvm_alias_expanded":"","rvm_bin_flag":"","rvm_docs_type":"","rvm_gemstone_package_file":"","rvm_gemstone_url":"","rvm_niceness":"","rvm_nightly_flag":"","rvm_only_path_flag":"","rvm_pretty_print_flag":"","rvm_proxy":"","rvm_quiet_flag":"","rvm_ruby_bits":"","rvm_ruby_file":"","rvm_ruby_make":"","rvm_ruby_make_install":"","rvm_ruby_mode":"","rvm_script_name":"","rvm_sdk":"","rvm_silent_flag":"","rvm_use_flag":"","rvm_hook":"","_":"/home/sturm/.nvs/default/bin/node","rvm_stored_umask":"022","rvm_environments_path":"/home/sturm/.rvm/environments","rvm_gems_path":"/home/sturm/.rvm/gems","rvm_gems_cache_path":"/home/sturm/.rvm/gems_cache","rvm_wrappers_path":"/home/sturm/.rvm/wrappers","rvm_create_flag":"1","rvm_user_path":"/home/sturm/.rvm/user","rvm_log_path":"/home/sturm/.rvm/log","rvm_user_install_flag":"0","rvm_loaded_flag":"1"}
```

**Comment by bpasero** [comment]
Does it change if you use `/home/sturm/.vscode-server-insiders/bin/b79d23d3568db6c926c5ac428457c31f4dfc1c00/node` instead?

**Comment by SturmB** [comment]
@bpasero The time to execute does not seem to change. The returned JSON is also identical, save for the underscore entry near the end:

`"_":"/home/sturm/.nvs/default/bin/node"`
vs.
`"_":"/home/sturm/.vscode-server-insiders/bin/b79d23d3568db6c926c5ac428457c31f4dfc1c00/node"`

**Comment by bpasero** [comment]
Ok then I am not sure and would have to defer to the original authors of that method.

**Comment by alexdima** [comment]
@bpasero I've recently read [here](https://github.com/microsoft/vscode-remote-release/issues/5162#issuecomment-861200590) about a possibly similar situation where a script called `pipes.sh` was used inside `.zshrc`. Maybe that one could be a repro for the hang. Perhaps these scripts execute differently when launched from a tty vs when launched from a nodejs process?

**Comment by SturmB** [comment]
I do not use `pipes.sh`, but there may be something else in my dotfiles that could be causing an issue. I pasted a link to them above.

However, I have just discovered that said pastebin link doesn't actually take you to those dotfiles if you aren't logged in to the service, so here they are individualized:

- [.zshrc](https://pastebin.com/z4EutY5v)
- [.zshrc.local](https://pastebin.com/Cizn78N2)
- [.aliases](https://pastebin.com/k0ZnNh5T)
- [.p10k.zsh](https://pastebin.com/c05TXPC2)
- [.fzf.zsh](https://pastebin.com/aayJRbVu)
- [.tmux.conf](https://pastebin.com/cs8j4Ap5)

**Comment by SturmB** [comment]
Welp, I just updated to v1.58.0 and this problem seems to have gone away now. My only guess is that the `resolveShellEnv` patch that @alexdima pushed to the Insiders build finally made its way into stable.

If anyone wants me to output some more logs, I'll be happy to do so. (At least, for the next few workdays. After that, I'm leaving this company and won't have access to this PC anymore.)

Should we close the issue or keep it open because the root cause still hasn't been identified and fixed?

**Comment by bessw** [comment]
It seems like I've got the same problem, because of this I can't use my ssh-agent from within vscode, thus the git extension can't push or pull.
Running git push/pull commands from within the terminal in vscode works.

My .bashrc inside wsl launches an ssh-agent and sets SSH_AUTH_SOCK variable.

When launching vscode I can see that my ssh-agent is getting started, so it seems like the .bashrc file is being interpreted, but vscode doesn't recognise when it's done.

```bash
$ time source ~/.bashrc 
real    0m0.029s
user    0m0.018s
sys     0m0.002s
```

Log (Remote Server):
```
[remoteagent] [error] [resolve shell env] Could not resolve shell environment within 10 seconds. Proceeding without shell environment...
[remoteagent] [error] getUnixShellEnvironment#error An unknown error occurred. Please consult the log for more details.
```

**Comment by SturmB** [comment]
I still think the underlying issue persists, but have no way of proving it for now. Thus, I will close the issue and we'll see if anything happens in the future to cause it to resurface.
