### ISSUE TITLE
Cannot start vscode in WSL

### ISSUE THREAD

**Issue by pedrodaniel10** [microsoft/vscode-remote-release#6294]
Not sure if this is the right place to write this issue but after running `code <PATH>` vscode updated (possibly due to tomorrow's Microsoft Patch Day. 
Aparently, this update broke something as a certain binary is not found anymore. Every time I run the previous command, the following error appears:

`/mnt/c/Users/Pedro/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/pedrodaniel10/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found`

[Windows]
Microsoft Windows Version 20H2 (OS Build 19042.1466)

[VSCode]
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

[Remote - WSL]
Version: v0.64.2 (shown in vscode)

As we can see, the version shown in VSCode doesn't match with the error.
Also, the list of files:
```
pedrodaniel10@din008b9:~/.vscode-server-server$ ls -al /home/pedrodaniel10/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/
total 20
drwxr-xr-x 4 pedrodaniel10 pedrodaniel10 4096 Feb  7 09:24 .
drwxr-xr-x 6 pedrodaniel10 pedrodaniel10 4096 Feb  7 09:14 ..
-rwxr-xr-x 1 pedrodaniel10 pedrodaniel10  230 Feb  3 04:21 code-server
drwxr-xr-x 2 pedrodaniel10 pedrodaniel10 4096 Feb  3 04:24 helpers
drwxr-xr-x 2 pedrodaniel10 pedrodaniel10 4096 Feb  3 04:24 remote-cli
```

**Comment by fsteinmetz** [comment]
Same issue here with remote-ssh. The `code` executable is in the `remote-cli` directory, thus not available in `$PATH`.

**Comment by va1entin** [comment]
I've experienced this issue as well. Running `code` in WSL2 resulted in numerous errors regarding missing files.

It starts like this:

```
/mnt/c/Users/ValentinHeidelberger/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
```

So I fixed it by creating a symlink:
`ln -s  /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli/code /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code`

Then, running `code` would throw another error

`/home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: 12: /home/val/.vscode-server-server/bin/node: not found`

Again, creating a symlink fixed it
`ln -s /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/node /home/val/.vscode-server-server/bin/node`

Finally, I got this error running `code`

![image](https://user-images.githubusercontent.com/31535155/152770302-359f3ebe-e63f-4b50-9798-ab1309404788.png)

After creating the mentioned directory and symlink in it, the error went away and VS Code started again from WSL2!
```
mkdir /home/val/.vscode-server-server/bin/out
ln -s /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/out/server-cli.js /home/val/.vscode-server-server/bin/out/server-cli.js
```

After VS Code had started successfully once, I was able to remove all the symlinks and dir created before. VS Code would still start with no errors.

`rm /home/val/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code /home/val/.vscode-server-server/bin/node /home/val/.vscode-server-server/bin/out/server-cli.js`

So here's what I ran in a copy-pasteable manner:

```
ln -s ~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli/code ~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code

ln -s ~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/node ~/.vscode-server-server/bin/node

mkdir ~/.vscode-server-server/bin/out

ln -s ~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/out/server-cli.js ~/.vscode-server-server/bin/out/server-cli.js

code

rm ~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code ~/.vscode-server-server/bin/node ~/.vscode-server-server/bin/out/server-cli.js
```

**Comment by schweigert** [comment]
I have the same problem.
I can't open the projects from wsl.

```
/mnt/c/Users/marlon.schweigert/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2/scripts/wslCode.sh: 63:
/home/schweigert/.vscode/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/bin/remote-cli/code: not found
```

**Comment by thesteve0** [comment]
OK here is how I fixed it:

1. Open VS Code on Windows
2. Open Extensions and then search on WSL
3. It should say the extension needs to be reloaded - go ahead and reload it
4. Open WSL and type `code`
5. This should force another upgrade of code and this time it should launch. 

I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. 
Hope this helps

**Comment by erSitzt** [comment]
@thesteve0 just in time fix :) ran into this issue 5 min ago :)

**Comment by cguertin14** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

yup that worked, thanks :)

**Comment by librepreso** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

Thank you! It worked.

**Comment by cmendible** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

Did not work for me (ARM64 device). Still get `Error: Cannot find module 'minimist'`

**Comment by Fhrozen** [comment]
@cmendible 
I tried the same as: 

> OK here is how I fixed it:
> 
> Open VS Code on Windows
> Open Extensions and then search on WSL
> It should say the extension needs to be reloaded - go ahead and reload it

just: 
2. Open Extensions and then search on *remote - SSH*
3. It should say `switch to pre-released version`, click and reload.

They fixed in the pre-released.

**Comment by cmendible** [comment]
> Hi,
> 
> I'm experiencing: `(node:302) UnhandledPromiseRejectionWarning: Error: Cannot find module 'minimist'` while trying to open a folder on WSL2.
> 
> My setup:
> 
> ```
> Device name	...
> Processor	Microsoft SQ2 @ 3.15 GHz   3.15 GHz
> Installed RAM	16.0 GB (15.5 GB usable)
> Device ID	...
> Product ID	...
> System type	64-bit operating system, ARM-based processor
> 
> Edition	Windows 11 Pro
> Version	21H2
> Installed on	‎11/‎25/‎2021
> OS build	22000.469
> Serial number	...
> Experience	Windows Feature Experience Pack 1000.22000.469.0
> 
> Version: 1.65.0-insider (user setup)
> Commit: 97c1e76d668d23d568044feb31083407f4c4b1ed
> Date: 2022-02-07T08:56:11.586Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT ia32 10.0.22000 
> ```
> 
> Tried restarting WSL and deleting `/.vscode-server-insiders/bin` but no luck :(

My issue is  WSL2, not SSH  

> @cmendible I tried the same as:
> 
> > OK here is how I fixed it:
> > Open VS Code on Windows
> > Open Extensions and then search on WSL
> > It should say the extension needs to be reloaded - go ahead and reload it
> 
> just: 2. Open Extensions and then search on _remote - SSH_ 3. It should say `switch to pre-released version`, click and reload.
> 
> They fixed in the pre-released.

My issue is with WSL not with SSH. Anyway I tried without luck...

**Comment by hyperion2019** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

You are a life saver!

**Comment by Parrryy** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

This did not fix for the issue for me. There is no option to reload.

**Comment by smartexpert** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

worked for me. I searched WSL in the extensions opened directly from windows and updated it. Then moved to reload then closed vs code. Then attempted to open it with `code .` in WSL. It downloaded a new version and worked as before.

**Comment by qitianliang** [comment]
> > keep it simple, uninstall `vscode` on Windows, and re-install solved this issue for me.
> 
> I've uninstalled on VScode, reinstalled. Shut down and restarted WSL. Seems to be continually happening.
> 
> code command does however work inside a terminal with VScode.

I have upgraded my ubuntu(wsl2) inside the Windows terminal like this `sudo apt update -y && sudo apt upgrade -y` after reinstalled the vscode.  I don't think it's necessary. You can have a try.

**Comment by chrissmithptml** [comment]
The error I encountered is very much what I see you're all facing.

The only way I was able to fix this issue was by completely removing the WSL extension from VS Code, then reinstalling it to an earlier version of the WSL Remote extension.  I rolled back to v0.63.11

I'm running on WSL2 using Ubuntu 20 LTS.   Once I rolled back to v0.63.11 it seems to be working now (though it did take me several tries before it took)

**Comment by toothbrush7777777** [comment]
I had a similar issue, where VS Code kept refusing to load WSL windows after the update, saying that `node` could not be found.
The following steps fixed the problem for me:
1. Exit VS Code from a non-WSL window (File > Exit)
2. Update package lists on Ubuntu (`sudo apt update`) _– note that that this may be irrelevant_
3. Shut down WSL (`wsl --shutdown`)
4. Start VS Code again

**Comment by bamurtaugh** [comment]
Thank you all for discussing and for the solutions/workarounds. Are folks still experiencing this issue? Or did reloading VS Code / Remote - WSL (i.e. https://github.com/microsoft/vscode-remote-release/issues/6294#issuecomment-1031974516) solve it?

**Comment by ctsstc** [comment]
None of these worked for me, I tried doing the apt update & upgrade, uninstalling & reinstalling the extension.
The only thing I haven't tried is reinstalling vscode.

**Comment by Brend-Smits** [comment]
This is definitely still an issue @bamurtaugh. I tried troubleshooting the problem but I couldn't find a solution aside from reverting my VSCode update and going back to version 1.63.2

**Comment by aeschli** [comment]
The issue was all related to the Remote-WSL extension to be slow in beeing updated.
VS Code Builds 1.64 and higher need Remote-WSL 0.64.2 and higher.

@ctsstc @Brend-Smits If you are on these versions and still see the problem, please file a new an issue. Please attach the WSL log (Command: `Remote-WSL: Show Log).

**Comment by fanktt** [comment]
It might happen because I installed two setups of VS Code ("system setup" and "user setup" [(doc)](https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup)), I deleted the "system" one, and it works now.

Somehow I installed the "user setup" version, although I already installed the "system setup". And the "user setup" version of VS Code and the WSL plugin keeps updated (1.64.2). While the "system setup" is not (1.63.2).

**Comment by Eleksar387** [comment]
I was on VS Code 1.65.0 and Remote-WSL 0.64.2. I reverted back to extension version 0.63.2, restarted WSL and it downloaded that version. I then updated again to 0.64.2 and now it works.

**Comment by mindplay-dk** [comment]
I just upgrade to 1.65.0 and got a message saying:

    server.sh is being replaced by 'bin/code-server'. Please migrate to the new command and adopt the following new default behaviors:

(sorry, I didn't copy the rest! I only copied it so I could google it, and now it's gone!)

I then got a dialog with options to retry or ignore.

> A reboot of WSL fixed it for me: `wsl.exe --shutdown`

Thanks, this fixed it for me.

I'm having to do this a lot lately - WSL2 seems to misbehave in a lot of "interesting" ways lately. 😕

**Comment by jdkang** [comment]
Having same issue on
- VS Code `1.65.2` 
- WSL Remote `0.64.2`

It **works** using `Remote Explorer` GUI but get an error when trying to use `code .` from WSL/Ubuntu

the error is:
```
/mnt/c/Users/<USER>/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2/scripts/wslCode.sh: 63: /home/<USER>/.vscode/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/bin/remote-cli/code: not found
```

dir structure:
```
~/.vscode/b/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/bin 
❯ find .
.
./helpers
./helpers/browser.sh
./code
```

clearing out `~/.vscode`  and `~/.vscode-server` and re-bootstrapping the download process does not seem to help.

**Comment by dylanwa** [comment]
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

Having the same issue after VS Code upgrade.
This workaround should be addressed either in product or "WSL2 + VS Code" document.

**Comment by su8ru** [comment]
In short, I solved the problem by reinstalling the VSCode in Windows.
This may be because there were two VSCodes (system and user?). I saw them when uninstalling.
I hope this will be helpful to someone.

**Comment by raelmax** [comment]
I tried all solutions recommended here, and none of them worked.
Right after the WSL reload, the command  `code .` works, but after closing the window and trying the command again, it locked without opening the editor.

**Comment by Weissle** [comment]
Below actions fix my problem while existing solutions don't.
Go to the vscode's extensions market and search the extension ' Remote - WSL '.
If the version of it is range from `0.64.0` to `0.66.0`, install another version. (I install `0.63.12` and it works)
After the installation is successful, reload the vscode. 
Then try to `code .` in the WSL and it will reinstall the vscode.
After that, `code` command can be used normally.
And **Do not** update the ' Remote - WSL ' back to the newest version.

**Comment by jamxe** [comment]
> A reboot of WSL fixed it for me: `wsl.exe --shutdown`

work for me, too.LOL

**Comment by ctsstc** [comment]
Built a new computer, now it's fixed.

**Comment by aeschli** [comment]
Closing the issue. As mentioned it's all related to the one update of the extension that was required when on VS Code Builds >= 1.64

Just make sure you have VS Code Builds >= 1.64 and Remote-WSL >= 0.64.2.

If you are on these versions and still see the problem, please file a new an new issue. Please attach the WSL log (Command: `Remote-WSL: Show Log).

**Comment by heyanurag** [comment]
I was still facing the issue with VSCode v1.67.1 and Remote WSL v0.66.2.

Turning OFF [Fast Refresh](https://support.lenovo.com/gt/en/solutions/ht501793) on Windows does the trick!

**Comment by QzSG** [comment]
> Having same issue on
> 
> * VS Code `1.65.2`
> * WSL Remote `0.64.2`
> 
> It **works** using `Remote Explorer` GUI but get an error when trying to use `code .` from WSL/Ubuntu
> 
> the error is:
> 
> ```
> /mnt/c/Users/<USER>/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2/scripts/wslCode.sh: 63: /home/<USER>/.vscode/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/bin/remote-cli/code: not found
> ```
> 
> dir structure:
> 
> ```
> ~/.vscode/b/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/bin 
> ❯ find .
> .
> ./helpers
> ./helpers/browser.sh
> ./code
> ```
> 
> clearing out `~/.vscode` and `~/.vscode-server` and re-bootstrapping the download process does not seem to help.
> 
> # EDIT: Managed to fix
> 1. In WSL remove ANY `~/.vscode*` folders
> 2. Uninstall Remote WSL from VS Code
> 3. (from elevated powershell) Shutdown wsl (`wsl --shutdown`) -- not sure if this is required.
> 4. Reinstall Remote WSL
> 5. Open `Remote Explorer` and click the folder icon of the **top node** of the WSL instance (e.g. `ubuntu-20.04`). This should open a _new_ VS code window. DO NOT open an existing/cached subfolder.
> 6. Go back to WSL and try to use `code .`

Weirdly enough this works and I can open code from a terminal inside the new wsl vscode window or from the remote explorer. But running Windows Terminal and trying to start code from there still results in 
```.vscode/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/bin/remote-cli/code: not found```

**Comment by surfii3z** [comment]
> It might happen because I installed two setups of VS Code ("system setup" and "user setup" [(doc)](https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup)), I deleted the "system" one, and it works now.
> 
> Somehow I installed the "user setup" version, although I already installed the "system setup". And the "user setup" version of VS Code and the WSL plugin keeps updated (1.64.2). While the "system setup" is not (1.63.2).

I was having the same problem. In my case, when I `code` in WSL terminal will launch code using `/mnt/c/Program Files/Microsoft VS Code/bin/code` path, which gives the same error.

```bash
which -a code
/mnt/c/Program Files/Microsoft VS Code/bin/code  ## system installation
/mnt/c/Users/XXXX/AppData/Local/Programs/Microsoft VS Code/bin/code ## user installation
```

What I did was to alias `code` to another path instead and it solved the problem.

```bash
echo "alias code='/mnt/c/Users/s93286/AppData/Local/Programs/"Microsoft VS Code"/bin/code'" >> ~/.bashrc

source ~/.bashrc
```
