### ISSUE TITLE
"code" command doesnot work on integrated terminal when working on remote server

### ISSUE THREAD

**Issue by gtpooniwala** [microsoft/vscode-remote-release#6350]
Issue Type: <b>Bug</b>

Install "Remote-SSH" extension on VSCode for windows.
Connect to remote server using the extension
Try command "code FileName" in integrated terminal
We get errror that code is not installed. 
This command used to work earlier. 

Extension version: 0.74.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'ssh-remote+azure-personal' could not be established
Remote OS version: Linux x64 5.11.0-1029-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.99GB free)|
|Process Argv|--crash-reporter-id a7d45ade-814a-4ac0-80be-255d222867d1|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+azure-personal' could not be established

|Item|Value|
|---|---|
|Remote|SSH: gcp-common|
|OS|Linux x64 5.11.0-1029-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (4 x 2199)|
|Memory (System)|14.64GB (0.26GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30436279
vsbas813:30436447
vscscmwlcmc:30438804
helixcf:30438807

```

</details>

**Comment by roblourens** [comment]
Do you have the `inheritEnv` terminal setting set?

**Comment by bartMarinissen** [comment]
I got the following error when running `code .` from wsl:

`/mnt/c/Users/marinissenb/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/bart/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found`

I fixed it by open vscode in windows, updating the WSL extension, and reloading vs-code in windows. 

It seems to be related to the binary of the vs-code server being re-named, and the installed WSL extension in windows looking for the old binary name (`code`) instead of the new binary name (`code-server`), but I am just guessing here.

**Comment by gtpooniwala** [comment]
@roblourens changing inheritEnv setting didnot have any effect on the problem

**Comment by gtpooniwala** [comment]
@bartMarinissen That was the exact problem. It got resolved on its own for me.
I initially tried to add the location of the  `code` binary to `PATH` based on https://github.com/microsoft/vscode-remote-release/issues/4451. However, there was no folder/binary named `code` in `~/.vscode-server/bin/*`. I tried deleting the `.vscode-server` folder and reconnecting. It recreated the folder with the same problem. I had given up on the problem and continued with other work. When I reconnected next day, the binary had been downloaded and `code` command is working as intended.

**Comment by huan** [comment]
> I initially tried to add the location of the code binary to PATH based on https://github.com/microsoft/vscode-remote-release/issues/4451. However, there was no folder/binary named code in ~/.vscode-server/bin/*.

@gtpooniwala I have the exact similar problem as you had before, however, it keeps with me for months and today I have not solved this problem yet. :-(

**Comment by gtpooniwala** [comment]
Since posting the previous reply, this problem has reoccurred and sorted itself out automatically again. This seems to be related 
@huan , I will recommend the following-
1. Close all vscode connections to the server
2. ssh to the server with a non vscode terminal
3. Kill any vscode process running on the server
4. Delete the ~/.vscode folder
5. Disconnect ssh
6. Open vscode locally
7. Update to latest version
8. Update Remote WSL and Remote SSH extensions as mentioned by @bartMarinissen (I am not sure how to do this manually. You could try uninstalling and reinstalling them)
9. Connect to the server with the the vscode extension
Please let me know if this helps.

**Comment by gtpooniwala** [comment]
@huan , I will recommend the following-
1. Close all vscode connections to the server
2. ssh to the server with a non vscode terminal
3. Kill any vscode process running on the server
4. Delete the ~/.vscode folder
5. Disconnect ssh
6. Open vscode locally
7. Update to latest version
8. Update Remote WSL and Remote SSH extensions. I am not sure how to do this manually. You could try uninstalling and reinstalling them)
9. Connect to the server with the the vscode extension
Please let me know if this helps.

**Comment by roblourens** [comment]
What is your PATH in a remote vscode terminal?

**Comment by huan** [comment]
@gtpooniwala Thank you very much for those steps! I will try them after I back to my Linux desktop.

@roblourens Will post my PATH in the remote vscode terminal later.

**Comment by huan** [comment]
@gtpooniwala Thank you very much, your steps fixed my problem!

## On SSH Remote Server

```sh
# closed all vscode connections
# killed all vscode related process
$ rm -fr ~/.vscode-server/
```

## On Local Desktop

```sh
$ sudo dpkg -i code_1.65.2-1646927742_amd64.deb 
(Reading database ... 383537 files and directories currently installed.)
Preparing to unpack code_1.65.2-1646927742_amd64.deb ...
Unpacking code (1.65.2-1646927742) over (1.64.0-1643863948) ...
Setting up code (1.65.2-1646927742) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
$ rm -fr ~/.vscode/
# restart vscode
```

**Comment by roblourens** [comment]
@gtpooniwala is this still an issue for you?

**Comment by gtpooniwala** [comment]
No, it is not an issue right now. You can close the issue if you think no other fixes are needed.
