### ISSUE TITLE
Remote SSH not working from Mac connection to Linux

### ISSUE THREAD

**Issue by kschaab** [microsoft/vscode-remote-release#6380]
I'm using remote SSH version v0.70.0.  This stopped working recently and will not work from VS Code release version or insiders.  I'm able to connect to the machine through SSH as expected.  

There seems to be an issue with wget from the channel:
```
[17:06:50.942] > Downloading with wget
[17:06:51.087] > wget download failed
> https://update.code.visualstudio.com/commit:/server-darwin/stable: 2022-02-23 17:06:51 ERROR 404: Not Found.
```

Truncated log (end repeats over and over and then gives up):
```
[17:06:50.387] Log Level: 2
[17:06:50.389] remote-ssh@0.70.0
[17:06:50.389] darwin x64
[17:06:50.390] SSH Resolver called for "ssh-remote+keithsc-glinux.sea.corp.google.com", attempt 1
[17:06:50.390] "remote.SSH.useLocalServer": true
[17:06:50.390] "remote.SSH.path": undefined
[17:06:50.391] "remote.SSH.configFile": undefined
[17:06:50.391] "remote.SSH.useFlock": true
[17:06:50.391] "remote.SSH.lockfilesInTmp": false
[17:06:50.391] "remote.SSH.localServerDownload": auto
[17:06:50.391] "remote.SSH.remoteServerListenOnSocket": false
[17:06:50.391] "remote.SSH.showLoginTerminal": false
[17:06:50.392] "remote.SSH.defaultExtensions": ["googlecloudtools.cloudcode"]
[17:06:50.392] "remote.SSH.loglevel": 2
[17:06:50.392] "remote.SSH.serverPickPortsFromRange": {}
[17:06:50.392] "remote.SSH.enableDynamicForwarding": true
[17:06:50.392] "remote.SSH.serverInstallPath": {}
[17:06:50.393] SSH Resolver called for host: keithsc-glinux.sea.corp.google.com
[17:06:50.394] Setting up SSH remote "keithsc-glinux.sea.corp.google.com"
[17:06:50.396] Acquiring local install lock: /var/folders/kv/nz07yh9j1231p6r73rcg9y9000k3zz/T/vscode-remote-ssh-d701c939-install.lock
[17:06:50.405] Looking for existing server data file at /Users/keithsc/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d701c939-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[17:06:50.407] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[17:06:50.411] Install and start server if needed
[17:06:50.414] PATH: /Users/keithsc/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/keithsc/homebrew/bin:/Users/keithsc/bin/share/darwin:/Users/keithsc/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/keithsc/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/keithsc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/keithsc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/keithsc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/autojump:/Users/keithsc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:/Users/keithsc/.antigen/bundles/desyncr/auto-ls:/Users/keithsc/.antigen/bundles/unixorn/autoupdate-antigen.zshplugin:/Users/keithsc/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/keithsc/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/keithsc/.antigen/bundles/Vifon/deer:/Users/keithsc/.antigen/bundles/romkatv/powerlevel10k
[17:06:50.414] Checking ssh with "ssh -V"
[17:06:50.436] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[17:06:50.441] askpass server listening on /var/folders/kv/nz07yh9j1231p6r73rcg9y9000k3zz/T/vscode-ssh-askpass-da7a46a6e52fd5a8496ae80e5a2e897ee8a0fa61.sock
[17:06:50.442] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/kv/nz07yh9j1231p6r73rcg9y9000k3zz/T/vscode-ssh-askpass-7ad59d06221317e14037c84777760da8e059a96e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","65310","-o","ConnectTimeout=15","keithsc-glinux.sea.corp.google.com"],"dataFilePath":"/Users/keithsc/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d701c939-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[17:06:50.442] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/keithsc/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Users/keithsc/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/keithsc/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/kv/nz07yh9j1231p6r73rcg9y9000k3zz/T/vscode-ssh-askpass-da7a46a6e52fd5a8496ae80e5a2e897ee8a0fa61.sock"}
[17:06:50.443] Spawned 76884
[17:06:50.578] > local-server-1> Spawned ssh, pid=76890
[17:06:50.586] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
[17:06:50.780] > ready: ab799a2fc647
[17:06:50.842] > Linux 5.14.16-1rodete1-amd64 #1 SMP Debian 5.14.16-1rodete1 (2021-11-17)
[17:06:50.842] Platform: linux
[17:06:50.931] stderr> bash: line 9: fail_with_exitcode: command not found
[17:06:50.936] > Installing to ...
[17:06:50.938] stderr> main: line 14: millis: command not found
[17:06:50.938] > ab799a2fc647%%1%%
[17:06:50.942] > Downloading with wget
[17:06:51.087] > wget download failed
> https://update.code.visualstudio.com/commit:/server-darwin/stable: 2022-02-23 17:06:51 ERROR 404: Not Found.
[17:06:51.089] stderr> main: line 34: printenv_indent: command not found
[17:06:51.090] stderr> main: line 36: do_client_download_or_fail: command not found
[17:06:51.090] stderr> main: line 68: millis: command not found
[17:06:51.093] > ab799a2fc647%%2%%
> tar --version:
[17:06:51.096] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[17:06:51.101] stderr> tar: This does not look like a tar archive
[17:06:51.132] stderr> 
[17:06:51.132] stderr> gzip: stdin: unexpected end of file
[17:06:51.133] stderr> tar: Child returned status 1
[17:06:51.133] stderr> tar: Error is not recoverable: exiting now
[17:06:51.139] > ERROR: tar exited with non-0 exit code: 0
> ab799a2fc647%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> ERROR: tar exited with non-0 exit code: 0
> ab799a2fc647%%2%%
> tar --version:
[17:06:51.139] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> ERROR: tar exited with non-0 exit code: 0
> ab799a2fc647%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.

```

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (2 mos ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

Steps to Reproduce:

This is just connect to host through remote-ssh.  Seemed to stop working after reloading the application host.  Have tried restarting VS Code, moving up versions to pre-release as well as moving down versions.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by kschaab** [comment]
Note switching to pre-release version also fixes this issue...

**Comment by tanhakabir** [comment]
Have you tried using the pre-release version of the extension? This error looks slightly different but possibly the same root cause of a fix I had pushed into the pre-release version of the extension.

The original issue in question: https://github.com/microsoft/vscode-remote-release/issues/6341

**Comment by kschaab** [comment]
Yes I just tried that, prerelease version fixed it for a colleague that was having the same issue but not for me.

**Comment by tanhakabir** [comment]
Hmm that's strange. A similar issue to yours with a weird download url: https://github.com/microsoft/vscode-remote-release/issues/6351 was fixed by the fix I had pushed.

I believe the actual error is `bash: line 9: fail_with_exitcode: command not found` where it doesn't seem to be able to resolve a function declared in the same script.

Just to be sure what is your default shell? And this is also broken for you in both versions `0.70` and `0.75.x` (pre-release)?

**Comment by kschaab** [comment]
My default shell is zsh.  Installing prerelease doesn't install 0.75, it is broken in 0.70 and 0.71.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/7329029/155440262-2ad32717-c56f-4471-a5b5-f892830b32a1.png">

I see no option for 0.75.x, maybe that's why it isn't fixed moving to prerelease?

<img width="613" alt="image" src="https://user-images.githubusercontent.com/7329029/155440346-8add34d0-1fd2-4061-a64a-a246b05dcf0a.png">

**Comment by tanhakabir** [comment]
Is your VS Code version up to date? Could you make sure first you can download the extension version `0.74` where it will still be broken and then get version `0.75.x`. This version should work for you

**Comment by kschaab** [comment]
I got the version of .75 in insiders and it does indeed fix the issue.

**Comment by tanhakabir** [comment]
Cool! Closing this issue now. This fix will be out in 0.76 when we release stable along with the VS Code release next week. You'll be able to stop using pre-release if you'd like after `0.76` is out
