### ISSUE TITLE
After VS code  1.72.2 update, remote SSH not working with any of my remote machines.

### ISSUE THREAD

**Issue by santhoshcameo** [microsoft/vscode-remote-release#7441]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.72.2 
- OS Version: Mac OS Monterey, 12.6 (21G115)
- Remote - SSH Version `v0.90.1`
- Detailed info:
         

                    -         Version: 1.72.2 (Universal)
                    -         Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
                    -         Date: 2022-10-12T22:16:30.254Z (2 wks ago)
                    -         Electron: 19.0.17
                    -         Chromium: 102.0.5005.167
                    -         Node.js: 16.14.2
                    -         V8: 10.2.154.15-electron.0
                    -         OS: Darwin x64 21.6.0
                    -         Sandboxed: No

Steps to Reproduce:

1.  I was using 1.65 including remote ssh extension without any issues
2.  received an update requets today and update the vs code
3.  The remote SSH is no more working, but I can ssh into them via terminal as usual, just the remote SSH extension not working

### my settings.json

```
{
    "python.formatting.provider": "black",
    "editor.formatOnSave": true,
    "window.zoomLevel": 2,
    "python.formatting.autopep8Path": "",
    "terminal.integrated.profiles.osx": "/bin/sh",
    "files.autoSave": "afterDelay",
    "remote.SSH.connectTimeout": 60,
    "terminal.integrated.profiles.linux": "/bin/bash",
    "editor.defaultFormatter": "ms-python.python",
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    },
    "debug.allowBreakpointsEverywhere": true,
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "redhat.telemetry.enabled": true,
    "workbench.colorTheme": "Visual Studio Light",
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "remote.extensionKind": {

        "pub.name": [
            "ui"
        ]
    },
    "remote.portsAttributes": {
    

    

    

        "443": {
            "protocol": "https"
        },
        "8443": {
            "protocol": "https"
        }
    },
    "remote.SSH.remoteServerListenOnSocket": true,
    "remote.SSH.useLocalServer": true,
    "remote.autoForwardPorts": false
}
```

### **LOG**

it shows like setting up SSH host:  <ip> initialising VS code server, then i am getting could not establish connection error

```
[00:07:28.606] Log Level: 2
[00:07:28.607] remote-ssh@0.90.1
[00:07:28.607] darwin x64
[00:07:28.611] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 1
[00:07:28.612] "remote.SSH.useLocalServer": false
[00:07:28.612] "remote.SSH.showLoginTerminal": false
[00:07:28.612] "remote.SSH.remotePlatform": {"test-fl-fastapi-dev":"linux"}
[00:07:28.612] "remote.SSH.path": undefined
[00:07:28.612] "remote.SSH.configFile": undefined
[00:07:28.612] "remote.SSH.useFlock": true
[00:07:28.612] "remote.SSH.lockfilesInTmp": false
[00:07:28.613] "remote.SSH.localServerDownload": auto
[00:07:28.613] "remote.SSH.remoteServerListenOnSocket": true
[00:07:28.613] "remote.SSH.showLoginTerminal": false
[00:07:28.613] "remote.SSH.defaultExtensions": []
[00:07:28.613] "remote.SSH.loglevel": 2
[00:07:28.613] "remote.SSH.enableDynamicForwarding": true
[00:07:28.613] "remote.SSH.enableRemoteCommand": false
[00:07:28.613] "remote.SSH.serverPickPortsFromRange": {}
[00:07:28.613] "remote.SSH.serverInstallPath": {}
[00:07:28.622] SSH Resolver called for host: 10.128.129.75
[00:07:28.622] Setting up SSH remote "10.128.129.75"
[00:07:28.625] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:07:28.628] Install and start server if needed
[00:07:30.953] PATH: /opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
[00:07:30.953] Checking ssh with "ssh -V"
[00:07:30.958] > OpenSSH_8.6p1, LibreSSL 3.3.6

[00:07:30.960] Running script with connection command: ssh -T -D 57438 -o ConnectTimeout=60 '10.128.129.75' bash
[00:08:10.465] > client_loop: send disconnect: Broken pipe
[00:08:10.465] Got some output, clearing connection timeout
[00:08:10.676] "install" terminal command done
[00:08:10.677] Install terminal quit with output: client_loop: send disconnect: Broken pipe
[00:08:10.677] Received install output: client_loop: send disconnect: Broken pipe
[00:08:10.678] Failed to parse remote port from server output
[00:08:10.679] Resolver error: Error: 
	at g.Create (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583874)
	at t.tryInstall (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643908
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:08:10.683] ------




[00:08:10.772] ------




[00:08:10.772] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 2, (Reconnection)
[00:08:10.774] SSH Resolver called for host: 10.128.129.75
[00:08:10.774] Setting up SSH remote "10.128.129.75"
[00:08:10.774] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:08:10.778] Install and start server if needed
[00:08:14.479] getPlatformForHost was canceled
[00:08:14.479] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:08:14.481] ------




[00:08:14.507] ------




[00:08:14.507] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 3, (Reconnection)
[00:08:14.508] SSH Resolver called for host: 10.128.129.75
[00:08:14.508] Setting up SSH remote "10.128.129.75"
[00:08:14.509] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:08:14.511] Install and start server if needed
[00:09:57.539] getPlatformForHost was canceled
[00:09:57.540] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:57.541] ------




[00:09:57.544] ------




[00:09:57.544] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 4, (Reconnection)
[00:09:57.545] SSH Resolver called for host: 10.128.129.75
[00:09:57.545] Setting up SSH remote "10.128.129.75"
[00:09:57.546] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:09:57.548] Install and start server if needed
[00:09:58.864] getPlatformForHost was canceled
[00:09:58.864] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:58.865] ------




[00:09:58.868] ------




[00:09:58.868] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 5, (Reconnection)
[00:09:58.869] SSH Resolver called for host: 10.128.129.75
[00:09:58.869] Setting up SSH remote "10.128.129.75"
[00:09:58.869] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:09:58.871] Install and start server if needed
[00:09:59.342] getPlatformForHost was canceled
[00:09:59.342] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:59.343] ------



```

**Comment by grimwm** [comment]
I also have the same issue. It looks like the ssh connection command is different, and I cannot connect to MacOS anymore, which is critical for me.

**Comment by yuGAN6** [comment]
Same issue here! It worked well on my VS code 1.71.0, but failed after updating to 1.73.0

**Comment by santhoshcameo** [comment]
It's a showstopper issue for me as I mostly work with remote & cloud instances.

**Comment by santhoshcameo** [comment]
@schae211 @grimwm @yuGAN6   Is this issue solved for you guys? or found any temporary workaround? Please let me know

**Comment by grimwm** [comment]
> @schae211 @grimwm @yuGAN6   Is this issue solved for you guys? or found any temporary workaround? Please let me know

@santhoshcameo yes, set VSCode to show the terminal when connecting. It changes the command used and improved reliability.

Also, the update I received yesterday changed the way logins work again, and everything is good again. See about updating VSCode first.

**Comment by yuGAN6** [comment]
> @schae211 @grimwm @yuGAN6 Is this issue solved for you guys? or found any temporary workaround? Please let me know

I just downgraded mine to version 1.71.2, and everything works fine.

**Comment by santhoshcameo** [comment]
@grimwm thanks for the response,  how do I set the **_VSCode to show the terminal when connecting._**
 I downloaded the latest platform, but when I try to connect to my remote instance, its asking which platform is your remote instance with linux, windows, mac as options, when I choose one from this, the ssh connection fails...

**Comment by grimwm** [comment]
Sorry, my fix isn't working anymore. You can search the settings for the one that shows the login terminal.

**Comment by eleanorjboyd** [comment]
Does this issue still exist in the newest update of VS Code (1.73.1)? Also what extensions do you have enabled? Finally are you able to connect to your remote locally? For example using the connection string that gets printed here: `[00:07:30.960] Running script with connection command: ssh -T -D 57438 -o ConnectTimeout=60 '10.128.129.75' bash`. Thank you!

**Comment by santhoshcameo** [comment]
@eleanorjboyd thanks for the response, 

- Yes, the version is 1.73.1
- Extensions are: all of them  are from Microsoft
`black formatter, isort, Jupiter,remote-ssh, remote-ssh edit configuration files, remote explorer`

- no the connection string also failing

```
(base) username@vpngate1990 ~ % ssh -T -D 65000 -o ConnectTimeout=60 'gpu-pc' bash                                     
username@ip's password: 
client_loop: send disconnect: Broken pipe
```

but the usual `ssh username@ip` is working as expected

**Comment by eleanorjboyd** [comment]
Hello! Is there a specific reason you set `"remote.SSH.useLocalServer": false`? If you try switching this to true does it work? Also if you try commenting out the remote platform setting, `"remote.SSH.remotePlatform": {"test-fl-fastapi-dev":"linux"}` does that work either? Finally what type of machine is your remote?

**Comment by santhoshcameo** [comment]
Hi @eleanorjboyd  Thanks for the response, the remote machine is OpenStack- Ubuntu 

Tried the options, but did not work,

Please find the settings.json


```
{
    "python.formatting.provider": "black",
    "editor.formatOnSave": true,
    "window.zoomLevel": 2,
    "python.formatting.autopep8Path": "",
    "files.autoSave": "afterDelay",
    "remote.SSH.connectTimeout": 60,
    "editor.defaultFormatter": "ms-python.python",
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    },
    "debug.allowBreakpointsEverywhere": true,
    "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnSave": true
    },
    "redhat.telemetry.enabled": true,
    "workbench.colorTheme": "Visual Studio Light",
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "remote.extensionKind": {
        "pub.name": [
            "ui"
        ]
    },
    "remote.portsAttributes": {

        "443": {
            "protocol": "https"
        },
        "8443": {
            "protocol": "https"
        }
    },
    "remote.SSH.remoteServerListenOnSocket": true,
    "remote.autoForwardPorts": false,
    "remote.SSH.showLoginTerminal": false,
    "remote.SSH.useLocalServer": true,
}
```

**Comment by eleanorjboyd** [comment]
Hello! This should be fixed currently on VS Code insiders. Could you see if it is or the problem you posted persists there?

**Comment by santhoshcameo** [comment]
Hi @eleanorjboyd  Tried the following options, did not work though. 

```
Version: 1.74.0-insider (Universal)
Commit: 3fb8e8feb1c93a490feb2c2259713d4c8f0e0058
Date: 2022-11-14T10:15:28.815Z (12 hrs ago)
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes
```

1. Download the version as you mentioned, without any changes
2. I have only password authentication to that ubuntu server, I can still ssh into that, but remote ssh does not work
3. Then created a public key authentication method,  that also did not solve.

Attached is the log.


```
[23:29:32.526] Log Level: 2
[23:29:32.531] remote-ssh@0.93.2022111115
[23:29:32.531] darwin x64
[23:29:32.537] SSH Resolver called for "ssh-remote+193.174.50.144", attempt 1
[23:29:32.538] "remote.SSH.useLocalServer": true
[23:29:32.538] "remote.SSH.path": undefined
[23:29:32.538] "remote.SSH.configFile": undefined
[23:29:32.538] "remote.SSH.useFlock": true
[23:29:32.539] "remote.SSH.lockfilesInTmp": false
[23:29:32.539] "remote.SSH.localServerDownload": auto
[23:29:32.539] "remote.SSH.remoteServerListenOnSocket": false
[23:29:32.539] "remote.SSH.showLoginTerminal": false
[23:29:32.539] "remote.SSH.defaultExtensions": []
[23:29:32.539] "remote.SSH.loglevel": 2
[23:29:32.539] "remote.SSH.enableDynamicForwarding": true
[23:29:32.540] "remote.SSH.enableRemoteCommand": false
[23:29:32.540] "remote.SSH.serverPickPortsFromRange": {}
[23:29:32.540] "remote.SSH.serverInstallPath": {}
[23:29:32.544] SSH Resolver called for host: 193.174.50.144
[23:29:32.544] Setting up SSH remote "193.174.50.144"
[23:29:32.548] Acquiring local install lock: /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-remote-ssh-f53f0560-install.lock
[23:29:32.550] Looking for existing server data file at /Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json
[23:29:32.551] Using commit id "3fb8e8feb1c93a490feb2c2259713d4c8f0e0058" and quality "insider" for server
[23:29:32.555] Install and start server if needed
[23:29:32.558] PATH: /opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
[23:29:32.558] Checking ssh with "ssh -V"
[23:29:32.566] > OpenSSH_9.0p1, LibreSSL 3.3.6

[23:29:32.570] askpass server listening on /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-1153f7a25608d7a671dfe3038647ed1695e61754.sock
[23:29:32.582] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-c16a6fba3813e25eb0a6b16a0763db5ccd3d9330.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51173","-o","ConnectTimeout=15","193.174.50.144"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json"}
[23:29:32.582] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.LdaLzxkvc6/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.K9OGMM6k7N/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-1153f7a25608d7a671dfe3038647ed1695e61754.sock"}
[23:29:32.583] Spawned 4427
[23:29:32.706] > local-server-1> Spawned ssh, pid=4432
[23:29:32.708] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:29:32.891] stderr> debug1: Server host key: ssh-ed25519 SHA256:qWbbGWhCwTodZw9OuWhXq0KDGvD86s0VZaONVHafWnA
[23:29:33.105] stderr> Authenticated to 193.174.50.144 ([193.174.50.144]:22) using "publickey".
[23:29:49.588] Terminating local server
[23:29:49.592] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:29:49.594] Local server exit: 15
[23:29:49.600] ------




[23:29:49.668] ------




[23:29:49.668] SSH Resolver called for "ssh-remote+193.174.50.144", attempt 2, (Reconnection)
[23:29:49.669] SSH Resolver called for host: 193.174.50.144
[23:29:49.669] Setting up SSH remote "193.174.50.144"
[23:29:49.670] Acquiring local install lock: /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-remote-ssh-f53f0560-install.lock
[23:29:49.671] Looking for existing server data file at /Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json
[23:29:49.671] Using commit id "3fb8e8feb1c93a490feb2c2259713d4c8f0e0058" and quality "insider" for server
[23:29:49.675] Install and start server if needed
[23:29:49.677] askpass server listening on /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-2c699bf8d502f6b6a9940c58dfa05521bb426d42.sock
[23:29:49.678] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-52470b87acd01fbdc14059381c7baa638a717899.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51184","-o","ConnectTimeout=15","193.174.50.144"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json"}
[23:29:49.678] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.LdaLzxkvc6/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.K9OGMM6k7N/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-2c699bf8d502f6b6a9940c58dfa05521bb426d42.sock"}
[23:29:49.679] Spawned 4434
[23:29:49.807] > local-server-2> Spawned ssh, pid=4439
[23:29:49.810] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:29:49.992] stderr> debug1: Server host key: ssh-ed25519 SHA256:qWbbGWhCwTodZw9OuWhXq0KDGvD86s0VZaONVHafWnA
[23:29:50.250] stderr> Authenticated to 193.174.50.144 ([193.174.50.144]:22) using "publickey".
[23:30:06.681] Terminating local server
[23:30:06.682] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:30:06.685] ------




[23:30:06.686] Local server exit: 15
[23:30:06.717] ------




[23:30:06.717] SSH Resolver called for "ssh-remote+193.174.50.144", attempt 3, (Reconnection)
[23:30:06.718] SSH Resolver called for host: 193.174.50.144
[23:30:06.718] Setting up SSH remote "193.174.50.144"
[23:30:06.719] Acquiring local install lock: /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-remote-ssh-f53f0560-install.lock
[23:30:06.719] Looking for existing server data file at /Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json
[23:30:06.719] Using commit id "3fb8e8feb1c93a490feb2c2259713d4c8f0e0058" and quality "insider" for server
[23:30:06.721] Install and start server if needed
[23:30:06.724] askpass server listening on /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-d8ea66f067c815e0416bf78c4c6997e59b4fef7b.sock
[23:30:06.724] Spawning local server with {"serverId":3,"ipcHandlePath":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-47a07e8502b9797d9d84626e6f27a0583df26ebb.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51189","-o","ConnectTimeout=15","193.174.50.144"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json"}
[23:30:06.724] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.LdaLzxkvc6/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.K9OGMM6k7N/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-d8ea66f067c815e0416bf78c4c6997e59b4fef7b.sock"}
[23:30:06.725] Spawned 4447
[23:30:06.855] > local-server-3> Spawned ssh, pid=4452
[23:30:06.857] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:30:07.042] stderr> debug1: Server host key: ssh-ed25519 SHA256:qWbbGWhCwTodZw9OuWhXq0KDGvD86s0VZaONVHafWnA
[23:30:07.303] stderr> Authenticated to 193.174.50.144 ([193.174.50.144]:22) using "publickey".
[23:30:23.729] Terminating local server
[23:30:23.731] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:30:23.733] ------




[23:30:23.734] ------




[23:30:23.734] SSH Resolver called for "ssh-remote+193.174.50.144", attempt 4, (Reconnection)
[23:30:23.735] Local server exit: 15
[23:30:23.736] SSH Resolver called for host: 193.174.50.144
[23:30:23.736] Setting up SSH remote "193.174.50.144"
[23:30:23.737] Acquiring local install lock: /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-remote-ssh-f53f0560-install.lock
[23:30:23.737] Looking for existing server data file at /Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json
[23:30:23.738] Using commit id "3fb8e8feb1c93a490feb2c2259713d4c8f0e0058" and quality "insider" for server
[23:30:23.739] Install and start server if needed
[23:30:23.743] askpass server listening on /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-6ece0be1c3cd9824f7ca8dcec1726d8ead1d0334.sock
[23:30:23.743] Spawning local server with {"serverId":4,"ipcHandlePath":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-24bffb3a94d0aaf1ca854b824a0d4ee60e58a576.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51195","-o","ConnectTimeout=15","193.174.50.144"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json"}
[23:30:23.743] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.LdaLzxkvc6/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.K9OGMM6k7N/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-6ece0be1c3cd9824f7ca8dcec1726d8ead1d0334.sock"}
[23:30:23.744] Spawned 4453
[23:30:23.879] > local-server-4> Spawned ssh, pid=4458
[23:30:23.881] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:30:24.093] stderr> debug1: Server host key: ssh-ed25519 SHA256:qWbbGWhCwTodZw9OuWhXq0KDGvD86s0VZaONVHafWnA
[23:30:24.353] stderr> Authenticated to 193.174.50.144 ([193.174.50.144]:22) using "publickey".
[23:30:40.750] Terminating local server
[23:30:40.751] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:30:40.753] ------




[23:30:40.755] Local server exit: 15
[23:30:40.789] ------




[23:30:40.789] SSH Resolver called for "ssh-remote+193.174.50.144", attempt 5, (Reconnection)
[23:30:40.790] SSH Resolver called for host: 193.174.50.144
[23:30:40.790] Setting up SSH remote "193.174.50.144"
[23:30:40.791] Acquiring local install lock: /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-remote-ssh-f53f0560-install.lock
[23:30:40.791] Looking for existing server data file at /Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json
[23:30:40.791] Using commit id "3fb8e8feb1c93a490feb2c2259713d4c8f0e0058" and quality "insider" for server
[23:30:40.793] Install and start server if needed
[23:30:40.795] askpass server listening on /var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-88b90fd0e534d61f7d72b66177bba3509969cc74.sock
[23:30:40.796] Spawning local server with {"serverId":5,"ipcHandlePath":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-0b012d1b6ad5b0b0d67d74463555a610dbe26626.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51199","-o","ConnectTimeout=15","193.174.50.144"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/e230-admin/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f53f0560-3fb8e8feb1c93a490feb2c2259713d4c8f0e0058-0.93.2022111115/data.json"}
[23:30:40.796] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.LdaLzxkvc6/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.K9OGMM6k7N/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y8/7bmvcf5j0n399csq_rzbrlcw0000gq/T/vscode-ssh-askpass-88b90fd0e534d61f7d72b66177bba3509969cc74.sock"}
[23:30:40.797] Spawned 4460
[23:30:40.919] > local-server-5> Spawned ssh, pid=4465
[23:30:40.921] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:30:41.097] stderr> debug1: Server host key: ssh-ed25519 SHA256:qWbbGWhCwTodZw9OuWhXq0KDGvD86s0VZaONVHafWnA
[23:30:41.360] stderr> Authenticated to 193.174.50.144 ([193.174.50.144]:22) using "publickey".
[23:30:57.802] Terminating local server
[23:30:57.803] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/e230-admin/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:30:57.806] ------




[23:30:57.807] Local server exit: 15
```

**Comment by eleanorjboyd** [comment]
Hi @santhoshcameo - so it seems like the connection string for SSH is not working both with and without VS Code. Due to this reasoning, it would be best if you can try and make the string `ssh -T -D 57438 -o ConnectTimeout=60 '10.128.129.75' bash` work by removing different sections of the connection command to determine which section is not allowing the connection to work correctly. You can do this in a local terminal and not in VS Code because this seems to be a general SSH issue and not specific to VS Code. Give that a try and let me know if you can identify a section of the connection string responsible for the erroring.

**Comment by santhoshcameo** [comment]
@eleanorjboyd 

The VS code generated command is 

```
ssh  -v -T -D 51061  -i san-delete.pem ubuntu@ec2-18-197-143-208.eu-central-1.compute.amazonaws.com 
which does NOT work. its log is below
```
**LOG**
```
(base) e230-admin@san ~ % ssh  -v -T -D 51061  -i san-delete.pem ubuntu@ec2-18-197-143-208.eu-central-1.compute.amazonaws.com     
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/e230-admin/.ssh/config
debug1: /Users/e230-admin/.ssh/config line 1: Applying options for ec2-18-197-143-208.eu-central-1.compute.amazonaws.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to ec2-18-197-143-208.eu-central-1.compute.amazonaws.com port 22.
debug1: Connection established.
debug1: identity file san-delete.pem type -1
debug1: identity file san-delete.pem-cert type -1
debug1: identity file /Users/e230-admin/san-delete.pem type -1
debug1: identity file /Users/e230-admin/san-delete.pem-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3
debug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to ec2-18-197-143-208.eu-central-1.compute.amazonaws.com:22 as 'ubuntu'
debug1: load_hostkeys: fopen /Users/e230-admin/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:toTeRJJvUKxLdAhKaf7+r5YAGyr3mMG61A/7SM4NUUQ
debug1: load_hostkeys: fopen /Users/e230-admin/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'ec2-18-197-143-208.eu-central-1.compute.amazonaws.com' is known and matches the ED25519 host key.
debug1: Found key in /Users/e230-admin/.ssh/known_hosts:169
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
debug1: Will attempt key: san-delete.pem  explicit
debug1: Will attempt key: /Users/e230-admin/san-delete.pem  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: san-delete.pem
Authenticated to ec2-18-197-143-208.eu-central-1.compute.amazonaws.com ([18.197.143.208]:22) using "publickey".
debug1: Local connections to LOCALHOST:51061 forwarded to remote address socks:0
debug1: Local forwarding listening on 127.0.0.1 port 51061.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on ::1 port 51061.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching /Users/e230-admin/.ssh/known_hosts for ec2-18-197-143-208.eu-central-1.compute.amazonaws.com / (none)
debug1: client_input_hostkeys: searching /Users/e230-admin/.ssh/known_hosts2 for ec2-18-197-143-208.eu-central-1.compute.amazonaws.com / (none)
debug1: client_input_hostkeys: hostkeys file /Users/e230-admin/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: no new or deprecated keys from server
debug1: Remote: /home/ubuntu/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Sending environment.
debug1: channel 2: setting env LC_CTYPE = "UTF-8"
client_loop: send disconnect: Broken pipe
```

- **The below command works**

As you suggested, Tried the below one via terminal, **which works and I am able to login**, the big difference I can see here is `-T parameter `

`ssh  -v  -D 51061  ec2-18-197-143-208.eu-central-1.compute.amazonaws.com`

**Comment by santhoshcameo** [comment]
another thread on this.

[https://github.com/microsoft/vscode-remote-release/issues/5439](https://github.com/microsoft/vscode-remote-release/issues/5439)

**Comment by eleanorjboyd** [comment]
Hello @santhoshcameo, I have created an issue about allowing the -T parameter to be configurable which would be the solution to your problem. Here is the issue which will be updated with the feature progress. https://github.com/microsoft/vscode-remote-release/issues/7558
