### ISSUE TITLE
Add Configurable -T Parameter for Remote-SSH

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7558]
Add an additional setting so the user can specify if they want to include the -T command in the connection string that is run by the extension. This parameter is necessary for many people but does cause issues for others so configurability is the best solution.

**Comment by eleanorjboyd** [comment]
recommendation by @schiffy91 in https://github.com/microsoft/vscode-remote-release/issues/7673

> Given this seems to be experienced by multiple users, I think a robust solution would be for the client to try with 'T'; if it fails, try again without 'T'. I don't think there needs to be a setting to enable/disable as much as this setting seems to have pretty weird implementations on different distributions of SSH.

**Comment by eleanorjboyd** [comment]
issue reported here: https://github.com/microsoft/vscode-remote-release/issues/8063

**Comment by davidpasqua-asml** [comment]
> 

Thank you, but I guess any advanced user will prefer to have the option to configure any ssh parameter (could be more needed depending on a number of factors)
losing extra time trying extra parameters doesn't do any good for the overall usage of any application

**Comment by eleanorjboyd** [comment]
@davidpasqua-asml, some of the ssh parameters interfere with our install script, are there any ssh parameters, in particular, you want configurable?

**Comment by sluc23** [comment]
any update on this issue? I'm facing same problem, unable to connect to Debian host with `-T` parameter

**Comment by eleanorjboyd** [comment]
No sorry, the issue will be tagged by our iteration plan issue when it does go into our monthly plan so once you see that then you know it is being worked on. Thanks!

**Comment by eleanorjboyd** [comment]
@roblourens, can answer this question? Thanks!

**Comment by tanminhan0** [comment]
I got this issue and couldn't connect remote ssh to my raspberrypi.local and I could connect from puTTy, somehow when I tried to use the extension to remote connect ssh to the raspberrypi it couldn't establish a connection and I tried it again it spammed out Waiting for server logs... and still failed connection. I tried the way I connect the remote from the terminal using ssh -v -T -D 56207 -o ConnectTimeout=30 raspberrypi.local without -T parameter is connecting in the terminal but I would like to connect with the extension so that I could show the code and edit the code in the VSCode, do you have any idea how could I fix it @eleanorjboyd

**Comment by eleanorjboyd** [comment]
@tanminhan0 can you please create a new bug report? Then we can answer it from there, thanks

**Comment by KegangWangCCNU** [comment]
I encountered the same problem, which is due to vscode creating a configuration file when first connecting to a remote computer, and the operating system in the configuration file may be incorrect. For example, when I connected to a Windows host, it created a Linux configuration file. By correcting the operating system in remote.SSH.remotePlatform, all problems were solved.

**Comment by on1ytampax** [comment]
@eleanorjboyd @roblourens Hello, I'm also having this issue when i can't connect to remote server via ssh with -T parameter. I tried to use "RequestTTY force" option in ssh config, but this option doesn't override -T parameter. Right now i have no workaround, so this issue is very critical for me. Please, help :)

**Comment by DuMoH112** [comment]
I also have this problem when connecting to vs code server on mac os. We will wait for the start of work on the task)

**Comment by thundercarrot** [comment]
I'm seeing the same problem going from Windows to Windows. I was able to work around it by specifying a RemoteCommand for the connection that starts a shell. I guess that defeats -T?
```
    "remote.SSH.useLocalServer": true,
    "remote.SSH.enableRemoteCommand": true,
```
and then in the .ssh config file:

```
Host xxxx
  HostName xxxx
  Port xxx
  User xxx
  RemoteCommand cmd.exe
```

**Comment by asmith22** [comment]
> @davidpasqua-asml, some of the ssh parameters interfere with our install script, are there any ssh parameters, in particular, you want configurable?

I think is relevant to an unrelated issue I have with X11 forwarding through the VSCode RemoteSSH integrated terminal, we need -X and have tried  
  ForwardX11 yes
  ForwardX11Trusted yes
  ForwardAgent yes
  
but still get "-v -T -D 57353 -o ConnectTimeout=15 <user>@<host>" as the ssh comment in the output window.

**Comment by zaunere** [comment]
FWIW, I saw this issue related to an older server and newer VSCode.  It seems to related to the resolution of avoiding to enter your password multiple times.

On an old server, Insider persisted with the opening log error, regardless of deleting existing .vscode* directories.  
Without Insider, it works but requires the password multiple times (old behavior).

OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
Linux123.com 4.14.214-160.339.amzn2.x86_64 #1 SMP Sun Jan 10 05:53:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mcwindy** [comment]
> I'm seeing the same problem going from Windows to Windows. I was able to work around it by specifying a RemoteCommand for the connection that starts a shell. I guess that defeats -T?
> 
> ```
>     "remote.SSH.useLocalServer": true,
>     "remote.SSH.enableRemoteCommand": true,
> ```
> 
> and then in the .ssh config file:
> 
> ```
> Host xxxx
>   HostName xxxx
>   Port xxx
>   User xxx
>   RemoteCommand cmd.exe
> ```

This worked for me, except for that i need to enter my password twice.

**Comment by MianWang123** [comment]
> I also have this problem when connecting to vs code server on mac os. We will wait for the start of work on the task)

+1

**Comment by maxencefaldor** [comment]
Any update on this @eleanorjboyd?

I encounter the same issue. The command being run by VSCode is `ssh -v -T -D 58077 -o ConnectTimeout=15 remote`

For me, it is crucial to be able to connect to `remote` and then execute a command with:
```
Host remote
        HostName ...
        User ...
        RemoteCommand <command that starts an interactive shell>
        RequestTTY yes
```

However, the option `-T` prevents the interactive shell to start and the connection fails.
When I run manually `ssh -v -D 58077 -o ConnectTimeout=15 remote` without `-T`, it works fine.

- Does someone know of any workaround?
- Do you plan to give configurability for the `-T` option?

Thanks!

**Comment by joshspicer** [comment]
👋 Pre-release version `v0.113.2024071915` ships with a new option `Remote.SSH: Permit Pty Allocation
` that omits the `-T` flag.  Please let me know here if this helps or if there's any other relevant feedback!

![Image](https://github.com/user-attachments/assets/12c80a5d-35f3-4a4a-96fc-41a9955a2057)
