### ISSUE TITLE
Error building devcontainer with default Node profile

### ISSUE THREAD

**Issue by shbatm** [microsoft/vscode-remote-release#7854]
Just hit this myself using the default generated `devcontainer.json` without a Dockerfile

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/typescript-node
{
	"name": "Node.js & TypeScript",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/typescript-node:0-18",
	"features": {
		"ghcr.io/devcontainers/features/git-lfs:1": {}
	}

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

```
[2023-01-10T15:52:33.840Z] * Processing feature: ghcr.io/devcontainers/features/git-lfs:1
[2023-01-10T15:52:33.841Z] No authentication credentials found for registry 'ghcr.io'.
[2023-01-10T15:52:33.841Z] No authentication credentials found for registry 'ghcr.io'.
[2023-01-10T15:52:34.245Z] * Fetching feature: git-lfs_1_oci
[2023-01-10T15:52:34.247Z] No authentication credentials found for registry 'ghcr.io'.
[2023-01-10T15:52:34.247Z] No authentication credentials found for registry 'ghcr.io'.
[2023-01-10T15:52:34.620Z] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1673365953781 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pricey-f7328750c5899a199e56d06dd6cc1165-features -f /tmp/devcontainercli-root/container-features/0.26.0-1673365953781/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[2023-01-10T15:52:34.866Z] 
[2023-01-10T15:52:34.866Z] [+] Building 0.0s (0/0)                                                         
[2023-01-10T15:52:34.967Z] [+] Building 0.0s (0/1)                                                         
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 39B                                        0.0s
[2023-01-10T15:52:35.103Z] [+] Building 0.2s (2/3)                                                         
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 1.56kB                                     0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
[2023-01-10T15:52:35.103Z]  => resolve image config for docker.io/docker/dockerfile:1.4               0.0s
[2023-01-10T15:52:35.253Z] [+] Building 0.3s (2/3)                                                         
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 1.56kB                                     0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.2s
[2023-01-10T15:52:35.257Z] Container server: {
  message: 'write EPIPE',
  name: 'Error',
  stack: 'Error: write EPIPE\n' +
    '\tat afterWriteDispatched (node:internal/stream_base_commons:160:15)\n' +
    '\tat writeGeneric (node:internal/stream_base_commons:151:3)\n' +
    '\tat Socket._writeGeneric (node:net:795:11)\n' +
    '\tat Socket._write (node:net:807:8)\n' +
    '\tat writeOrBuffer (node:internal/streams/writable:389:12)\n' +
    '\tat _write (node:internal/streams/writable:330:10)\n' +
    '\tat Writable.write (node:internal/streams/writable:334:10)\n' +
    '\tat c:\\Users\\andyk\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.269.0\\dist\\extension\\extension.js:87:219\n' +
    '\tat new Promise (<anonymous>)\n' +
    '\tat Fe (c:\\Users\\andyk\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.269.0\\dist\\extension\\extension.js:86:1504)\n' +
    '\tat async vk (c:\\Users\\andyk\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.269.0\\dist\\extension\\extension.js:67:709)\n' +
    '\tat async yk (c:\\Users\\andyk\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.269.0\\dist\\extension\\extension.js:67:79)\n' +
    '\tat async Object.rpc (c:\\Users\\andyk\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.269.0\\dist\\extension\\extension.js:83:901)'
}
[2023-01-10T15:52:35.277Z] [+] Building 0.3s (3/3) FINISHED                                                
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 1.56kB                                     0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile:1.4         0.2s
------
 > resolve image config for docker.io/docker/dockerfile:1.4:
[2023-01-10T15:52:35.278Z] ------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: exit status 255, out: ``
[2023-01-10T15:52:35.282Z] Stop (662 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1673365953781 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pricey-f7328750c5899a199e56d06dd6cc1165-features -f /tmp/devcontainercli-root/container-features/0.26.0-1673365953781/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[2023-01-10T15:52:35.283Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1673365953781 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pricey-f7328750c5899a199e56d06dd6cc1165-features -f /tmp/devcontainercli-root/container-features/0.26.0-1673365953781/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[2023-01-10T15:52:35.283Z]     at Kne (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1865:1355)
[2023-01-10T15:52:35.283Z]     at x7 (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1865:1291)
[2023-01-10T15:52:35.283Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-10T15:52:35.283Z]     at async oie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1871:2093)
[2023-01-10T15:52:35.283Z]     at async qf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1871:3239)
[2023-01-10T15:52:35.283Z]     at async Mse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1995:16211)
[2023-01-10T15:52:35.283Z]     at async Lse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js:1995:15965)
[2023-01-10T15:52:35.318Z] Stop (2683 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/pricey --workspace-mount-consistency cached --id-label vsch.local.repository=git@github.com:kutruff/pricey.git --id-label vsch.local.repository.volume=pricey --id-label vsch.local.repository.folder=pricey --log-level debug --log-format json --config /workspaces/pricey/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-c17cc4e0-2474-4147-8001-cedbfde366de.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=pricey,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2023-01-10T15:52:35.318Z] Exit code 1
[2023-01-10T15:52:35.318Z] Start: Run: docker rm -f 7b02b4bc040ff78533b9d8415090be181fca5dac153976f433ad5bdd059ff4f6
[2023-01-10T15:52:35.322Z] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.269.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/pricey --workspace-mount-consistency cached --id-label vsch.local.repository=git@github.com:kutruff/pricey.git --id-label vsch.local.repository.volume=pricey --id-label vsch.local.repository.folder=pricey --log-level debug --log-format json --config /workspaces/pricey/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-c17cc4e0-2474-4147-8001-cedbfde366de.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=pricey,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2023-01-10T15:52:35.323Z] Exit code 1
[2023-01-10T15:52:35.521Z] Stop (5283 ms): Run in container: /bin/sh
[2023-01-10T15:52:35.536Z] Stop (5036 ms): Run in container: /bin/sh
[2023-01-10T15:52:35.536Z] Container server terminated (code: 137, signal: null).
[2023-01-10T15:52:35.909Z] Stop (591 ms): Run: docker rm -f 7b02b4bc040ff78533b9d8415090be181fca5dac153976f433ad5bdd059ff4f6
[2023-01-10T15:52:55.504Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-01-10T15:52:55.703Z] Stop (199 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-01-10T15:52:55.704Z] 1.41

```

_Originally posted by @akutruff in https://github.com/microsoft/vscode-remote-release/issues/7319#issuecomment-1377480373_

**Comment by shbatm** [comment]
I'm hitting this too, similar setup to above. Tried logging in and out of Docker Hub with no change, tried restarting docker, vs-code, and computer with no change.

**Comment by bamurtaugh** [comment]
Thanks for reporting. I think this may have been a fleeting issue - are you still experiencing it?

**Comment by shbatm** [comment]
I ran into it again 2 days ago.

A `docker pull docker.io/docker/dockerfile:1.4` from a separate WSL terminal worked fine and then no errors when reloading the window.

**Comment by chrmarti** [comment]
Fix is available in Dev Containers 0.273.0-pre-release. Thanks.

**Comment by rio** [comment]
@chrmarti, there's no way to update to that version since the vscode engine compatibility constraint is set to ^1.75.0. Downgrading also doesn't seem to help.

**Comment by chrmarti** [comment]
@rio Indeed, you need to install VS Code Insiders for now to get the latest version: https://code.visualstudio.com/insiders/

VS Code 1.75 is expect next week, so you could also wait for that.

**Comment by caseybarker** [comment]
I'm still seeing a similar error in v0.276.0 Pre-Release of Dev Containers:
```
[40207 ms] Container server: {
  message: 'write EPIPE',
  name: 'Error',
  stack: 'Error: write EPIPE\n' +
    '\tat afterWriteDispatched (node:internal/stream_base_commons:160:15)\n' +
    '\tat writeGeneric (node:internal/stream_base_commons:151:3)\n' +
    '\tat Socket._writeGeneric (node:net:795:11)\n' +
    '\tat Socket._write (node:net:807:8)\n' +
    '\tat writeOrBuffer (node:internal/streams/writable:389:12)\n' +
    '\tat _write (node:internal/streams/writable:330:10)\n' +
    '\tat Writable.write (node:internal/streams/writable:334:10)\n' +
    '\tat /home/casey/.vscode/extensions/ms-vscode-remote.remote-containers-0.276.0/dist/extension/extension.js:87:219\n' +
    '\tat new Promise (<anonymous>)\n' +
    '\tat Ae (/home/casey/.vscode/extensions/ms-vscode-remote.remote-containers-0.276.0/dist/extension/extension.js:86:1504)\n' +
    '\tat async _A (/home/casey/.vscode/extensions/ms-vscode-remote.remote-containers-0.276.0/dist/extension/extension.js:67:709)\n' +
    '\tat async SA (/home/casey/.vscode/extensions/ms-vscode-remote.remote-containers-0.276.0/dist/extension/extension.js:67:79)\n' +
    '\tat async Object.rpc (/home/casey/.vscode/extensions/ms-vscode-remote.remote-containers-0.276.0/dist/extension/extension.js:83:901)'
}

**Comment by schlich** [comment]
I was also running into this issue using the Python base devcontainer, fixed with `docker pull docker.io/docker/dockerfile:1.4` as suggested above

**Comment by chrmarti** [comment]
Following up with @caseybarker in https://github.com/microsoft/vscode-remote-release/issues/7979.
