### ISSUE TITLE
Unable to connect to VS Code Remote on VS Code Insiders

### ISSUE THREAD

**Issue by Aholicknight** [microsoft/vscode-remote-release#8552]
- VSCode Version: 1.79.0-insider (same version on local and remote)
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: Windows_NT x64 10.0.22621
- Remote Extension/Connection Type: Server

- Logs:
```
2023-05-30 10:44:33.678 [info] Found running server in \\.\pipe\vscode-tunneling-0f59920f75b0f9d1-sock
2023-05-30 10:44:33.697 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:44:33.697 [info] Creating new tunnel proxy server
2023-05-30 10:44:42.544 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:44:42.545 [info] Remote resolution completed
2023-05-30 10:44:43.985 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:44:44.084 [info] [proxy] Tunnel connection successful
2023-05-30 10:44:44.193 [info] Resolving tunnel+aholicknight...
2023-05-30 10:44:44.202 [info] Found running server in \\.\pipe\vscode-tunneling-857a2cca9a98b3aa-sock
2023-05-30 10:44:44.221 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:44:44.221 [info] Creating new tunnel proxy server
2023-05-30 10:44:44.990 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:44:44.992 [info] Remote resolution completed
2023-05-30 10:44:46.525 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:44:46.626 [info] [proxy] Tunnel connection successful
2023-05-30 10:44:46.740 [info] Resolving tunnel+aholicknight...
2023-05-30 10:44:46.748 [info] Found running server in \\.\pipe\vscode-tunneling-2c1b831bc6adaa66-sock
2023-05-30 10:44:46.769 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:44:46.769 [info] Creating new tunnel proxy server
2023-05-30 10:44:47.501 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:44:47.502 [info] Remote resolution completed
2023-05-30 10:44:49.405 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:44:49.507 [info] [proxy] Tunnel connection successful
2023-05-30 10:44:49.634 [info] Resolving tunnel+aholicknight...
2023-05-30 10:44:49.645 [info] Found running server in \\.\pipe\vscode-tunneling-e58eb825e26b0837-sock
2023-05-30 10:44:49.664 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:44:49.664 [info] Creating new tunnel proxy server
2023-05-30 10:44:50.414 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:44:50.415 [info] Remote resolution completed
2023-05-30 10:44:51.976 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:44:52.076 [info] [proxy] Tunnel connection successful
2023-05-30 10:44:52.348 [info] [proxy] [connection.1] tunnel connection established
2023-05-30 10:52:26.440 [info] Resolving tunnel+aholicknight...
2023-05-30 10:52:26.459 [info] Creating new tunnel proxy server
2023-05-30 10:52:27.650 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:52:27.650 [info] Remote resolution completed
2023-05-30 10:52:29.768 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:52:30.139 [info] [proxy] Tunnel connection successful
2023-05-30 10:52:30.445 [info] Resolving tunnel+aholicknight...
2023-05-30 10:52:30.456 [info] Found running server in \\.\pipe\vscode-tunneling-3a1ee55a5f00eb24-sock
2023-05-30 10:52:30.474 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:52:30.474 [info] Creating new tunnel proxy server
2023-05-30 10:52:31.232 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:52:31.233 [info] Remote resolution completed
2023-05-30 10:52:32.730 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:52:33.461 [info] [proxy] Tunnel connection successful
2023-05-30 10:52:33.827 [info] Resolving tunnel+aholicknight...
2023-05-30 10:52:33.837 [info] Found running server in \\.\pipe\vscode-tunneling-bc3512a687069ff6-sock
2023-05-30 10:52:33.854 [info] Error greeting the server, starting a new instance (Error: Connection closed)
2023-05-30 10:52:33.854 [info] Creating new tunnel proxy server
2023-05-30 10:52:34.689 [info] [proxy] Found tunnel (ID=zg0jb9cm, Cluster=use)
2023-05-30 10:52:34.691 [info] Remote resolution completed
2023-05-30 10:52:38.105 [info] [proxy] [connection.0] tunnel connection established
2023-05-30 10:52:38.597 [info] [proxy] Tunnel connection successful
2023-05-30 10:52:39.411 [info] Resolving tunnel+aholicknight...
2023-05-30 10:52:39.421 [info] Found running server in \\.\pipe\vscode-tunneling-ff7b99150da0cc8f-sock
2023-05-30 10:52:39.438 [info] Error greeting the server, starting a new instance (Error: Connection closed)
```
Steps to Reproduce:

1. Install the latest version of VS Code Insiders
2. Remote into your VS Code Insiders
3. You will get the error `Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused: auth mismatch)`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Thanks for filing. Just to double check, are you using the Remote Tunnels extension? Or Remote SSH?

**Comment by bamurtaugh** [comment]
Looks like this may be the same as https://github.com/microsoft/vscode-remote-release/issues/8555.

**Comment by connor4312** [comment]
Thanks for the issue! This should be fixed on today's Insiders already (note: you'll want to update VS Code / the CLI on the host machine). Please let me know if you continue to experience problems.

**Comment by Aholicknight** [comment]
> Thanks for the issue! This should be fixed on today's Insiders already (note: you'll want to update VS Code / the CLI on the host machine). Please let me know if you continue to experience problems.

@connor4312 Ah so that's what the new update is. I will update on my local and remote computer, and see if the problem is resolved.

**Comment by Aholicknight** [comment]
> Thanks for filing. Just to double check, are you using the Remote Tunnels extension? Or Remote SSH?

@bamurtaugh Sorry I forgot to answer your question. I am using Remote Tunnels, not Remote SSH.

**Comment by Aholicknight** [comment]
![msedge_20230601_TzNc7SkGMu](https://github.com/microsoft/vscode-remote-release/assets/7843719/851fef2c-acd2-46c6-a2d9-987a5c5a77e7)

This is still not working for some reason. I tested with a virtual machine as the remote and my local computer. I do not know why this is still happening.

**Comment by Aholicknight** [comment]
![msedge_20230601_oDf9neKAJ3](https://github.com/microsoft/vscode-remote-release/assets/7843719/50da2d11-6474-4f41-9ab2-a593db1d9589)

For some reason it does work on the website version lol
