### ISSUE TITLE
Sharing Git credentials with your container - ssh-agent forwarding to Windows instead of WSL

### ISSUE THREAD

**Issue by pedrodaniel10** [microsoft/vscode-remote-release#8803]
- VSCode Version
```
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
```
- Local OS Version: Windows 10 Version 21H2 (OS Build 19044.3208)
- Remote OS Version: mcr.microsoft.com/devcontainers/typescript-node:18
- Remote Extension/Connection Type: Containers

Steps to Reproduce:
I am following [Sharing Git credentials with your container](https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials) documentation so I can use the VSCode source control features and the Gitlab Workflow extension. 
However I always get the following message:
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I found a similar issue in #6395 and #8689.

My settings have `Execute in WSL` on. Also the folder is currently in WSL.
![image](https://github.com/microsoft/vscode-remote-release/assets/16168631/fe3740fb-35cc-47a7-8cc5-0c3b1c1bb37d)

After some debugging, I am pretty sure that it's using Window's SSH Agent instead of WSL's. When I have 

```
PS C:\Windows\system32> Get-Service ssh-agent                                                                                                                                                                                                   Status   Name               DisplayName                                                                                 
------   ----               -----------                                                                                 
Stopped  ssh-agent          OpenSSH Authentication Agent     
```

I get the following error in logs:

```
[2023-08-04T20:17:44.154Z] Container server: Remote to local stream terminated with error: {
  message: 'connect ENOENT \\\\.\\pipe\\openssh-ssh-agent',
  name: 'Error',
  stack: 'Error: connect ENOENT \\\\.\\pipe\\openssh-ssh-agent\n' +
    '    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)'
}
```

The error does not occur when the service is on. Meaning it's using Window's `ssh-agent` instead of WSL's.
Despite that, I also added the private key through `ssh-agent` on Windows. But git still does not work. (certificate is named `id_rsa`)
It is listed when I run `ssh-agent -l` (on Windows and on WSL)

```
node ➜ /workspace (refactor) $ GIT_SSH_COMMAND="ssh -v" git pull
OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.9 30 May 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to <REDACTED_HOSTNAME> [<REDACTED_IP>] port 22.
debug1: Connection established.
debug1: identity file /home/node/.ssh/id_rsa type -1
debug1: identity file /home/node/.ssh/id_rsa-cert type -1
debug1: identity file /home/node/.ssh/id_ecdsa type -1
debug1: identity file /home/node/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/node/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/node/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/node/.ssh/id_ed25519 type -1
debug1: identity file /home/node/.ssh/id_ed25519-cert type -1
debug1: identity file /home/node/.ssh/id_ed25519_sk type -1
debug1: identity file /home/node/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/node/.ssh/id_xmss type -1
debug1: identity file /home/node/.ssh/id_xmss-cert type -1
debug1: identity file /home/node/.ssh/id_dsa type -1
debug1: identity file /home/node/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.2p1 Debian-2
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.8
debug1: compat_banner: match: OpenSSH_8.8 pat OpenSSH* compat 0x04000000
debug1: Authenticating to <REDACTED_HOSTNAME>:22 as 'git'
debug1: load_hostkeys: fopen /home/node/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:<REDACTED_HASH>
debug1: load_hostkeys: fopen /home/node/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '<REDACTED_HOSTNAME>' is known and matches the ECDSA host key.
debug1: Found key in /home/node/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
debug1: Will attempt key: /home/node/.ssh/id_rsa 
debug1: Will attempt key: /home/node/.ssh/id_ecdsa 
debug1: Will attempt key: /home/node/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/node/.ssh/id_ed25519 
debug1: Will attempt key: /home/node/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/node/.ssh/id_xmss 
debug1: Will attempt key: /home/node/.ssh/id_dsa 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/node/.ssh/id_rsa
debug1: Trying private key: /home/node/.ssh/id_ecdsa
debug1: Trying private key: /home/node/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/node/.ssh/id_ed25519
debug1: Trying private key: /home/node/.ssh/id_ed25519_sk
debug1: Trying private key: /home/node/.ssh/id_xmss
debug1: Trying private key: /home/node/.ssh/id_dsa
debug1: No more authentication methods to try.
git@<REDACTED_HOSTNAME>: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Note: `id_rsa` is encrypted and requires a password (dah! given when `ssh-add`)

**Comment by pedrodaniel10** [comment]
The issue is fixed by updating OpenSSH to the latest version: 9.2.2.0 BETA.

I ran the command:
```powershell
winget install "openssh beta"
```

However, in my view, it only confirms the problem. It should be using WSL's ssh-agent instead of Windows'.

**Comment by bamurtaugh** [comment]
Thanks for the update, @pedrodaniel10!

**Comment by aeschli** [comment]
You are running devcontainers on Windows (via WSL), correct?

**Comment by chrmarti** [comment]
It should prefer the ssh-agent in WSL over the one in Windows when you are using Execute in WSL and/or a WSL folder. Make sure `SSH_AUTH_SOCK` is set in your WSL shell's startup scripts and share your log when it still does not work (`F1` > `Dev Containers: Show Container Log`).
