### ISSUE TITLE
all remote server  have   " connect timeout "   

### ISSUE THREAD

**Issue by lancerk999** [microsoft/vscode-remote-release#8937]
Type: <b>Bug</b>

[08:30:33.981] Remote server is listening on port 44868
[08:30:33.983] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":44868},"osReleaseId":"centos","arch":"x86_64","sshAuthSock":"","display":"","tmpDir":"/run/user/0","platform":"linux"},"serverStartTime":45,"installUnpackCode":""}
[08:30:33.991] Persisting server connection details to /Users/lancerk/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0b903204-8b617bd08fd9e3fc94d14adb8d358b56e3f72314-0.106.2/data.json
[08:30:33.995] Starting forwarding server. local port 51996 -> socksPort 51884 -> remotePort 44868
[08:30:33.996] Forwarding server listening on port 51996
[08:30:33.996] Waiting for ssh tunnel to be ready
[08:30:33.997] [Forwarding server port 51996] Got connection 0
[08:30:33.998] Tunneled port 44868 to local port 51996
[08:30:33.998] Resolved "ssh-remote+myserver-tencent" to "port 51996"
[08:30:36.054] > local-server-2> Timed out
[08:30:36.055] Local server exit: 0

Extension version: 0.106.2
VS Code version: Code 1.82.0 (Universal) (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin arm64 22.6.0
Modes:
Connection to 'ssh-remote+myserver-tencent-pgsql' could not be established
Connection to 'ssh-remote+192.168.101.213-xk-centos7-server-postgresql-root' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id 6e4bf43e-cef7-4faa-9b93-1657cf5df6a7|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+myserver-tencent-pgsql' could not be established

Connection to 'ssh-remote+192.168.101.213-xk-centos7-server-postgresql-root' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30831758
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by wurining** [comment]
Same here. After updating the vscode, the remote plugin is updated to v0.106.2 as well. Then all remote connections are unavailable. 

You can try to rollback to v0.105* to resolve it temporally.

**Comment by jonkelling** [comment]
rolling back to v0.105.3 did not help for me

**Comment by jonkelling** [comment]
0.102.0 did work

**Comment by wurining** [comment]
Another problem as below
<img width="384" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/26198634/961a44be-7ed3-47fb-b78a-94e0c7de15c6">

Are there anybody saw this `sleep 180` process? Does it use for keeping the ssh connection?

**Comment by lancerk999** [comment]
i have rollback to  v0.106.1  it's last version   ,  and  it work.

**Comment by kbumsik** [comment]
I have exactly the same issue with `0.106.2`.

In my case I did "Switch to Pre-Release Version" then it works.

So the issue is certainly fixed in preview version.

The preview version is `v0.107.2023090815 `

**Comment by wurining** [comment]
This works for me, and steps are as follow:
- rollback to `v0.106.1` on local
- set `remote.SSH.useExecServer:true` on local
- execute `Remote-SSH: Uninstall VS Code Server from Host...` on local
- login remote host
- reinstall all previous plugins

But there is still a problem. When close the vscode window, there is a zombie process of `exec server` kept. I had to manually kill it.

I guess this problem is brought by the update of vscode. 
https://github.com/microsoft/vscode/releases/tag/1.82.0

**Comment by bamurtaugh** [comment]
Thanks all for filing. I believe this should now be resolved with the latest VS Code and Remote-SSH extension. If not, please just let me know. Thanks!
