### ISSUE TITLE
Reveal in File Explorer feature won't work when using WSL2 remote

### ISSUE THREAD

**Issue by LuisAlbertoVasquezVargas** [microsoft/vscode-remote-release#9037]
- VSCode Version: v0.81.5
- Local OS Version: Windows 10 22H2 Build 19045.3516
- Remote OS Version: WSL2 Ubuntu-22.04

- Logs: No logs

Steps to Reproduce:

1. Open any directory under the WSL.
2. Navigate into the explorer and right click any folder, then choose Reveal in File Explorer.
3. Nothing happens.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

As a side note, I reverted to the previous version v0.81.5 and it works pretty well, looks like the issue is with a bug in the latest patch that was released some hours ago.

**Comment by naoppy** [comment]
[FYI]
I have same issue, I found WSL<=0.81.4 works well, but WSL>=0.81.5 doesn't work.

**Comment by hamirmahal** [comment]
I'm running into the issue right now.

**Comment by hamirmahal** [comment]
I'm running into this issue right now.

**Comment by hamirmahal** [comment]
For any potential contributors looking to fix this issue, what codebases should we look into modifying to fix this issue, and how would we test that our changes worked?

**Comment by hamirmahal** [comment]
For any potential contributors looking to fix this, what codebases should we look into modifying to fix this issue, and how would we test that our changes worked?

**Comment by aeschli** [comment]
I released a fix in WSL extension version 0.81.8

**Comment by hamirmahal** [comment]
This functionality seems to be working with `v0.81.8` of the `WSL` extension.

**Comment by hamirmahal** [comment]
Thank you!

**Comment by naoppy** [comment]
I also verified `v0.81.8` works fine. Thank you for maintainers!

**Comment by thisisbinh** [comment]
For those that see their WSL extension in VSCode has version v0.81.8 but "Reveal in File Explorer" still does not work, just do a reload of the VSCode and it should work. If the WSL the extension says "Reload required", you can click that as well.

**Comment by hamirmahal** [comment]
> I am still having an issue, even with v0.81.8 and restarting VSCode.
> 
> When I click "Reveal in File Explorer", file explorer opens, but it doesn't open to the correct folder. It always opens to the "Desktop" folder for some reason.

It works for me on Ubuntu 22.04 LTS.

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-36-generic snap
```

I have

```
WSL
v0.81.8
```

**Comment by hamirmahal** [comment]
> I am still having an issue, even with v0.81.8 and restarting VSCode.
> 
> When I click "Reveal in File Explorer", file explorer opens, but it doesn't open to the correct folder. It always opens to the "Desktop" folder for some reason.

It works for me on Ubuntu 22.04 LTS.

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-36-generic snap
```

I have

```
WSL
v0.81.8
```

What operating system are you using, and does the issue reoccur reliably, even after restarting your machine?
