### ISSUE TITLE
devcontainer build fails, VS Code Server SHA mismatch

### ISSUE THREAD

**Issue by jdhenry08** [microsoft/vscode-remote-release#9670]
Attempting to rebuild a known working dev container fails and gives me the following error:
```
[3632 ms] Installing VS Code Server for commit b356b209a5a41743b45f25d569a7afb733d347a9
[3632 ms] Start: Run in Host: docker exec -i -u root 536fd7d57c7db98de6279b95ba072431434151f17c1708705b984fb901970a19 /bin/sh
[3636 ms] Start: Downloading VS Code Server
[3636 ms] b356b209a5a41743b45f25d569a7afb733d347a9 linux-x64 insider 
[7687 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:b356b209a5a41743b45f25d569a7afb733d347a9/server-linux-x64/insider): SHA mismatch, actual d10ac8442366646149d78786feeb6f19592e6cd2b5745815dd2f77886763c988 != expected 5d0baef113dfd8c5c44d0d6cce1292e86bc24646c098cd3b54fcebeae2e5286f
```

- VSCode Version: 1.88.0-insider
- Local OS Version: Windows 11 x64
- Remote OS Version: WSL running Ubuntu 22.04 (jammy)
- Remote Extension/Connection Type: Local > WSL > dev container (mcr.microsoft.com/devcontainers/typescript-node)

Does this issue occur when you try this locally?: No, it's specific to dev container startup
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by specter119** [comment]
Can reproduced this, I think SHA need to be fixed ASAP.

**Comment by astrooom** [comment]
Can reproduce as well.

**Comment by pharrisee** [comment]
Getting same issue here:

`Installing VS Code Server for commit b356b209a5a41743b45f25d569a7afb733d347a9
[4692 ms] Start: Run in Host: docker exec -i -u root 40e4ebfe37ba0833387a61054120758daf74f6cc930bae334fbb0bcefc2f0ea3 /bin/sh
[4697 ms] Start: Downloading VS Code Server
[4698 ms] b356b209a5a41743b45f25d569a7afb733d347a9 linux-x64 insider 
[20391 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:b356b209a5a41743b45f25d569a7afb733d347a9/server-linux-x64/insider): SHA mismatch, actual d10ac8442366646149d78786feeb6f19592e6cd2b5745815dd2f77886763c988 != expected 5d0baef113dfd8c5c44d0d6cce1292e86bc24646c098cd3b54fcebeae2e5286f`

- VSCode Version: 1.88.0-insider
- Local OS Version: Windows 10 x64 (Education)
- Remote OS Version: WSL running Ubuntu 23.10
- Remote Extension/Connection Type: Local > WSL > dev container (mcr.microsoft.com/devcontainers/go)

**Comment by chrmarti** [comment]
This is fixed in the latest Insiders. Thanks!

**Comment by specter119** [comment]
> This is fixed in the latest Insiders. Thanks!

ssh remote can not work yet, after 2 ~ 3 versions.

the last working version is `9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a`

**Comment by deepak1556** [comment]
SSH issue is unrelated to the SHA mismatch as the reporter mentions it is broken for past versions as well.

@specter119 can you open a separate issue with relevant logs.

**Comment by deepak1556** [comment]
Steps for verification:

* run `DevContainers: Open folder in container`
* Choose any container from the template
* Ensure you are able to connect to the container without issues.

**Comment by AlexYangGitHub** [comment]
![截圖 2024-04-30 上午6 51 59](https://github.com/microsoft/vscode-remote-release/assets/10139176/ed752256-f7cf-4cfe-bb67-8ee0186fef9a)

In latest VS code, I still faced the same issue.
 
![截圖 2024-04-30 上午6 44 52](https://github.com/microsoft/vscode-remote-release/assets/10139176/6f6c0eb9-e28f-4dff-8f47-0a656cb345b0)

**Comment by AlexYangGitHub** [comment]
how to solve it ?

**Comment by chrmarti** [comment]
@AlexYangGitHub This looks like a different issue. I'll copy your report to a new issue to track it. Thanks.
